from ..mutable import UflMutableList as UflMutableList
from ..patch import UflListPatch as UflListPatch
from .immutable import UflImmutable as UflImmutable

class UflList(UflImmutable):
    def __init__(self, type, values=None) -> None: ...
    @property
    def type(self): ...
    def __iter__(self): ...
    def get_item(self, index): ...
    def get_length(self): ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other): ...
    def make_mutable(self): ...
    def apply_patch(self, patch) -> None: ...
    def copy(self): ...
