from ..mutable import UflMutableList as UflMutableList
from ..patch import UflListPatch as UflListPatch
from .immutable import UflImmutable as UflImmutable

from typing import (
    Iterator,
    List,
    Optional,
)
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.mutable.list import UflMutableList
from umlfri2.ufl.objects.patch.list import UflListPatch
from umlfri2.ufl.types.structured.list import UflListType

class UflList(UflImmutable):
    def __init__(
        self,
        type: UflListType,
        values: Optional[List[UflObject]] = ...
    ) -> None: ...
    @property
    def type(self): ...
    def __iter__(self) -> Iterator[UflObject]: ...
    def get_item(self, index): ...
    def get_length(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other): ...
    def make_mutable(self) -> UflMutableList: ...
    def apply_patch(self, patch: UflListPatch) -> None: ...
    def copy(self): ...
