from ..mutable import UflMutableObject as UflMutableObject
from ..patch import UflObjectPatch as UflObjectPatch
from .immutable import UflImmutable as UflImmutable
from _typeshed import Incomplete
from collections.abc import Generator

from typing import (
    Any,
    Dict,
)
from umlfri2.ufl.objects.mutable.object import UflMutableObject
from umlfri2.ufl.objects.patch.object import UflObjectPatch
from umlfri2.ufl.types.structured.object import UflObjectType

class UflObject(UflImmutable):
    def __init__(self, type: UflObjectType, attributes: Dict[str, Any]) -> None: ...
    @property
    def type(self): ...
    def __eq__(self, other): ...
    def get_values(self) -> Generator[Incomplete, Incomplete]: ...
    def get_value(self, name: str) -> Any: ...
    def make_mutable(self) -> UflMutableObject: ...
    def apply_patch(self, patch: UflObjectPatch) -> None: ...
    def copy(self): ...
