from PyQt5.QtWidgets import QStyledItemDelegate, QTableWidget
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.addon.online import OnlineAddOn as OnlineAddOn
from umlfri2.qtgui.base import image_loader as image_loader

class AddOnListWidget(QTableWidget):
    EXPANDING_BUTTON_BOX: bool
    class __NoSelectionItemDelegate(QStyledItemDelegate):
        def initStyleOption(self, option, index) -> None: ...
    check_changed: Incomplete
    def __init__(self, check_boxes: bool = False, show_prev_version: bool = False) -> None: ...
    def refresh(self): ...
    def focusInEvent(self, event) -> None: ...
    def focusOutEvent(self, event) -> None: ...
    @property
    def checked_addons(self) -> Generator[Incomplete, Incomplete]: ...
