from umlfri2.application.events.addon import ActionEnableStatusChangedEvent as ActionEnableStatusChangedEvent, ActionTriggeredEvent as ActionTriggeredEvent

class AddOnAction:
    def __init__(self, application, id) -> None: ...
    @property
    def id(self): ...
    @property
    def addon(self): ...
    @property
    def enabled(self): ...
    @enabled.setter
    def enabled(self, value) -> None: ...
    def trigger(self) -> None: ...
