from umlfri2.application.events.addon import ActionEnableStatusChangedEvent as ActionEnableStatusChangedEvent, ActionTriggeredEvent as ActionTriggeredEvent
from umlfri2.application.addon.local.addon import AddOn
from umlfri2.application.application import Application


class AddOnAction:
    def __init__(self, application: Application, id: str) -> None: ...
    @property
    def id(self) -> str: ...
    @property
    def addon(self): ...
    @property
    def enabled(self): ...
    @enabled.setter
    def enabled(self, value) -> None: ...
    def trigger(self) -> None: ...
