from _typeshed import Incomplete
from collections.abc import Generator

class GuiInjection:
    def __init__(self, actions, toolbars) -> None: ...
    def reset(self) -> None: ...
    @property
    def actions(self) -> Generator[Incomplete, Incomplete]: ...
    def get_action(self, id): ...
    @property
    def toolbars(self) -> Generator[Incomplete, Incomplete]: ...
