from _typeshed import Incomplete
from collections.abc import Generator

class ToolBar:
    def __init__(self, label, items) -> None: ...
    @property
    def addon(self): ...
    @property
    def id(self): ...
    @property
    def label(self): ...
    @property
    def items(self) -> Generator[Incomplete, Incomplete]: ...
