from ..base.clipboard import QtClipboardAdatper as QtClipboardAdatper
from ..newproject import NewProjectDialog as NewProjectDialog
from ..projecttree import ProjectTree as ProjectTree
from ..properties import PropertiesWidget as PropertiesWidget
from ..splashscreen.exitscreen import ExitScreen as ExitScreen
from ..toolbox import MainToolBox as MainToolBox
from .addontoolbar import AddOnToolBar as AddOnToolBar
from .aligntoolbar import AlignToolBar as AlignToolBar
from .menu import MainWindowMenu as MainWindowMenu
from .tabs import Tabs as Tabs
from .toolbar import MainToolBar as MainToolBar
from PyQt5.QtWidgets import QMainWindow
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application import Application as Application
from umlfri2.application.addon.local import AddOnState as AddOnState
from umlfri2.application.events.addon import AddOnStateChangedEvent as AddOnStateChangedEvent
from umlfri2.application.events.application import ChangeStatusChangedEvent as ChangeStatusChangedEvent, LanguageChangedEvent as LanguageChangedEvent, UpdateCheckFinishedEvent as UpdateCheckFinishedEvent
from umlfri2.application.events.solution import CloseSolutionEvent as CloseSolutionEvent, OpenSolutionEvent as OpenSolutionEvent, SaveSolutionEvent as SaveSolutionEvent
from umlfri2.application.events.tabs import TabLockStatusChangedEvent as TabLockStatusChangedEvent
from umlfri2.constants.paths import CONFIG as CONFIG, GRAPHICS as GRAPHICS
from umlfri2.constants.solutionfile import SOLUTION_EXTENSION as SOLUTION_EXTENSION

class UmlFriMainWindow(QMainWindow):
    def __init__(self) -> None: ...
    def createPopupMenu(self) -> None: ...
    def closeEvent(self, event) -> None: ...
    def dragEnterEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...
    def get_toolbar_actions(self) -> Generator[Incomplete]: ...
    def get_dock_actions(self) -> Generator[Incomplete]: ...
    @property
    def project_tree(self): ...
    def new_project(self) -> None: ...
    def open_solution(self) -> None: ...
    def open_recent_file(self, recent_file) -> None: ...
    def open_solution_from_file(self, file_name) -> None: ...
    def save_solution(self): ...
    def save_solution_as(self): ...
