from .controlcomponent import ControlComponent as ControlComponent
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.ufl.types.basic import UflBoolType as UflBoolType, UflIntegerType as UflIntegerType
from umlfri2.ufl.types.generic import UflAnyType as UflAnyType
from umlfri2.ufl.types.structured import UflIterableType as UflIterableType, UflVariableWithMetadataType as UflVariableWithMetadataType

class ForEachItemMetadata:
    def __init__(self, value, count, index) -> None: ...
    @property
    def value(self): ...
    @property
    def index(self): ...
    @property
    def count(self): ...
    @property
    def is_first(self): ...
    @property
    def is_last(self): ...
    @staticmethod
    def build_node_metadata_type(item_type): ...

class ForEachComponent(ControlComponent):
    ATTRIBUTES: Incomplete
    def __init__(self, children, src, item) -> None: ...
    def compile(self, type_context) -> None: ...
    def filter_children(self, context) -> Generator[Incomplete, Incomplete]: ...
