from PyQt5.QtGui import (
    QContextMenuEvent,
    QDragEnterEvent,
    QDropEvent,
    QMouseEvent,
    QPaintEvent,
    QWheelEvent,
)
from typing import Union
from umlfri2.application.drawingarea.drawingarea import DrawingArea
from umlfri2.model.diagram import Diagram
from umlfri2.qtgui.fullscreen.fullscreen import FullScreenDiagram
from umlfri2.qtgui.mainwindow.mainwindow import UmlFriMainWindow


class CanvasWidget:
    def __init__(
        self,
        main_window: Union[UmlFriMainWindow, FullScreenDiagram],
        drawing_area: DrawingArea
    ) -> None: ...
    def contextMenuEvent(self, event: QContextMenuEvent) -> None: ...
    @property
    def diagram(self) -> Diagram: ...
    def dragEnterEvent(self, event: QDragEnterEvent) -> None: ...
    def dropEvent(self, event: QDropEvent) -> None: ...
    def mouseDoubleClickEvent(self, event: QMouseEvent) -> None: ...
    def mouseMoveEvent(self, event: QMouseEvent) -> None: ...
    def mousePressEvent(self, event: QMouseEvent) -> None: ...
    def mouseReleaseEvent(self, event: QMouseEvent) -> None: ...
    def paintEvent(self, event: QPaintEvent) -> None: ...
    def wheelEvent(self, event: QWheelEvent) -> None: ...
