from ...expressions.tree import *
from ...expressions.tree.visitor import UflVisitor as UflVisitor

class LambdaInliningVisitorImpl(UflVisitor):
    def __init__(self, replacements) -> None: ...
    def visit_attribute_access(self, node): ...
    def visit_enum(self, node): ...
    def visit_macro_invoke(self, node): ...
    def visit_technical_variable(self, node): ...
    def visit_variable(self, node): ...
    def visit_variable_definition(self, node) -> None: ...
    def visit_literal(self, node): ...
    def visit_binary(self, node): ...
    def visit_unary(self, node): ...
    def visit_variable_metadata_access(self, node): ...
    def visit_object_metadata_access(self, node): ...
    def visit_unpack(self, node): ...
    def visit_expression(self, node) -> None: ...
    def visit_lambda_expression(self, node): ...
    def visit_cast(self, node): ...
