from PyQt5.QtWidgets import QDialog, QLineEdit
from umlfri2.constants.keys import STRIKE_OUT as STRIKE_OUT
from umlfri2.types.enums import FontStyle as FontStyle
from umlfri2.types.font import Fonts as Fonts

class UpDownPassingLineEdit(QLineEdit):
    def __init__(self) -> None: ...
    @property
    def destination_widget(self): ...
    @destination_widget.setter
    def destination_widget(self, value) -> None: ...
    def keyPressEvent(self, event) -> None: ...
    def keyReleaseEvent(self, event) -> None: ...

class FontDialog(QDialog):
    def __init__(self, parent=None) -> None: ...
    @property
    def ufl_font(self): ...
    @ufl_font.setter
    def ufl_font(self, value) -> None: ...
