from umlfri2.ufl.context import Context as Context

class ConnectionTypeLabel:
    def __init__(self, position, id, appearance) -> None: ...
    @property
    def connection_type(self): ...
    @property
    def position(self): ...
    @property
    def id(self): ...
    def compile(self, type_context) -> None: ...
    def create_appearance_object(self, connection, ruler): ...
