from umlfri2.ufl.context import Context as Context
from umlfri2.ufl.types.complex import UflColorType as UflColorType

class DiagramType:
    def __init__(self, id, icon, ufl_type, display_name, element_types, connection_types, background_color) -> None: ...
    @property
    def metamodel(self): ...
    @property
    def id(self): ...
    @property
    def icon(self): ...
    @property
    def ufl_type(self): ...
    @property
    def element_types(self): ...
    @property
    def connection_types(self): ...
    def get_background_color(self, diagram): ...
    def compile(self, type_context) -> None: ...
    def get_display_name(self, diagram): ...
