from typing import (
    Iterator,
    Tuple,
)
from umlfri2.application.application import Application
from umlfri2.application.updates import UmlFriUpdates


class AboutUmlFri:
    def __init__(self, application: Application) -> None: ...
    @property
    def author(self) -> Iterator[Tuple[str, Tuple[int, int]]]: ...
    @property
    def dependency_versions(self) -> Iterator[Tuple[str, str]]: ...
    @property
    def description(self) -> str: ...
    @property
    def updates(self) -> UmlFriUpdates: ...
    @property
    def urls(self) -> Iterator[str]: ...
    @property
    def version_1_contributions(self) -> Iterator[Tuple[str, Tuple[int, int]]]: ...
