from typing import (
    Any,
    Iterator,
    List,
    Optional,
    Union,
)
from umlfri2.application.about import AboutUmlFri
from umlfri2.application.addon.list import AddOnList
from umlfri2.application.commandprocessor import CommandProcessor
from umlfri2.application.config import ApplicationConfig
from umlfri2.application.dispatcher import EventDispatcher
from umlfri2.application.language import LanguageManager
from umlfri2.application.recentfile import RecentFile
from umlfri2.application.tablist import TabList
from umlfri2.metamodel.projecttemplate.project import ProjectTemplate
from umlfri2.model.diagram import Diagram
from umlfri2.model.element.elementobject import ElementObject
from umlfri2.model.project import Project
from umlfri2.model.solution import Solution
from umlfri2.qtgui.base.qtthreadmanager import QTThreadManager
from umlfri2.qtgui.rendering.qtruler import QTRuler


class Application:
    def __init__(self) -> None: ...
    @property
    def about(self) -> AboutUmlFri: ...
    @property
    def addons(self) -> AddOnList: ...
    @property
    def can_save_solution(self) -> bool: ...
    @property
    def can_save_solution_as(self) -> bool: ...
    @property
    def change_status(self) -> bool: ...
    @property
    def clipboard_empty(self) -> bool: ...
    def close_solution(self) -> None: ...
    @property
    def commands(self) -> CommandProcessor: ...
    @property
    def config(self) -> ApplicationConfig: ...
    @property
    def event_dispatcher(self) -> EventDispatcher: ...
    def init_after_main_window_shown(self) -> None: ...
    @property
    def language(self) -> LanguageManager: ...
    def new_project(
        self,
        template: ProjectTemplate,
        new_solution: bool = ...,
        project_name: str = ...
    ) -> None: ...
    def open_solution(self, filename: str) -> None: ...
    def open_solution_in_steps(self, filename: str) -> Iterator[str]: ...
    @property
    def recent_files(self) -> Iterator[RecentFile]: ...
    @property
    def ruler(self) -> QTRuler: ...
    def save_solution(self) -> None: ...
    def save_solution_as(self, filename: str) -> None: ...
    def select_item(
        self,
        element: Optional[Union[Project, Diagram, ElementObject]]
    ) -> None: ...
    @property
    def should_save_as(self) -> bool: ...
    @property
    def solution(self) -> Optional[Solution]: ...
    @property
    def solution_name(self) -> Optional[str]: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def tabs(self) -> TabList: ...
    @property
    def templates(self) -> Iterator[ProjectTemplate]: ...
    @property
    def thread_manager(self) -> Optional[QTThreadManager]: ...
    @property
    def unsaved(self) -> bool: ...
    def use_args(self, args: List[Any]) -> None: ...
    def use_ruler(self, ruler: QTRuler) -> None: ...
    def use_thread_manager(self, thread_manager: QTThreadManager) -> None: ...


class MetaApplication:
    def __call__(cls) -> Application: ...
