from umlfri2.application.application import Application
from umlfri2.application.commands.base.command import Command


class CommandProcessor:
    def __init__(self, application: Application) -> None: ...
    @property
    def can_redo(self) -> bool: ...
    @property
    def can_undo(self) -> bool: ...
    @property
    def changed(self) -> bool: ...
    def clear_buffers(self) -> None: ...
    def execute(self, command: Command) -> None: ...
    def mark_unchanged(self) -> None: ...
    def redo(self, count: int = ...) -> None: ...
    def undo(self, count: int = ...) -> None: ...
