class ApplicationConfig:
    def __init__(self) -> None: ...
    @property
    def export_padding(self) -> int: ...
    @property
    def export_zoom(self) -> int: ...
    @property
    def ignored_versions(self) -> None: ...
    def unignore_versions(self, *versions) -> None: ...
