from umlfri2.application.application import Application
from umlfri2.application.recentfiles import RecentFiles


class RecentFile:
    def __init__(
        self,
        application: Application,
        recent_files: RecentFiles,
        file_path: str,
        pinned: bool = ...
    ) -> None: ...
    @property
    def exists(self) -> bool: ...
    @property
    def file_name(self) -> str: ...
    def open(self) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def pinned(self) -> bool: ...
