from umlfri2.application.application import Application
from umlfri2.application.drawingarea.drawingarea import DrawingArea
from umlfri2.application.tablist import TabList
from umlfri2.model.diagram import Diagram
from umlfri2.types.image import Image


class Tab:
    def __init__(
        self,
        application: Application,
        tabs: TabList,
        diagram: Diagram,
        locked: bool = ...
    ) -> None: ...
    def close(self) -> None: ...
    @property
    def drawing_area(self) -> DrawingArea: ...
    @property
    def icon(self) -> Image: ...
    def lock(self) -> None: ...
    @property
    def locked(self) -> bool: ...
    @property
    def name(self) -> str: ...
    def unlock(self) -> None: ...
