from typing import (
    Any,
    Iterator,
    Optional,
)
from umlfri2.application.application import Application
from umlfri2.application.tab import Tab
from umlfri2.model.diagram import Diagram


class TabList:
    def __init__(self, application: Application) -> None: ...
    def __iter__(self) -> Iterator[Tab]: ...
    def _close_tab(self, tab: Tab) -> None: ...
    @property
    def current_tab(self) -> Optional[Tab]: ...
    def get_tab_for(self, diagram: Diagram) -> Tab: ...
    @property
    def lock_status_changed(self) -> bool: ...
    def open_new_project_tabs(self, tabs: Iterator[Any]) -> None: ...
    def reset_lock_status(self) -> None: ...
    def select_tab(self, diagram: Optional[Diagram]) -> Optional[Tab]: ...
