from ..base.helpercomponent import HelperComponent as HelperComponent
from .controlcomponent import ControlComponent as ControlComponent
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.ufl.types.generic import UflAnyType as UflAnyType

class SwitchCaseComponent(HelperComponent):
    ATTRIBUTES: Incomplete
    def __init__(self, children, value) -> None: ...
    def get_value(self, context): ...
    def retype(self, type) -> None: ...
    def compile(self, type_context) -> None: ...

class SwitchDefaultComponent(HelperComponent):
    def compile(self, type_context) -> None: ...

class SwitchComponent(ControlComponent):
    ATTRIBUTES: Incomplete
    SPECIAL_CHILDREN: Incomplete
    ONLY_SPECIAL_CHILDREN: bool
    def __init__(self, children, value) -> None: ...
    def compile(self, type_context) -> None: ...
    def filter_children(self, context) -> Generator[Incomplete, Incomplete]: ...
