from ..mutable import UflMutableFlags as UflMutableFlags
from ..patch import UflFlagsPatch as UflFlagsPatch
from .immutable import UflImmutable as UflImmutable

class UflFlags(UflImmutable):
    def __init__(self, type, values=None) -> None: ...
    @property
    def type(self): ...
    def __iter__(self): ...
    def __contains__(self, item) -> bool: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other): ...
    def make_mutable(self): ...
    def apply_patch(self, patch) -> None: ...
    def copy(self): ...
