class UflImmutable:
    @property
    def type(self) -> None: ...
    def make_mutable(self) -> None: ...
    def apply_patch(self, patch) -> None: ...
    def copy(self) -> None: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
