from ..mutable import UflMutableObject as UflMutableObject
from ..patch import UflObjectPatch as UflObjectPatch
from .immutable import UflImmutable as UflImmutable
from _typeshed import Incomplete
from collections.abc import Generator

class UflObject(UflImmutable):
    def __init__(self, type, attributes) -> None: ...
    @property
    def type(self): ...
    def __eq__(self, other): ...
    def get_values(self) -> Generator[Incomplete, Incomplete]: ...
    def get_value(self, name): ...
    def make_mutable(self): ...
    def apply_patch(self, patch) -> None: ...
    def copy(self): ...
