from PyQt5.QtGui import QPainter as QPainter
from umlfri2.qtgui.base import image_loader as image_loader
from umlfri2.qtgui.rendering.qtruler import QTRuler as QTRuler
from umlfri2.types.enums import LineStyle as LineStyle
from umlfri2.types.font import FontStyle as FontStyle
from umlfri2.types.geometry import PathCubicTo as PathCubicTo, PathLineTo as PathLineTo, Vector as Vector
from umlfri2.ufl.components.visual.canvas import Canvas as Canvas

class QTPainterCanvas(Canvas):
    def __init__(self, painter) -> None: ...
    def translate(self, delta) -> None: ...
    def zoom(self, zoom) -> None: ...
    def draw_ellipse(self, rectangle, fg=None, bg=None, line_width=None, line_style=None) -> None: ...
    def draw_line(self, start, end, fg, line_width=None, line_style=None) -> None: ...
    def draw_path(self, path, fg=None, bg=None, line_width=None, line_style=None) -> None: ...
    def draw_rectangle(self, rectangle, fg=None, bg=None, line_width=None, line_style=None) -> None: ...
    def draw_text(self, pos, text, font, fg) -> None: ...
    def draw_image(self, pos, image) -> None: ...
    def clear(self, color=None) -> None: ...
    def get_ruler(self): ...
