from ..base.type import UflType as UflType

from typing import (
    Optional,
    Union,
)
from umlfri2.model.element.elementobject import ElementValueGenerator
from umlfri2.ufl.objects.mutable.list import ListItemValueGenerator

class UflBoolType(UflType):
    def __init__(self, default: None = ...) -> None: ...
    @property
    def default(self): ...
    @property
    def has_default(self): ...
    def build_default(
        self,
        generator: Optional[Union[ElementValueGenerator, ListItemValueGenerator]]
    ) -> bool: ...
    def parse(self, value: str) -> bool: ...
    @property
    def is_immutable(self) -> bool: ...
    def is_valid_value(self, value: bool) -> bool: ...
    def is_default_value(self, value: bool) -> bool: ...
    def is_equatable_to(self, other): ...
