from ..base.type import UflType as UflType
from .string import UflStringType as UflStringType

class UflNumberType(UflType):
    def __init__(self, default=None) -> None: ...
    @property
    def default(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator): ...
    def parse(self, value): ...
    @property
    def is_immutable(self): ...
    def is_valid_value(self, value): ...
    def is_default_value(self, value): ...
    def is_equatable_to(self, other): ...
    def is_comparable_with(self, other): ...
    def is_convertible_to(self, other): ...
