from ..base.type import UflType as UflType

from typing import (
    Optional,
    Tuple,
    Union,
)
from umlfri2.model.diagram import DiagramValueGenerator
from umlfri2.model.element.elementobject import ElementValueGenerator
from umlfri2.ufl.components.text.textcontainer import TextContainerComponent
from umlfri2.ufl.objects.mutable.list import ListItemValueGenerator

class UflStringType(UflType):
    def __init__(
        self,
        possibilities: Optional[Tuple[str, str, str, str, str, str, str, str]] = ...,
        default: None = ...,
        template: Optional[TextContainerComponent] = ...,
        multiline: bool = ...
    ) -> None: ...
    @property
    def default(self): ...
    @property
    def possibilities(self) -> Optional[Tuple[str, str, str, str, str, str, str, str]]: ...
    @property
    def multiline(self) -> bool: ...
    @property
    def template(self): ...
    @property
    def has_default(self): ...
    def build_default(
        self,
        generator: Optional[Union[ElementValueGenerator, ListItemValueGenerator, DiagramValueGenerator]]
    ) -> str: ...
    def parse(self, value: str) -> str: ...
    @property
    def is_immutable(self) -> bool: ...
    def is_equatable_to(self, other): ...
    def is_valid_value(self, value: str) -> bool: ...
    def is_default_value(self, value: str) -> bool: ...
