from ..base.type import UflType as UflType

class UflStringType(UflType):
    def __init__(self, possibilities=None, default=None, template=None, multiline: bool = False) -> None: ...
    @property
    def default(self): ...
    @property
    def possibilities(self): ...
    @property
    def multiline(self): ...
    @property
    def template(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator): ...
    def parse(self, value): ...
    @property
    def is_immutable(self): ...
    def is_equatable_to(self, other): ...
    def is_valid_value(self, value): ...
    def is_default_value(self, value): ...
