from ..base import Event as Event

class ConnectionCreatedEvent(Event):
    def __init__(self, connection, indirect: bool = False) -> None: ...
    @property
    def connection(self): ...
    @property
    def indirect(self): ...
    def get_opposite(self): ...
