from ..base import Event as Event

class DiagramCreatedEvent(Event):
    def __init__(self, diagram, index=None, indirect: bool = False) -> None: ...
    @property
    def diagram(self): ...
    @property
    def index(self): ...
    @property
    def indirect(self): ...
    def get_opposite(self): ...
