from ..base import Event as Event

class ElementCreatedEvent(Event):
    def __init__(self, element, index=None, indirect: bool = False) -> None: ...
    @property
    def element(self): ...
    @property
    def index(self): ...
    @property
    def indirect(self): ...
    def get_opposite(self): ...
