from ..base import Event as Event

class NodeMovedEvent(Event):
    def __init__(self, node, old_parent, old_index, new_parent, new_index) -> None: ...
    @property
    def node(self): ...
    @property
    def old_parent(self): ...
    @property
    def old_index(self): ...
    @property
    def new_parent(self): ...
    @property
    def new_index(self): ...
    def get_opposite(self): ...
