from ..base import Event as Event

class ObjectDataChangedEvent(Event):
    def __init__(self, object, patch) -> None: ...
    @property
    def object(self): ...
    @property
    def patch(self): ...
    def get_opposite(self): ...
