from ..drawingareacursor import DrawingAreaCursor as DrawingAreaCursor
from _typeshed import Incomplete
from typing import NamedTuple

class ActionMenuItem(NamedTuple):
    icon: Incomplete
    text: Incomplete
    action: Incomplete

class Action:
    def __init__(self) -> None: ...
    def associate(self, application, drawing_area) -> None: ...
    def snap_to(self, snapping) -> None: ...
    def after_finish(self, callback): ...
    @property
    def application(self): ...
    @property
    def drawing_area(self): ...
    @property
    def box(self) -> None: ...
    @property
    def path(self) -> None: ...
    @property
    def vertical_snapping_indicators(self): ...
    @property
    def horizontal_snapping_indicators(self): ...
    @property
    def finished(self): ...
    @property
    def cursor(self): ...
    @property
    def menu_to_show(self) -> None: ...
    def mouse_down(self, point) -> None: ...
    def mouse_move(self, point) -> None: ...
    def mouse_up(self) -> None: ...
