from .action import Action as Action
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.model.element import ElementVisual as ElementVisual
from umlfri2.types.geometry import PathBuilder as PathBuilder, Point as Point
from typing import (
    Iterator,
    Optional,
)
from umlfri2.application.drawingarea.snapping.snapping import Snapping
from umlfri2.types.geometry.path import Path
from umlfri2.types.geometry.point import Point


class AddConnectionAction(Action):
    def __init__(self) -> None: ...
    @property
    def path(self) -> Optional[Path]: ...
    @property
    def horizontal_snapping_indicators(self) -> Iterator[Point]: ...
    @property
    def vertical_snapping_indicators(self) -> Iterator[Point]: ...
    def snap_to(self, snapping: Snapping) -> None: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
