from .action import Action as Action
from umlfri2.application.commands.diagram import AddDiagramElementCommand as AddDiagramElementCommand
from umlfri2.types.geometry.point import Point


class AddElementAction(Action):
    def __init__(self, type: str) -> None: ...
    @property
    def element_type(self): ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
