from ..drawingareacursor import DrawingAreaCursor as DrawingAreaCursor
from .action import Action as Action
from umlfri2.application.commands.diagram import MoveConnectionLabelCommand as MoveConnectionLabelCommand
from umlfri2.types.geometry import Vector as Vector
from umlfri2.application.drawingarea.drawingareacursor import DrawingAreaCursor
from umlfri2.model.connection.connectionvisual import ConnectionVisual
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.rectangle import Rectangle


class MoveConnectionLabelAction(Action):
    def __init__(self, connection: ConnectionVisual, id: str) -> None: ...
    @property
    def cursor(self) -> DrawingAreaCursor: ...
    @property
    def box(self) -> Rectangle: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
