from ..drawingareacursor import DrawingAreaCursor as DrawingAreaCursor
from .action import Action as Action
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.commands.diagram import MoveSelectionCommand as MoveSelectionCommand
from umlfri2.types.geometry import Vector as Vector

class MoveSelectionAction(Action):
    def __init__(self) -> None: ...
    @property
    def cursor(self): ...
    @property
    def box(self): ...
    @property
    def horizontal_snapping_indicators(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def vertical_snapping_indicators(self) -> Generator[Incomplete, Incomplete]: ...
    def snap_to(self, snapping) -> None: ...
    def mouse_down(self, point) -> None: ...
    def mouse_move(self, point) -> None: ...
    def mouse_up(self) -> None: ...
