from ..drawingareacursor import DrawingAreaCursor as DrawingAreaCursor
from .action import Action as Action
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.commands.diagram import MoveConnectionPointCommand as MoveConnectionPointCommand
from umlfri2.types.geometry import PathBuilder as PathBuilder, Point as Point
from typing import Iterator
from umlfri2.application.drawingarea.drawingareacursor import DrawingAreaCursor
from umlfri2.application.drawingarea.snapping.snapping import Snapping
from umlfri2.model.connection.connectionvisual import ConnectionVisual
from umlfri2.types.geometry.path import Path
from umlfri2.types.geometry.point import Point


class MoveConnectionPointAction(Action):
    def __init__(self, connection: ConnectionVisual, index: int) -> None: ...
    @property
    def path(self) -> Path: ...
    @property
    def cursor(self) -> DrawingAreaCursor: ...
    @property
    def horizontal_snapping_indicators(self) -> None: ...
    @property
    def vertical_snapping_indicators(self) -> Iterator[Point]: ...
    def snap_to(self, snapping: Snapping) -> None: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
