from ..drawingareacursor import DrawingAreaCursor as DrawingAreaCursor
from .action import Action as Action
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.commands.diagram import MoveSelectionCommand as MoveSelectionCommand
from umlfri2.types.geometry import Vector as Vector
from typing import Iterator
from umlfri2.application.drawingarea.drawingareacursor import DrawingAreaCursor
from umlfri2.application.drawingarea.snapping.snapping import Snapping
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.rectangle import Rectangle


class MoveSelectionAction(Action):
    def __init__(self) -> None: ...
    @property
    def cursor(self) -> DrawingAreaCursor: ...
    @property
    def box(self) -> Rectangle: ...
    @property
    def horizontal_snapping_indicators(self) -> Iterator[Point]: ...
    @property
    def vertical_snapping_indicators(self) -> Iterator[Point]: ...
    def snap_to(self, snapping: Snapping) -> None: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
