from .action import Action as Action
from umlfri2.types.geometry import Rectangle as Rectangle

class SelectManyAction(Action):
    @property
    def box(self): ...
    def mouse_down(self, point) -> None: ...
    def mouse_move(self, point) -> None: ...
    def mouse_up(self) -> None: ...
