from .action import Action as Action
from umlfri2.types.geometry import Rectangle as Rectangle
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.rectangle import Rectangle


class SelectManyAction(Action):
    @property
    def box(self) -> Rectangle: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
