from typing import (
    Any,
    Iterator,
    Optional,
)
from umlfri2.ufl.components.text.textcontainer import TextContainerComponent
from umlfri2.ufl.types.base.type import UflType


class UflTypeParser:
    def __init__(self, abstract: bool = ...) -> None: ...
    def parse(self, type_name: str) -> UflTypeParserForName: ...


class UflTypeParserForName:
    def __init__(self, abstract: bool, inner_type: str, outer_type: Optional[str]) -> None: ...
    @property
    def can_have_attributes(self) -> bool: ...
    @property
    def can_have_possibilities(self) -> bool: ...
    @property
    def can_have_template(self) -> bool: ...
    def finish(self) -> UflType: ...
    def set_attributes(self, attributes: Iterator[Any]) -> None: ...
    def set_default_value_as_string(self, value: Optional[str]) -> None: ...
    def set_possibilities(self, possibilities: Iterator[Any]) -> None: ...
    def set_template(self, template: TextContainerComponent) -> None: ...
