from ..communication import PipeChannel as PipeChannel
from .starter import PluginStarter as PluginStarter
from _typeshed import Incomplete

class BaseProgramStarter(PluginStarter):
    program: Incomplete
    environment: Incomplete
    def __init__(self, path) -> None: ...
    def start(self): ...
    def terminate(self) -> None: ...
    def kill(self) -> None: ...
    @property
    def is_alive(self): ...
