from typing import Optional
from umlfri2.model.diagram import Diagram


class DiagramCreatedEvent:
    def __init__(self, diagram: Diagram, index: None = ..., indirect: bool = ...) -> None: ...
    @property
    def diagram(self) -> Diagram: ...
    @property
    def index(self) -> None: ...
    @property
    def indirect(self) -> bool: ...
