from typing import Optional
from umlfri2.application.events.model.diagramcreated import DiagramCreatedEvent
from umlfri2.model.diagram import Diagram


class DiagramDeletedEvent:
    def __init__(self, diagram: Diagram, index: None = ..., indirect: bool = ...) -> None: ...
    @property
    def diagram(self) -> Diagram: ...
    def get_opposite(self) -> DiagramCreatedEvent: ...
    @property
    def indirect(self) -> bool: ...
