from ..constants import ONLINE_ADDON_LAST_VERSION_FILE as ONLINE_ADDON_LAST_VERSION_FILE

class OnlineAddOnListSaver:
    def __init__(self, storage) -> None: ...
    def save(self, zipball_storage, version) -> None: ...
