from ..constants import MODEL_NAMESPACE as MODEL_NAMESPACE, MODEL_SCHEMA as MODEL_SCHEMA

class SolutionSaver:
    def __init__(self, storage, path) -> None: ...
    def save(self, solution) -> None: ...
