from .macro import Macro as Macro

class InlinedMacro(Macro):
    @property
    def signature(self) -> None: ...
    def compare_signature(self, selector, argument_types): ...
    def compile(self, visitor, registrar, node) -> None: ...
