from ..base import Command as Command
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.events.model import DiagramCreatedEvent as DiagramCreatedEvent

class CreateDiagramCommand(Command):
    def __init__(self, parent, diagram_type) -> None: ...
    @property
    def description(self): ...
    @property
    def diagram(self): ...
    def get_updates(self) -> Generator[Incomplete]: ...
