from ..base import Command as Command
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.events.model import ElementCreatedEvent as ElementCreatedEvent

class CreateElementCommand(Command):
    def __init__(self, parent, element_type) -> None: ...
    @property
    def description(self): ...
    @property
    def element_object(self): ...
    def get_updates(self) -> Generator[Incomplete]: ...
