from .vector import Vector as Vector

class Size:
    def __init__(self, width, height) -> None: ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    def as_vector(self): ...
    def rotate(self): ...
    def __mul__(self, other): ...
