class Vector:
    def __init__(self, x, y) -> None: ...
    @staticmethod
    def from_angle_length(angle, length): ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    @property
    def angle(self): ...
    @property
    def length(self): ...
    def __bool__(self) -> bool: ...
    def __neg__(self): ...
    def __mul__(self, other): ...
    def __truediv__(self, other): ...
