from .point import Point as Point
from _typeshed import Incomplete
from collections.abc import Generator

class Line:
    def __init__(self, x1, y1, x2, y2) -> None: ...
    @staticmethod
    def from_point_point(p1, p2): ...
    @property
    def first(self): ...
    @property
    def second(self): ...
    def get_abc(self): ...
    def intersect(self, other) -> Generator[Incomplete, Incomplete]: ...
    def get_nearest_point_to(self, other): ...
    def get_distance_to(self, other): ...
