from .point import Point as Point
from .vector import Vector as Vector

class PathCommand:
    def __init__(self, final_point) -> None: ...
    @property
    def final_point(self): ...
    def transform(self, matrix) -> None: ...

class PathLineTo(PathCommand):
    def transform(self, matrix): ...

class PathCubicTo(PathCommand):
    def __init__(self, control_point1, control_point2, final_point) -> None: ...
    @property
    def control_point1(self): ...
    @property
    def control_point2(self): ...
    def transform(self, matrix): ...

class PathSegment:
    def __init__(self, starting_point, commands, closed: bool = False) -> None: ...
    @property
    def starting_point(self): ...
    @property
    def final_point(self): ...
    @property
    def commands(self): ...
    @property
    def closed(self): ...
    def transform(self, matrix): ...

class Path:
    def __init__(self, segments) -> None: ...
    @property
    def segments(self): ...
    def transform(self, matrix): ...

class PathBuilder:
    def __init__(self) -> None: ...
    def build(self): ...
    def move_to(self, point): ...
    def line_to(self, point): ...
    def move_or_line_to(self, point) -> None: ...
    def cubic_to(self, control1, control2, point): ...
    def close(self): ...
    def from_path(self, path, join_moves: bool = False): ...
    def from_string(self, s): ...
