from .size import Size as Size
from .vector import Vector as Vector

class Point:
    def __init__(self, x, y) -> None: ...
    @property
    def x(self): ...
    @property
    def y(self): ...
    def as_vector(self): ...
    def as_size(self): ...
    def round(self): ...
    def __sub__(self, other): ...
    def __add__(self, other): ...
    def transform(self, matrix): ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    @staticmethod
    def parse(param): ...
