from .line import Line as Line
from .point import Point as Point
from .size import Size as Size
from .vector import Vector as Vector
from _typeshed import Incomplete
from collections.abc import Generator

class Rectangle:
    def __init__(self, x, y, width, height) -> None: ...
    @staticmethod
    def from_point_size(point, size): ...
    @staticmethod
    def from_point_point(p1, p2): ...
    @property
    def top_left(self): ...
    @property
    def top_center(self): ...
    @property
    def top_right(self): ...
    @property
    def right_center(self): ...
    @property
    def bottom_left(self): ...
    @property
    def bottom_center(self): ...
    @property
    def bottom_right(self): ...
    @property
    def left_center(self): ...
    @property
    def center(self): ...
    @property
    def size(self): ...
    @property
    def x1(self): ...
    @property
    def y1(self): ...
    @property
    def width(self): ...
    @property
    def height(self): ...
    @property
    def x2(self): ...
    @property
    def y2(self): ...
    def contains(self, point): ...
    def intersect(self, other) -> Generator[Incomplete, Incomplete]: ...
    def get_nearest_point_to(self, other): ...
    def is_overlapping(self, other): ...
    @property
    def all_lines(self) -> Generator[Incomplete]: ...
    def normalize(self): ...
    @staticmethod
    def combine_bounds(rectangles): ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __eq__(self, other): ...
