from .point import Point as Point

class Transformation:
    def __init__(self, m11, m12, m21, m22, offset_x, offset_y) -> None: ...
    @property
    def m11(self): ...
    @property
    def m12(self): ...
    @property
    def m21(self): ...
    @property
    def m22(self): ...
    @property
    def offset_x(self): ...
    @property
    def offset_y(self): ...
    def __mul__(self, other): ...
    @staticmethod
    def make_rotation(alpha, center=...): ...
    @staticmethod
    def make_scale(scale, center=...): ...
    @staticmethod
    def make_scale2(scale, center=...): ...
    @staticmethod
    def make_translate(delta): ...
    @staticmethod
    def make_skew_x(alpha): ...
    @staticmethod
    def make_skew_y(alpha): ...
    @staticmethod
    def make_identity(): ...
