from typing import (
    Iterator,
    Optional,
)
from umlfri2.metamodel.connectiontype import ConnectionType
from umlfri2.model.cache import ModelTemporaryDataCache
from umlfri2.model.connection.connectionvisual import ConnectionVisual
from umlfri2.model.element.elementobject import ElementObject
from umlfri2.model.project import Project
from umlfri2.qtgui.rendering.qtruler import QTRuler
from umlfri2.ufl.components.connectionvisual.connectionvisualcontainer import ConnectionVisualContainerObject
from umlfri2.ufl.components.visual.visualcontainer import VisualObjectContainer
from umlfri2.ufl.dialog.dialog import UflDialog
from umlfri2.ufl.dialog.options import UflDialogOptions
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.patch.object import UflObjectPatch
from uuid import UUID


class ConnectionObject:
    def __init__(
        self,
        type: ConnectionType,
        source: ElementObject,
        destination: ElementObject,
        save_id: Optional[UUID] = ...
    ) -> None: ...
    def add_visual(self, visual: ConnectionVisual) -> None: ...
    def apply_ufl_patch(self, patch: UflObjectPatch) -> None: ...
    @property
    def cache(self) -> ModelTemporaryDataCache: ...
    def create_appearance_object(
        self,
        ruler: QTRuler
    ) -> ConnectionVisualContainerObject: ...
    def create_label_object(
        self,
        id: str,
        ruler: QTRuler
    ) -> VisualObjectContainer: ...
    def create_ufl_dialog(
        self,
        options: UflDialogOptions = ...
    ) -> UflDialog: ...
    @property
    def data(self) -> UflObject: ...
    @property
    def destination(self) -> ElementObject: ...
    def get_other_end(
        self,
        element: ElementObject
    ) -> ElementObject: ...
    @property
    def has_ufl_dialog(self) -> bool: ...
    def is_connected_with(self, element: ElementObject) -> bool: ...
    @property
    def project(self) -> Project: ...
    def remove_visual(self, visual: ConnectionVisual) -> None: ...
    def reverse(self) -> None: ...
    @property
    def save_id(self) -> UUID: ...
    @property
    def source(self) -> ElementObject: ...
    @property
    def type(self) -> ConnectionType: ...
    @property
    def visuals(self) -> Iterator[ConnectionVisual]: ...
