from umlfri2.model.connection.connectionvisual import ConnectionVisual
from umlfri2.qtgui.rendering.qtpaintercanvas import QTPainterCanvas
from umlfri2.qtgui.rendering.qtruler import QTRuler
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.rectangle import Rectangle


class ConnectionLabel:
    def __init__(self, connection: ConnectionVisual, id: str) -> None: ...
    def _adding_point(self, line_index: int, line1_length: float, line2_length: float) -> None: ...
    def _removing_point(self, line_index: int, line1_length: float, line2_length: float) -> None: ...
    @property
    def connection(self) -> ConnectionVisual: ...
    def draw(self, canvas: QTPainterCanvas) -> None: ...
    def get_bounds(self, ruler: QTRuler) -> Rectangle: ...
    def get_nearest_point(self, ruler: QTRuler) -> Point: ...
    def get_position(self, ruler: QTRuler) -> Point: ...
    @property
    def id(self) -> str: ...
    def is_at_position(
        self,
        ruler: QTRuler,
        position: Point
    ) -> bool: ...
    def move(
        self,
        ruler: QTRuler,
        new_position: Point
    ) -> None: ...
