from ..base.type import UflType as UflType
from umlfri2.types.proportion import Proportion as Proportion, WHOLE_PROPORTION as WHOLE_PROPORTION

class UflProportionType(UflType):
    def __init__(self, default=None) -> None: ...
    @property
    def default(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator): ...
    def parse(self, value): ...
    @property
    def is_immutable(self): ...
    def is_valid_value(self, value): ...
    def is_default_value(self, value): ...
