from umlfri2.types.color import Color as Color, Colors as Colors
from umlfri2.ufl.types.base.type import UflAttributeDescription as UflAttributeDescription, UflType as UflType
from umlfri2.ufl.types.basic.integer import UflIntegerType as UflIntegerType

from typing import Optional
from umlfri2.types.color import Color

class UflColorType(UflType):
    def __init__(self, default: Optional[Color] = ...) -> None: ...
    @property
    def default(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator: None) -> Color: ...
    def parse(self, value: str) -> Color: ...
    @property
    def is_immutable(self) -> bool: ...
    def is_valid_value(self, value: Color) -> bool: ...
    def is_default_value(self, value: Color) -> bool: ...
