from umlfri2.types.color import Color as Color, Colors as Colors
from umlfri2.ufl.types.base.type import UflAttributeDescription as UflAttributeDescription, UflType as UflType
from umlfri2.ufl.types.basic.integer import UflIntegerType as UflIntegerType

class UflColorType(UflType):
    def __init__(self, default=None) -> None: ...
    @property
    def default(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator): ...
    def parse(self, value): ...
    @property
    def is_immutable(self): ...
    def is_valid_value(self, value): ...
    def is_default_value(self, value): ...
