from umlfri2.types.font import Font as Font, FontStyle as FontStyle, Fonts as Fonts
from umlfri2.ufl.types.base.type import UflAttributeDescription as UflAttributeDescription, UflType as UflType
from umlfri2.ufl.types.basic.integer import UflIntegerType as UflIntegerType
from umlfri2.ufl.types.basic.string import UflStringType as UflStringType
from umlfri2.ufl.types.enum.typedenum import UflTypedEnumType as UflTypedEnumType

from typing import Optional
from umlfri2.types.font import Font

class UflFontType(UflType):
    def __init__(self, default: Optional[Font] = ...) -> None: ...
    @property
    def default(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator: None) -> Font: ...
    def parse(self, value: str) -> Font: ...
    @property
    def is_immutable(self) -> bool: ...
    def is_valid_value(self, value: Font) -> bool: ...
    def is_default_value(self, value: Font) -> bool: ...
