from umlfri2.types.image import Image as Image
from umlfri2.ufl.types.base.type import UflType as UflType

class UflImageType(UflType):
    def __init__(self, default=None) -> None: ...
    @property
    def default(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator): ...
    def parse(self, value) -> None: ...
    @property
    def is_immutable(self): ...
    def is_valid_value(self, value): ...
    def is_default_value(self, value): ...
