from PyQt5.QtWidgets import QTabBar, QTabWidget
from _typeshed import Incomplete

class ValidateTabChangeEvent:
    def __init__(self, tab_index) -> None: ...
    @property
    def is_valid(self): ...
    @property
    def tab_index(self): ...
    def invalidate(self) -> None: ...

class ValidatingTabBar(QTabBar):
    validate_tab_change: Incomplete
    def mousePressEvent(self, event): ...
    def wheelEvent(self, event) -> None: ...
    def change_tab_in_direction(self, to_right, continue_from_end: bool = False) -> None: ...

class ValidatingTabWidget(QTabWidget):
    def __init__(self, parent=None) -> None: ...
    def keyPressEvent(self, event) -> None: ...
