from umlfri2.application.addon.local.addon import AddOn
from umlfri2.application.application import Application


class AddOnAction:
    def __init__(self, application: Application, id: str) -> None: ...
    def _set_addon(self, addon: AddOn) -> None: ...
    @property
    def id(self) -> str: ...
    def trigger(self) -> None: ...
