from _typeshed import Incomplete
from umlfri2.types.enums import FontStyle as FontStyle

class Font:
    def __init__(self, family, size, style=()) -> None: ...
    @property
    def size(self): ...
    @property
    def family(self): ...
    @property
    def style(self): ...
    def change_family(self, new_family): ...
    def change_size(self, new_size): ...
    def change(self, style, value): ...
    def __eq__(self, other): ...
    @staticmethod
    def get_font(description): ...

class Fonts:
    default: Incomplete
    @staticmethod
    def exists(name): ...
    @staticmethod
    def get(name): ...
