from _typeshed import Incomplete

class Proportion:
    def __init__(self, antecedent, consequent) -> None: ...
    @property
    def antecedent(self): ...
    @property
    def consequent(self): ...
    @property
    def ratio(self): ...
    @property
    def fraction(self): ...
    @property
    def percentage(self): ...
    @property
    def value(self): ...
    @staticmethod
    def from_ratio(antecedent, consequent): ...
    @staticmethod
    def from_fraction(numerator, denominator): ...
    @staticmethod
    def from_percentage(percentage): ...
    @staticmethod
    def from_value(value): ...
    @staticmethod
    def from_string(proportion): ...

WHOLE_PROPORTION: Incomplete
EMPTY_PROPORTION: Incomplete
