from _typeshed import Incomplete

class MaybeType:
    def __new__(cls, *args, **kwargs) -> None: ...
    def __and__(self, other): ...
    def __rand__(self, other): ...
    def __or__(self, other): ...
    def __ror__(self, other): ...

Maybe: Incomplete
