from .compilationerror import ValueCompilationError as ValueCompilationError
from .valueprovider import ValueProvider as ValueProvider

class ConstantValueProvider(ValueProvider):
    def __init__(self, value, source=None) -> None: ...
    def compile(self, type_context, expected_type) -> None: ...
    def get_type(self): ...
    def get_source(self): ...
    def __call__(self, context): ...
