from ...expressions import CompiledUflExpression as CompiledUflExpression
from .compilationerror import ValueCompilationError as ValueCompilationError
from .valueprovider import ValueProvider as ValueProvider

class DynamicValueProvider(ValueProvider):
    def __init__(self, expression, source=None) -> None: ...
    def compile(self, type_context, expected_type) -> None: ...
    def get_source(self): ...
    def get_type(self): ...
    def __call__(self, context): ...
