class ValueProvider:
    def compile(self, type_context, expected_type) -> None: ...
    def get_type(self) -> None: ...
    def get_source(self) -> None: ...
    def __call__(self, context) -> None: ...
