from ..base.component import Component as Component

class GraphicalObject:
    def assign_bounds(self, bounds) -> None: ...
    def draw(self, canvas, shadow) -> None: ...

class GraphicalComponent(Component):
    def create_graphical_object(self, context, ruler, size) -> None: ...
