from typing import (
    Iterator,
    Optional,
)
from umlfri2.application.addon.local.actions.starter import AddOnStarter
from umlfri2.application.addon.local.actions.stopper import AddOnStopper
from umlfri2.application.addon.local.addon import AddOn
from umlfri2.application.addon.online.version import OnlineAddOnVersion
from umlfri2.application.application import Application
from umlfri2.datalayer.storages.zip import ZipStorage


class AddOnManager:
    def __init__(self, application: Application) -> None: ...
    def __iter__(self) -> Iterator[AddOn]: ...
    def get_addon(self, identifier: str) -> Optional[AddOn]: ...
    def install_addon(
        self,
        storage: ZipStorage,
        online_addon_version: OnlineAddOnVersion
    ) -> AddOn: ...
    def load_addons(self) -> None: ...
    def start_all(self) -> AddOnStarter: ...
    def stop_all(self) -> AddOnStopper: ...
    def uninstall_addon(self, addon: AddOn) -> None: ...
