from typing import Iterator
from umlfri2.application.events.model.projectchanged import ProjectChangedEvent
from umlfri2.model.project import Project
from umlfri2.qtgui.rendering.qtruler import QTRuler


class ChangeProjectNameCommand:
    def __init__(self, project: Project, name: str) -> None: ...
    def _do(self, ruler: QTRuler) -> None: ...
    def _redo(self, ruler: QTRuler) -> None: ...
    def get_updates(self) -> Iterator[ProjectChangedEvent]: ...
