from typing import Iterator
from umlfri2.application.events.model.diagramdeleted import DiagramDeletedEvent
from umlfri2.model.diagram import Diagram
from umlfri2.qtgui.rendering.qtruler import QTRuler


class DeleteDiagramCommand:
    def __init__(self, diagram: Diagram) -> None: ...
    def _do(self, ruler: QTRuler) -> None: ...
    def _redo(self, ruler: QTRuler) -> None: ...
    def _undo(self, ruler: QTRuler) -> None: ...
    def get_updates(self) -> Iterator[DiagramDeletedEvent]: ...
