from ..base import Event as Event

class AddOnStateChangedEvent(Event):
    def __init__(self, addon, state) -> None: ...
    @property
    def addon(self): ...
    @property
    def addon_state(self): ...
