from umlfri2.datalayer.storages import ZipStorage as ZipStorage

class OnlineAddonVersionDownloader:
    def __init__(self, version) -> None: ...
    @property
    def addon_version(self): ...
    @property
    def downloaded(self): ...
    @property
    def storage(self): ...
