from .downloader import OnlineAddonVersionDownloader as OnlineAddonVersionDownloader

class OnlineAddOnUpdater:
    def __init__(self, local_manager, *addon_versions) -> None: ...
    def combine_with(self, other): ...
    @property
    def finished(self): ...
    @property
    def has_error(self): ...
    def do(self) -> None: ...
