from PyQt5.QtWidgets import QWidget
from umlfri2.application import Application as Application
from umlfri2.constants.languages import AVAILABLE_LANGUAGES as AVAILABLE_LANGUAGES

class SettingsDialogGeneral(QWidget):
    def __init__(self, dialog) -> None: ...
    @staticmethod
    def get_name(): ...
    def apply_settings(self) -> None: ...
    def reload_texts(self) -> None: ...
