from .column import UflDialogColumn as UflDialogColumn

class UflDialogEnumColumn(UflDialogColumn):
    def __init__(self, attr) -> None: ...
    def get_value(self, object): ...
    def translate(self, translation) -> None: ...
