from .checkdata import check_any as check_any

class ConnectionTemplate:
    def __init__(self, type, data, source_id, destination_id, id=None) -> None: ...
    @property
    def id(self): ...
    @property
    def type(self): ...
    @property
    def data(self): ...
    @property
    def source_id(self): ...
    @property
    def destination_id(self): ...
