from _typeshed import Incomplete
from collections.abc import Generator

class ProjectTemplate:
    def __init__(self, id, elements, connections, diagrams) -> None: ...
    @property
    def id(self): ...
    @property
    def icon(self): ...
    @property
    def addon(self): ...
    @property
    def metamodel(self): ...
    @property
    def elements(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def connections(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def diagrams(self) -> Generator[Incomplete, Incomplete]: ...
    def compile(self) -> None: ...
