from ..base import Event as Event
from _typeshed import Incomplete
from collections.abc import Generator

class ConnectionHiddenEvent(Event):
    def __init__(self, connection) -> None: ...
    @property
    def connection(self): ...
    def get_chained(self) -> Generator[Incomplete]: ...
    def get_opposite(self): ...
