from ..base import Event as Event
from _typeshed import Incomplete
from collections.abc import Generator

class ElementHiddenEvent(Event):
    def __init__(self, element) -> None: ...
    @property
    def element(self): ...
    def get_chained(self) -> Generator[Incomplete]: ...
    def get_opposite(self): ...
