from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.events.base import Event as Event

class ElementResizedMovedEvent(Event):
    def __init__(self, element) -> None: ...
    @property
    def element(self): ...
    def get_chained(self) -> Generator[Incomplete]: ...
    def get_opposite(self): ...
