from ..base import Event as Event

class SelectionChangedEvent(Event):
    def __init__(self, diagram, selection) -> None: ...
    @property
    def diagram(self): ...
    @property
    def selection(self): ...
    def get_opposite(self): ...
