from .connectionvisualcomponent import ConnectionVisualComponent as ConnectionVisualComponent, ConnectionVisualObject as ConnectionVisualObject

class ConnectionVisualContainerObject(ConnectionVisualObject):
    def __init__(self, children) -> None: ...
    def assign_points(self, points) -> None: ...
    def draw(self, canvas) -> None: ...

class ConnectionVisualContainerComponent(ConnectionVisualComponent):
    def compile(self, type_context) -> None: ...
