from .downloader import OnlineAddonVersionDownloader as OnlineAddonVersionDownloader

class OnlineAddOnInstaller:
    def __init__(self, local_manager, addon_version) -> None: ...
    @property
    def finished(self): ...
    @property
    def has_error(self): ...
    def do(self) -> None: ...
