from ..base import Event as Event
from umlfri2.model.diagram import Diagram


class DiagramChangedEvent(Event):
    def __init__(self, diagram: Diagram) -> None: ...
    @property
    def diagram(self): ...
    def get_opposite(self): ...
