from PyQt5.QtWidgets import QDialog
from umlfri2.application import Application as Application

class ExportDialog(QDialog):
    def __init__(self, main_window) -> None: ...
    def done(self, dialog_code) -> None: ...
    @property
    def zoom(self): ...
    @property
    def padding(self): ...
    @property
    def transparent(self): ...
