from .qtpaintercanvas import QTPainterCanvas as QTPainterCanvas
from .qtruler import QTRuler as QTRuler
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.model import Diagram as Diagram
from umlfri2.types.geometry import Vector as Vector

class ImageExport:
    def __init__(self, diagram_or_selection, zoom, padding, transparent) -> None: ...
    def supported_formats(self) -> Generator[Incomplete]: ...
    @property
    def default_format(self): ...
    def export(self, file, format) -> None: ...
    def export_to_clipboard(self) -> None: ...
    def get_size(self, bounds): ...
