from umlfri2.qtgui.appdialogs.settings.dialog import SettingsDialog


class SettingsDialogGeneral:
    def __init__(self, dialog: SettingsDialog) -> None: ...
    def apply_settings(self) -> None: ...
    @staticmethod
    def get_name() -> str: ...
    def reload_texts(self) -> None: ...
