from typing import Union
from umlfri2.metamodel.translation.translation import Translation
from umlfri2.ufl.objects.mutable.object import UflMutableObject
from umlfri2.ufl.types.structured.object import UflObjectAttribute

class UflDialogColumn:
    def __init__(self, attr: UflObjectAttribute) -> None: ...
    @property
    def title(self) -> str: ...
    def get_value(self, object) -> None: ...
    def translate(self, translation: Translation) -> None: ...
