from typing import (
    Callable,
    Optional,
)


class ModelTemporaryDataCache:
    def __init__(self, callback: Optional[Callable]) -> None: ...
    def depend_on(self, cache: ModelTemporaryDataCache) -> None: ...
    def ensure_valid(self, **kwargs) -> None: ...
    def invalidate(self) -> None: ...
    def refresh(self, **kwargs) -> None: ...
