from typing import (
    Any,
    Iterator,
    Optional,
)
from umlfri2.metamodel.elementtype import ElementType
from umlfri2.metamodel.metamodel import Metamodel
from umlfri2.model.element.elementobject import ElementObject
from umlfri2.ufl.dialog.dialog import UflDialog
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.patch.object import UflObjectPatch
from uuid import UUID


class Project:
    def __init__(
        self,
        metamodel: Metamodel,
        name: Optional[str] = ...,
        save_id: Optional[UUID] = ...
    ) -> None: ...
    def apply_config_patch(self, patch: UflObjectPatch) -> None: ...
    @property
    def children(self) -> Iterator[ElementObject]: ...
    @property
    def config(self) -> UflObject: ...
    def create_child_element(
        self,
        type: ElementType,
        save_id: Optional[UUID] = ...
    ) -> ElementObject: ...
    def create_config_dialog(self) -> UflDialog: ...
    def get_all_elements(self) -> Iterator[Any]: ...
    def get_display_name(self) -> str: ...
    def invalidate_all_caches(self) -> None: ...
    @property
    def metamodel(self) -> Metamodel: ...
    @property
    def parent(self) -> None: ...
    @property
    def save_id(self) -> UUID: ...
