from typing import (
    Iterator,
    Optional,
)
from umlfri2.model.diagram import Diagram
from umlfri2.model.element.elementobject import ElementObject
from umlfri2.model.project import Project
from uuid import UUID


class Solution:
    def __init__(
        self,
        project: Optional[Project] = ...,
        save_id: Optional[UUID] = ...
    ) -> None: ...
    def add_project(self, project: Project) -> None: ...
    @property
    def children(self) -> Iterator[Project]: ...
    def get_all_diagrams(self) -> Iterator[Diagram]: ...
    def get_all_elements(self) -> Iterator[ElementObject]: ...
    def invalidate_all_caches(self) -> None: ...
    @property
    def save_id(self) -> UUID: ...
