class PipeChannel:
    def __init__(self) -> None: ...
    @property
    def child_reader_handle(self) -> int: ...
    @property
    def child_writer_handle(self) -> int: ...
    def close_child_descriptors(self) -> None: ...
