from .widget import UflDialogWidget as UflDialogWidget
from _typeshed import Incomplete
from collections.abc import Generator

class UflDialogMultiSelectWidget(UflDialogWidget):
    def __init__(self, tab, attr, type) -> None: ...
    @property
    def value(self): ...
    def associate(self, ufl_object) -> None: ...
    def associate_default(self) -> None: ...
    @property
    def changed(self): ...
    def finish_after_save(self) -> None: ...
    def discard(self) -> None: ...
    @property
    def possibilities(self) -> Generator[Incomplete]: ...
    def check(self, index) -> None: ...
    def uncheck(self, index) -> None: ...
    def translate(self, translation) -> None: ...
