from .widget import UflDialogWidget as UflDialogWidget

class UflDialogNullableWidget(UflDialogWidget):
    def __init__(self, tab, attr, type, inner_widget) -> None: ...
    @property
    def inner_widget(self): ...
    @property
    def value(self): ...
    @property
    def is_null(self): ...
    @is_null.setter
    def is_null(self, value) -> None: ...
    def associate(self, ufl_object) -> None: ...
    def associate_default(self) -> None: ...
    @property
    def changed(self): ...
    def finish_after_save(self) -> None: ...
    def discard(self) -> None: ...
