from .channel import Channel as Channel

class FileChannel(Channel):
    def __init__(self, input, output) -> None: ...
    def write(self, data) -> None: ...
    def read(self): ...
    def close(self) -> None: ...
    @property
    def closed(self): ...
