from .actions import SelectManyAction as SelectManyAction
from .drawingareacursor import DrawingAreaCursor as DrawingAreaCursor
from .selection import Selection as Selection
from .snapping import Snapping as Snapping
from _typeshed import Incomplete
from umlfri2.application.events.application import ZoomChangedEvent as ZoomChangedEvent
from umlfri2.application.snippet import SnippetBuilder as SnippetBuilder
from umlfri2.types.color import Colors as Colors
from umlfri2.types.enums import LineStyle as LineStyle
from umlfri2.types.geometry import Point as Point, Vector as Vector
from typing import (
    Any,
    List,
    Optional,
)
from umlfri2.application.application import Application
from umlfri2.application.drawingarea.actions.action import ActionMenuItem
from umlfri2.application.drawingarea.drawingareacursor import DrawingAreaCursor
from umlfri2.application.drawingarea.selection import Selection
from umlfri2.model.diagram import Diagram
from umlfri2.qtgui.rendering.qtpaintercanvas import QTPainterCanvas
from umlfri2.qtgui.rendering.qtruler import QTRuler
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.size import Size


class DrawingArea:
    SELECTION_RECTANGLE_FILL: Incomplete
    SELECTION_RECTANGLE_BORDER: Incomplete
    SELECTION_RECTANGLE_WIDTH: int
    SNAPPING_INDICATOR_SIZE: int
    SNAPPING_INDICATOR_WIDTH: int
    SNAPPING_INDICATOR_COLOR: Incomplete
    SNAPPING_INDICATOR_STYLE: Incomplete
    ZOOM_FACTOR: float
    ZOOM_MIN: int
    ZOOM_MAX: int
    def __init__(
        self,
        application: Application,
        diagram: Diagram
    ) -> None: ...
    @property
    def diagram(self) -> Diagram: ...
    @property
    def enable_snapping(self): ...
    @enable_snapping.setter
    def enable_snapping(self, value) -> None: ...
    @property
    def cursor(self) -> DrawingAreaCursor: ...
    @property
    def selection(self) -> Selection: ...
    def draw(self, canvas: QTPainterCanvas) -> None: ...
    def mouse_down(self, point: Point, control_pressed: bool, shift_pressed: bool) -> None: ...
    def mouse_move(self, point: Point, control_pressed: bool, shift_pressed: bool) -> None: ...
    def mouse_up(self, point: Point, control_pressed: bool, shift_pressed: bool) -> None: ...
    @property
    def menu_to_show(self) -> Optional[List[ActionMenuItem]]: ...
    def execute_menu_action(
        self,
        menu_item: ActionMenuItem,
        point: Point,
        control_pressed: bool,
        shift_pressed: bool
    ) -> None: ...
    def get_object_at(self, point): ...
    def ensure_selection_at(self, point: Point) -> None: ...
    def reset_action(self) -> None: ...
    def set_action(self, action: Any) -> None: ...
    @property
    def current_action(self) -> None: ...
    @property
    def action_active(self) -> bool: ...
    def get_size(self, ruler: QTRuler) -> Size: ...
    @property
    def can_zoom_in(self) -> bool: ...
    def zoom_in(self) -> None: ...
    @property
    def can_zoom_out(self) -> bool: ...
    def zoom_out(self) -> None: ...
    @property
    def can_zoom_original(self) -> bool: ...
    def zoom_original(self) -> None: ...
    @property
    def can_copy_snippet(self) -> bool: ...
    def copy_snippet(self) -> None: ...
    @property
    def can_paste_snippet(self) -> bool: ...
    @property
    def can_paste_snippet_duplicate(self) -> bool: ...
