from .actions import AddConnectionPointAction as AddConnectionPointAction, AddUntypedConnectionAction as AddUntypedConnectionAction, MoveConnectionLabelAction as MoveConnectionLabelAction, MoveConnectionPointAction as MoveConnectionPointAction, MoveSelectionAction as MoveSelectionAction, RemoveConnectionPointAction as RemoveConnectionPointAction, ResizeElementAction as ResizeElementAction
from .selectionpointposition import SelectionPointPosition as SelectionPointPosition
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.events.diagram import ConnectionHiddenEvent as ConnectionHiddenEvent, ElementHiddenEvent as ElementHiddenEvent, SelectionChangedEvent as SelectionChangedEvent
from umlfri2.model.connection import ConnectionVisual as ConnectionVisual
from umlfri2.model.element import ElementVisual as ElementVisual
from umlfri2.types.color import Colors as Colors
from umlfri2.types.enums import LineStyle as LineStyle
from umlfri2.types.geometry import Line as Line, PathBuilder as PathBuilder, Point as Point, Rectangle as Rectangle, Size as Size, Transformation as Transformation, Vector as Vector

class Selection:
    SELECTION_COLOR: Incomplete
    SELECTION_SIZE: int
    SELECTION_POINT_COLOR: Incomplete
    SELECTION_POINT_SIZE: int
    LABEL_LINE_MINIMAL_DISTANCE: int
    ICON_COLOR: Incomplete
    ICON_COLOR_BACKGROUND: Incomplete
    CONNECTION_ICON_SHIFT: Incomplete
    CONNECTION_ICON: Incomplete
    CONNECTION_ICON_BOUNDS: Incomplete
    def __init__(self, application, diagram) -> None: ...
    @property
    def selected_visuals(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def selected_elements(self) -> Generator[Incomplete]: ...
    @property
    def selected_connection(self): ...
    @property
    def selected_diagram(self): ...
    @property
    def diagram(self): ...
    def select(self, visual) -> None: ...
    def select_all(self) -> None: ...
    def deselect_all(self) -> None: ...
    def add_to_selection(self, visual) -> None: ...
    def remove_from_selection(self, visual) -> None: ...
    def toggle_select(self, visual) -> None: ...
    def select_at(self, point) -> None: ...
    def select_in_area(self, area) -> None: ...
    def draw_for(self, canvas, visual) -> None: ...
    def draw_selected(self, canvas, selection: bool = False, transparent: bool = False) -> None: ...
    def get_action_at(self, position, shift_pressed): ...
    def is_selection_at(self, position): ...
    def is_selected(self, visual): ...
    def get_bounds(self, include_connections: bool = True): ...
    @property
    def is_diagram_selected(self): ...
    @property
    def is_connection_selected(self): ...
    @property
    def is_element_selected(self): ...
    @property
    def size(self): ...
    def get_lonely_selected_visual(self): ...
