class Color:
    def __eq__(self, other: Color) -> bool: ...
    def __init__(self, argb: int) -> None: ...
    def __str__(self) -> str: ...
    def add_alpha(self, alpha: int) -> Color: ...
    @property
    def argb(self) -> int: ...
    @staticmethod
    def from_string(color: str) -> Color: ...
    def to_rgb_str(self) -> str: ...


class Colors:
    @staticmethod
    def exists(name: str) -> bool: ...
    @staticmethod
    def get(name: str) -> Color: ...
