from typing import (
    Set,
    Tuple,
    Union,
)
from umlfri2.types.enums.fontstyle import FontStyle


class Font:
    def __eq__(self, other: Font) -> bool: ...
    def __init__(
        self,
        family: str,
        size: int,
        style: Union[Set[FontStyle], Tuple[()], frozenset] = ...
    ) -> None: ...
    def __str__(self) -> str: ...
    def change(self, style: FontStyle, value: bool) -> Font: ...
    def change_family(self, new_family: str) -> Font: ...
    @property
    def family(self) -> str: ...
    @staticmethod
    def get_font(description: str) -> Font: ...
    @property
    def size(self) -> int: ...
    @property
    def style(self) -> frozenset: ...
