from io import BufferedReader
from umlfri2.datalayer.storages.directory import DirectoryStorage


class Image:
    def __init__(self, storage: DirectoryStorage, path: str) -> None: ...
    def load(self) -> BufferedReader: ...
    @property
    def path(self) -> str: ...
    @property
    def storage(self) -> DirectoryStorage: ...
