class Proportion:
    def __init__(self, antecedent: int, consequent: int) -> None: ...
    @staticmethod
    def from_percentage(percentage: float) -> Proportion: ...
    @staticmethod
    def from_string(proportion: str) -> Proportion: ...
    @staticmethod
    def from_value(value: float) -> Proportion: ...
    @property
    def value(self) -> float: ...
