class Version:
    def __gt__(self, other: Version) -> bool: ...
    def __init__(self, value: str) -> None: ...
    def __le__(self, other: Version) -> bool: ...
    def __lt__(self, other: Version) -> bool: ...
    def __ne__(self, other: Version) -> bool: ...
    def __str__(self) -> str: ...
    def is_compatible_with(self, current: Version) -> bool: ...
    @property
    def major_minor_string(self) -> str: ...
