from ..valueproviders import DefaultValueProvider as DefaultValueProvider
from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from _typeshed import Incomplete
from umlfri2.types.enums import HorizontalAlignment as HorizontalAlignment, VerticalAlignment as VerticalAlignment
from umlfri2.types.geometry import Rectangle as Rectangle
from umlfri2.types.threestate import Maybe as Maybe
from umlfri2.ufl.types.enum import UflTypedEnumType as UflTypedEnumType
from umlfri2.ufl.types.structured import UflNullableType as UflNullableType

class AlignObject(VisualObject):
    def __init__(self, child, horizontal, vertical) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class AlignComponent(VisualComponent):
    ATTRIBUTES: Incomplete
    def __init__(self, children, horizontal=None, vertical=None) -> None: ...
    def compile(self, type_context) -> None: ...
