from ..valueproviders import DefaultValueProvider as DefaultValueProvider
from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from _typeshed import Incomplete
from umlfri2.types.geometry import Rectangle as Rectangle, Size as Size
from umlfri2.types.threestate import Maybe as Maybe
from umlfri2.ufl.types.complex import UflColorType as UflColorType
from umlfri2.ufl.types.structured import UflNullableType as UflNullableType

class EllipseObject(VisualObject):
    def __init__(self, child, fill, border) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class EllipseComponent(VisualComponent):
    ATTRIBUTES: Incomplete
    def __init__(self, children, fill=None, border=None) -> None: ...
    def compile(self, type_context) -> None: ...
