from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from umlfri2.types.geometry import Size as Size

class EmptyObject(VisualObject):
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class EmptyComponent(VisualComponent):
    HAS_CHILDREN: bool
    def __init__(self) -> None: ...
