from ..base.componenttype import ComponentType as ComponentType
from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from _typeshed import Incomplete
from umlfri2.types.geometry import Size as Size
from umlfri2.ufl.types.basic import UflDecimalType as UflDecimalType

class GraphicsObject(VisualObject):
    def __init__(self, children) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class GraphicsComponent(VisualComponent):
    ATTRIBUTES: Incomplete
    CHILDREN_TYPE: Incomplete
    def __init__(self, children, width, height) -> None: ...
    def compile(self, type_context) -> None: ...
