from ..valueproviders import DefaultValueProvider as DefaultValueProvider
from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from _typeshed import Incomplete
from umlfri2.types.geometry import PathBuilder as PathBuilder, Rectangle as Rectangle, Size as Size, Transformation as Transformation
from umlfri2.types.threestate import Maybe as Maybe
from umlfri2.ufl.types.complex import UflColorType as UflColorType
from umlfri2.ufl.types.enum import UflDefinedEnumType as UflDefinedEnumType
from umlfri2.ufl.types.structured import UflNullableType as UflNullableType

class CornerDefinition:
    def __init__(self, id, path, ornament, center, corner) -> None: ...
    @property
    def id(self): ...
    @property
    def path(self): ...
    @property
    def ornament(self): ...

class SideDefinition:
    def __init__(self, id, path, ornament, center, size, side) -> None: ...
    @property
    def id(self): ...
    @property
    def path(self): ...
    @property
    def ornament(self): ...
    @property
    def size(self): ...

class RoundedRectangleObject(VisualObject):
    def __init__(self, child, fill, border, corners, sides) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class RectangleObject(VisualObject):
    def __init__(self, child, fill, border) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class RectangleComponent(VisualComponent):
    ATTRIBUTES: Incomplete
    def __init__(self, children, fill=None, border=None, topleft=None, topright=None, bottomleft=None, bottomright=None, left=None, right=None, top=None, bottom=None) -> None: ...
    def compile(self, type_context) -> None: ...
