from ..base.componenttype import ComponentType as ComponentType
from ..text import TextContainerComponent as TextContainerComponent, TextDataComponent as TextDataComponent
from ..valueproviders import DefaultValueProvider as DefaultValueProvider
from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from _typeshed import Incomplete
from umlfri2.types.color import Colors as Colors
from umlfri2.types.font import Fonts as Fonts
from umlfri2.ufl.types.basic import UflStringType as UflStringType
from umlfri2.ufl.types.complex import UflColorType as UflColorType, UflFontType as UflFontType

class TextBoxObject(VisualObject):
    def __init__(self, size, text, color, font) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class TextBoxComponent(VisualComponent):
    ATTRIBUTES: Incomplete
    CHILDREN_TYPE: Incomplete
    def __init__(self, children, text=None, color=None, font=None) -> None: ...
    def compile(self, type_context) -> None: ...
