from ..base.component import Component as Component
from .empty import EmptyObject as EmptyObject
from umlfri2.types.geometry import Point as Point, Rectangle as Rectangle
from umlfri2.types.threestate import Maybe as Maybe

class VisualObjectContainer:
    def __init__(self, object) -> None: ...
    @property
    def size(self): ...
    @property
    def position(self): ...
    def resize(self, new_size) -> None: ...
    def move(self, new_position) -> None: ...
    def get_minimal_size(self): ...
    def is_resizable(self): ...
    def draw(self, canvas) -> None: ...

class VisualContainerComponent(Component):
    def __init__(self, children) -> None: ...
    def create_visual_object(self, context, ruler): ...
    def compile(self, type_context) -> None: ...
