from umlfri2.ufl.components.text.textcontainer import TextContainerComponent

class UniqueValueGenerator:
    def get_text(self, template: TextContainerComponent) -> str: ...
    def get_parent_name(self) -> None: ...
    def has_value(self, value) -> None: ...
    def for_name(self, name) -> None: ...
