from .widget import UflDialogWidget as UflDialogWidget

class UflDialogChildWidget(UflDialogWidget):
    def __init__(self, tab, attr, type, dialog) -> None: ...
    @property
    def value(self): ...
    @property
    def dialog(self): ...
    def associate(self, ufl_object) -> None: ...
    def associate_default(self) -> None: ...
    def translate(self, translation) -> None: ...
    @property
    def changed(self): ...
    def finish_after_save(self) -> None: ...
    def discard(self) -> None: ...
