from .valued import UflDialogValuedWidget as UflDialogValuedWidget
from _typeshed import Incomplete
from collections.abc import Generator

class UflDialogSelectWidget(UflDialogValuedWidget):
    def __init__(self, tab, attr, type) -> None: ...
    @property
    def possibilities(self) -> Generator[Incomplete]: ...
    @property
    def current_index(self): ...
    value: Incomplete
    @current_index.setter
    def current_index(self, index) -> None: ...
    def translate(self, translation) -> None: ...
