from .widget import UflDialogWidget as UflDialogWidget

class UflDialogValuedWidget(UflDialogWidget):
    def __init__(self, tab, attr, type) -> None: ...
    @property
    def value(self): ...
    @value.setter
    def value(self, value) -> None: ...
    def associate(self, ufl_object) -> None: ...
    def associate_default(self) -> None: ...
    @property
    def changed(self): ...
    def finish_after_save(self) -> None: ...
    def discard(self) -> None: ...
