class UflDialogWidget:
    def __init__(self, tab, attr, type) -> None: ...
    @property
    def tab(self): ...
    @property
    def value(self) -> None: ...
    @property
    def attribute(self): ...
    @property
    def type(self): ...
    @property
    def id(self): ...
    @property
    def label(self): ...
    def associate(self, ufl_object) -> None: ...
    def associate_default(self) -> None: ...
    def translate(self, translation) -> None: ...
    @property
    def changed(self) -> None: ...
    def finish_after_save(self) -> None: ...
    def discard(self) -> None: ...
