from .canvaswidget import CanvasWidget as CanvasWidget
from PyQt5.QtWidgets import QScrollArea

class ScrolledCanvasWidget(QScrollArea):
    def __init__(self, main_window, drawing_area) -> None: ...
    def wheelEvent(self, event) -> None: ...
    @property
    def diagram(self): ...
