from .node import UflNode as UflNode

class UflBinaryNode(UflNode):
    def __init__(self, operand1, operator, operand2, type=None) -> None: ...
    @property
    def operand1(self): ...
    @property
    def operand2(self): ...
    @property
    def operator(self): ...
    def accept(self, visitor): ...
