from .node import UflNode as UflNode

class UflUnaryNode(UflNode):
    def __init__(self, operator, operand, type=None) -> None: ...
    @property
    def operator(self): ...
    @property
    def operand(self): ...
    def accept(self, visitor): ...
