from .node import UflNode as UflNode

class UflVariableDefinitionNode(UflNode):
    def __init__(self, name, type=None) -> None: ...
    @property
    def name(self): ...
    def accept(self, visitor): ...
