from .storage import Storage as Storage, StorageReference as StorageReference
from _typeshed import Incomplete
from collections.abc import Generator

class DirectoryStorageReference(StorageReference):
    def __init__(self, path, mode) -> None: ...
    @property
    def name(self): ...
    @property
    def still_valid(self): ...
    def open(self, mode=None): ...

class DirectoryStorage(Storage):
    @staticmethod
    def read_storage(path): ...
    @staticmethod
    def new_storage(path): ...
    def __init__(self, path, mode) -> None: ...
    @property
    def path(self): ...
    def list(self, path=None): ...
    def open(self, path, mode: str = 'r'): ...
    def store_string(self, path, data) -> None: ...
    def read_string(self, path): ...
    def exists(self, path): ...
    def create_substorage(self, path): ...
    def make_dir(self, path): ...
    def get_all_files(self) -> Generator[Incomplete]: ...
    def copy_from(self, storage) -> None: ...
    def remember_reference(self): ...
    def remove_storage(self) -> None: ...
    def close(self) -> None: ...
