import types

class StorageReference:
    @property
    def name(self) -> None: ...
    @property
    def still_valid(self) -> None: ...
    def open(self, mode=None) -> None: ...

class UnknownStorageException(Exception): ...

class Storage:
    @staticmethod
    def read_storage(path): ...
    def list(self, path=None) -> None: ...
    def open(self, path, mode: str = 'r') -> None: ...
    def store_string(self, path, data) -> None: ...
    def read_string(self, path) -> None: ...
    def exists(self, path) -> None: ...
    def create_substorage(self, path) -> None: ...
    def make_dir(self, path) -> None: ...
    def get_all_files(self) -> None: ...
    def copy_from(self, storage) -> None: ...
    def remember_reference(self) -> None: ...
    def remove_storage(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
