from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.model.cache import ModelTemporaryDataCache as ModelTemporaryDataCache
from umlfri2.ufl.dialog import UflDialog as UflDialog, UflDialogOptions as UflDialogOptions

class ConnectionObject:
    def __init__(self, type, source, destination, save_id=None) -> None: ...
    def add_visual(self, visual) -> None: ...
    def remove_visual(self, visual) -> None: ...
    @property
    def visuals(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def cache(self): ...
    @property
    def type(self): ...
    @property
    def data(self): ...
    @property
    def source(self): ...
    @property
    def destination(self): ...
    @property
    def project(self): ...
    def reverse(self) -> None: ...
    def get_other_end(self, element): ...
    def is_connected_with(self, element): ...
    @property
    def save_id(self): ...
    def create_appearance_object(self, ruler): ...
    def create_label_object(self, id, ruler): ...
    def apply_ufl_patch(self, patch) -> None: ...
    @property
    def has_ufl_dialog(self): ...
    def create_ufl_dialog(self, options=...): ...
