from ..cache import ModelTemporaryDataCache as ModelTemporaryDataCache
from umlfri2.types.geometry import Line as Line, Point as Point, Rectangle as Rectangle, Vector as Vector

class ConnectionLabel:
    def __init__(self, connection, id) -> None: ...
    @property
    def cache(self): ...
    @property
    def connection(self): ...
    @property
    def id(self): ...
    @property
    def line_index(self): ...
    def get_position(self, ruler): ...
    def move(self, ruler, new_position) -> None: ...
    def get_bounds(self, ruler): ...
    def is_at_position(self, ruler, position): ...
    def get_nearest_point(self, ruler): ...
    def draw(self, canvas) -> None: ...
