import types
from .storage import Storage as Storage, StorageReference as StorageReference
from _typeshed import Incomplete
from collections.abc import Generator
from io import BytesIO

class ZipStorageReference(StorageReference):
    def __init__(self, zip_path, path, mode) -> None: ...
    @property
    def name(self): ...
    @property
    def still_valid(self): ...
    def open(self, mode=None): ...

class ZipFileWriter(BytesIO):
    def __init__(self, zip_file, file_path) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: types.TracebackType | None) -> None: ...
    def close(self) -> None: ...

class ZipStorage(Storage):
    @staticmethod
    def read_storage(path): ...
    @staticmethod
    def new_storage(path): ...
    @staticmethod
    def read_from_memory(bytes): ...
    def __init__(self, zip_path, zip_file, path, mode) -> None: ...
    def list(self, path: str = '/') -> Generator[Incomplete]: ...
    def open(self, path, mode: str = 'r'): ...
    def store_string(self, path, data) -> None: ...
    def read_string(self, path): ...
    def exists(self, path): ...
    def create_substorage(self, path): ...
    def make_dir(self, path): ...
    def get_all_files(self) -> Generator[Incomplete]: ...
    def copy_from(self, storage) -> None: ...
    def remember_reference(self): ...
    def remove_storage(self) -> None: ...
    def close(self) -> None: ...
