from ..projecttree import ProjectMimeData as ProjectMimeData
from ..properties import PropertiesDialog as PropertiesDialog
from ..rendering import QTPainterCanvas as QTPainterCanvas
from .actionmenu import ActionMenu as ActionMenu
from .connectionmenu import CanvasConnectionMenu as CanvasConnectionMenu
from .diagrammenu import CanvasDiagramMenu as CanvasDiagramMenu
from .elementmenu import CanvasElementMenu as CanvasElementMenu
from PyQt5.QtWidgets import QWidget
from umlfri2.application import Application as Application
from umlfri2.application.commands.diagram import ChangeZOrderCommand as ChangeZOrderCommand, HideConnectionCommand as HideConnectionCommand, HideElementsCommand as HideElementsCommand, ShowElementCommand as ShowElementCommand, ZOrderDirection as ZOrderDirection
from umlfri2.application.commands.model import DeleteConnectionCommand as DeleteConnectionCommand, DeleteElementsCommand as DeleteElementsCommand
from umlfri2.application.drawingarea import DrawingAreaCursor as DrawingAreaCursor
from umlfri2.application.events.application import ZoomChangedEvent as ZoomChangedEvent
from umlfri2.application.events.diagram import DiagramChangedEvent as DiagramChangedEvent, SelectionChangedEvent as SelectionChangedEvent
from umlfri2.application.events.model import ConnectionChangedEvent as ConnectionChangedEvent, ElementCreatedEvent as ElementCreatedEvent, ElementDeletedEvent as ElementDeletedEvent, NodeMovedEvent as NodeMovedEvent, ObjectDataChangedEvent as ObjectDataChangedEvent
from umlfri2.application.events.solution import MetamodelConfigChangedEvent as MetamodelConfigChangedEvent
from umlfri2.constants.keys import DELETE_FROM_PROJECT as DELETE_FROM_PROJECT, Z_ORDER_LOWER as Z_ORDER_LOWER, Z_ORDER_RAISE as Z_ORDER_RAISE, Z_ORDER_TO_BOTTOM as Z_ORDER_TO_BOTTOM, Z_ORDER_TO_TOP as Z_ORDER_TO_TOP
from umlfri2.metamodel import DefaultElementAction as DefaultElementAction
from umlfri2.model import ElementObject as ElementObject
from umlfri2.model.element import ElementVisual as ElementVisual
from umlfri2.types.geometry import Point as Point

class CanvasWidget(QWidget):
    def __init__(self, main_window, drawing_area) -> None: ...
    @property
    def diagram(self): ...
    def paintEvent(self, event) -> None: ...
    def mousePressEvent(self, event) -> None: ...
    def mouseMoveEvent(self, event) -> None: ...
    def mouseReleaseEvent(self, event) -> None: ...
    def mouseDoubleClickEvent(self, event) -> None: ...
    def wheelEvent(self, event) -> None: ...
    def contextMenuEvent(self, event) -> None: ...
    def dragEnterEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...
