from ..patch import UflFlagsPatch as UflFlagsPatch
from .mutable import UflMutable as UflMutable

class UflMutableFlags(UflMutable):
    def __init__(self, type, values) -> None: ...
    @property
    def type(self): ...
    def __iter__(self): ...
    def __contains__(self, item) -> bool: ...
    def __eq__(self, other): ...
    def set(self, value) -> None: ...
    def unset(self, value) -> None: ...
    def get_length(self): ...
    def make_immutable(self): ...
    def make_patch(self): ...
    def copy(self) -> None: ...
