from ..patch import UflListPatch as UflListPatch
from .mutable import UflMutable as UflMutable
from umlfri2.ufl.uniquevaluegenerator import UniqueValueGenerator as UniqueValueGenerator

class ListItemValueGenerator(UniqueValueGenerator):
    def __init__(self, list) -> None: ...
    def get_parent_name(self) -> None: ...
    def for_name(self, name): ...
    def has_value(self, value): ...

class UflMutableList(UflMutable):
    def __init__(self, type, values) -> None: ...
    @property
    def type(self): ...
    def __iter__(self): ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other): ...
    def get_item(self, index): ...
    def set_item(self, index, value) -> None: ...
    def get_length(self): ...
    def create_default(self): ...
    def append(self, value=None): ...
    def delete(self, index) -> None: ...
    def move_up(self, index) -> None: ...
    def move_down(self, index) -> None: ...
    def make_immutable(self): ...
    def make_patch(self): ...
    def copy(self): ...
