from ..patch import UflListPatch as UflListPatch
from .mutable import UflMutable as UflMutable
from umlfri2.ufl.uniquevaluegenerator import UniqueValueGenerator as UniqueValueGenerator

from typing import (
    Any,
    Iterator,
    List,
    Optional,
    Union,
)
from umlfri2.ufl.objects.immutable.list import UflList
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.mutable.object import UflMutableObject
from umlfri2.ufl.objects.patch.list import UflListPatch
from umlfri2.ufl.types.structured.list import UflListType

class ListItemValueGenerator(UniqueValueGenerator):
    def __init__(self, list: UflMutableList) -> None: ...
    def get_parent_name(self) -> None: ...
    def for_name(self, name: str) -> ListItemValueGenerator: ...
    def has_value(self, value: str) -> bool: ...

class UflMutableList(UflMutable):
    def __init__(
        self,
        type: UflListType,
        values: List[Union[UflObject, Any]]
    ) -> None: ...
    @property
    def type(self) -> UflListType: ...
    def __iter__(self) -> Iterator[UflMutableObject]: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, other): ...
    def get_item(self, index): ...
    def set_item(self, index, value) -> None: ...
    def get_length(self): ...
    def create_default(self) -> UflMutableObject: ...
    def append(
        self,
        value: Optional[UflMutableObject] = ...
    ) -> UflMutableObject: ...
    def move_up(self, index) -> None: ...
    def move_down(self, index) -> None: ...
    def make_immutable(self) -> UflList: ...
    def make_patch(self) -> UflListPatch: ...
    def copy(self) -> UflMutableList: ...
