from .mutable import UflMutable as UflMutable
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.ufl.objects.patch import UflObjectPatch as UflObjectPatch

from typing import (
    Any,
    Dict,
    Union,
)
from umlfri2.types.color import Color
from umlfri2.types.font import Font
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.patch.object import UflObjectPatch
from umlfri2.ufl.types.structured.object import UflObjectType

class UflMutableObject(UflMutable):
    def __init__(self, type: UflObjectType, attributes: Dict[str, Any]) -> None: ...
    @property
    def type(self) -> UflObjectType: ...
    def __eq__(self, other): ...
    def get_values(self) -> Generator[Incomplete]: ...
    def get_value(self, name: str) -> Any: ...
    def set_value(self, name: str, value: Union[Color, Font, str, bool]) -> None: ...
    def make_immutable(self) -> UflObject: ...
    def make_patch(self) -> UflObjectPatch: ...
    def copy(self) -> UflMutableObject: ...
