from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from umlfri2.types.geometry import Size as Size
from umlfri2.qtgui.rendering.qtpaintercanvas import QTPainterCanvas
from umlfri2.types.geometry.rectangle import Rectangle
from umlfri2.types.geometry.size import Size

class EmptyObject(VisualObject):
    def assign_bounds(self, bounds: Rectangle) -> None: ...
    def get_minimal_size(self) -> Size: ...
    def draw(self, canvas: QTPainterCanvas, shadow: None) -> None: ...
    def is_resizable(self): ...

class EmptyComponent(VisualComponent):
    HAS_CHILDREN: bool
    def __init__(self) -> None: ...
