from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from _typeshed import Incomplete
from umlfri2.types.geometry import Rectangle as Rectangle
from umlfri2.ufl.types.complex import UflImageType as UflImageType

class ImageObject(VisualObject):
    def __init__(self, size, image) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class ImageComponent(VisualComponent):
    ATTRIBUTES: Incomplete
    HAS_CHILDREN: bool
    def __init__(self, image) -> None: ...
    def compile(self, type_context) -> None: ...
