from ..valueproviders import DefaultValueProvider as DefaultValueProvider
from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from _typeshed import Incomplete
from umlfri2.types.geometry import Rectangle as Rectangle, Size as Size
from umlfri2.ufl.types.basic import UflIntegerType as UflIntegerType

class PaddingObject(VisualObject):
    def __init__(self, child, left, right, top, bottom) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class PaddingComponent(VisualComponent):
    ATTRIBUTES: Incomplete
    def __init__(self, children, padding=None, left=None, right=None, top=None, bottom=None) -> None: ...
    def compile(self, type_context) -> None: ...
