from ..valueproviders import DefaultValueProvider as DefaultValueProvider
from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from _typeshed import Incomplete
from umlfri2.types.geometry import Size as Size
from umlfri2.types.threestate import Maybe as Maybe
from umlfri2.ufl.types.basic import UflIntegerType as UflIntegerType
from umlfri2.ufl.types.structured import UflNullableType as UflNullableType

class SizerObject(VisualObject):
    def __init__(self, child, minwidth, maxwidth, minheight, maxheight, width, height) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class SizerComponent(VisualComponent):
    ATTRIBUTES: Incomplete
    def __init__(self, children, minwidth=None, maxwidth=None, minheight=None, maxheight=None, width=None, height=None) -> None: ...
    def compile(self, type_context) -> None: ...
