from ..base.componenttype import ComponentType as ComponentType
from ..base.helpercomponent import HelperComponent as HelperComponent
from .visualcomponent import VisualComponent as VisualComponent, VisualObject as VisualObject
from _typeshed import Incomplete
from umlfri2.types.geometry import Rectangle as Rectangle, Size as Size
from umlfri2.types.threestate import Maybe as Maybe

class TableObject(VisualObject):
    def __init__(self, table) -> None: ...
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self): ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self): ...

class TableRow(HelperComponent):
    CHILDREN_TYPE: Incomplete
    def compile(self, type_context) -> None: ...

class TableColumn(HelperComponent):
    CHILDREN_TYPE: Incomplete
    def compile(self, type_context) -> None: ...

class TableComponent(VisualComponent):
    CHILDREN_TYPE: Incomplete
    def __init__(self, children) -> None: ...
    def compile(self, type_context) -> None: ...
