from ..base.component import Component as Component

class VisualObject:
    def assign_bounds(self, bounds) -> None: ...
    def get_minimal_size(self) -> None: ...
    def draw(self, canvas, shadow) -> None: ...
    def is_resizable(self) -> None: ...

class VisualComponent(Component): ...
