from ...objects import UflFlags as UflFlags
from ..base.type import UflType as UflType
from _typeshed import Incomplete
from collections.abc import Generator

class UflFlagsType(UflType):
    def __init__(self, possibilities, default=None) -> None: ...
    @property
    def default_possibilities(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def has_default(self): ...
    def build_default(self, generator): ...
    @property
    def possibilities(self): ...
    @property
    def is_immutable(self): ...
    @property
    def item_type(self) -> None: ...
    def parse(self, value): ...
    def parse_possibility(self, value): ...
    def is_valid_possibility(self, value): ...
    def is_default_value(self, value): ...
