from ..basic.string import UflStringType as UflStringType
from .enumpossibility import UflEnumPossibility as UflEnumPossibility
from .flags import UflFlagsType as UflFlagsType

class UflStringFlagsType(UflFlagsType):
    def __init__(self, possibilities, default=None) -> None: ...
    @property
    def item_type(self): ...
    def is_assignable_from(self, other): ...
    def is_equatable_to(self, other): ...
