from umlfri2.ufl.types.complex import UflColorType as UflColorType, UflFontType as UflFontType
from umlfri2.ufl.types.structured import UflListType as UflListType, UflObjectType as UflObjectType

class UflObjectApiHelper:
    def __init__(self, ufl_object) -> None: ...
    def __iter__(self): ...
    def __getitem__(self, item): ...
