from PyQt5.QtWidgets import QPushButton
from _typeshed import Incomplete

class ExpandButton(QPushButton):
    expanded_changed: Incomplete
    def __init__(self) -> None: ...
    @property
    def expanded(self): ...
    @expanded.setter
    def expanded(self, value) -> None: ...
    def event(self, e): ...
