class UflDialogOptions:
    def __init__(self, list_as_tab: bool, object_as_tab: bool, multiline_as_tab: bool) -> None: ...
    @property
    def list_as_tab(self) -> bool: ...
    @property
    def multiline_as_tab(self) -> bool: ...
    @property
    def object_as_tab(self) -> bool: ...
