from ..state import AddOnState as AddOnState
from umlfri2.application.addon.local.manager import AddOnManager


class AddOnStarter:
    class __StartErrorException(Exception): ...
    def __init__(self, manager: AddOnManager, *addons) -> None: ...
    @property
    def finished(self) -> bool: ...
    @property
    def has_error(self) -> bool: ...
    def do(self) -> None: ...
