from ..state import AddOnState as AddOnState
from _typeshed import Incomplete
from typing import NamedTuple

class AddOnStopper:
    class __StopErrorException(Exception): ...

    class __AddonWithDep(NamedTuple):
        addon: Incomplete
        dependencies: Incomplete
    def __init__(self, manager, *addons) -> None: ...
    @property
    def finished(self): ...
    @property
    def has_error(self): ...
    def addons(self): ...
    def do(self) -> None: ...
