from .point import SnappedPoint as SnappedPoint
from .rectangle import SnappedRectangle as SnappedRectangle
from umlfri2.types.geometry import Point as Point, Vector as Vector

class InitializedSnapping:
    MAXIMAL_DISTANCE: int
    def __init__(self, rectangles, points) -> None: ...
    def add_point(self, point) -> None: ...
    def snap_point(self, point): ...
    def snap_rectangle(self, rectangle): ...
