from .interface import Interface as Interface
from _typeshed import Incomplete
from collections.abc import Generator

class IApplication(Interface):
    def __init__(self, executor) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_action(self, id: str): ...
    def get_actions(self) -> Generator[Incomplete]: ...
    def get_current_diagram(self): ...
    def set_current_diagram(self, value: object): ...
    def get_solution(self): ...
