from .interface import Interface as Interface
from _typeshed import Incomplete
from collections.abc import Generator

class IConnectionVisual(Interface):
    def __init__(self, executor, connection) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_destination(self): ...
    def get_diagram(self): ...
    def get_labels(self) -> Generator[Incomplete]: ...
    def get_object(self): ...
    def get_points(self) -> Generator[Incomplete]: ...
    def get_source(self): ...
