from .helpers.uflobject import UflObjectApiHelper as UflObjectApiHelper
from .interface import Interface as Interface
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.model import ElementObject as ElementObject

class IElementObject(Interface):
    def __init__(self, executor, element) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    @property
    def element_object(self): ...
    def get_children(self) -> Generator[Incomplete]: ...
    def get_connections(self) -> Generator[Incomplete]: ...
    def get_diagrams(self) -> Generator[Incomplete]: ...
    def get_name(self): ...
    def get_parent(self): ...
    def get_project(self): ...
    def get_type(self): ...
    def get_value(self, path: str): ...
    def get_values(self) -> Generator[Incomplete, Incomplete]: ...
    def get_visuals(self) -> Generator[Incomplete]: ...
