from .interface import Interface as Interface

class IElementType(Interface):
    def __init__(self, executor, element) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_name(self): ...
