from .interface import Interface as Interface
from _typeshed import Incomplete
from collections.abc import Generator

class IProject(Interface):
    def __init__(self, executor, project) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_children(self) -> Generator[Incomplete]: ...
    def get_metamodel(self): ...
    def get_name(self): ...
