from .interface import Interface as Interface
from _typeshed import Incomplete
from collections.abc import Generator

class ISolution(Interface):
    def __init__(self, executor, solution) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_file_name(self): ...
    def get_projects(self) -> Generator[Incomplete]: ...
