from .updates import UmlFriUpdates as UmlFriUpdates
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.types.version import Version as Version

class AboutUmlFri:
    name: str
    version: Incomplete
    is_debug_version = __debug__
    def __init__(self, application) -> None: ...
    @property
    def urls(self) -> Generator[Incomplete]: ...
    @property
    def author(self) -> Generator[Incomplete]: ...
    @property
    def description(self): ...
    @property
    def dependency_versions(self) -> Generator[Incomplete]: ...
    @property
    def version_1_contributions(self) -> Generator[Incomplete]: ...
    @property
    def updates(self): ...
