from .events.application import ChangeStatusChangedEvent as ChangeStatusChangedEvent
from _typeshed import Incomplete
from collections.abc import Generator

MAX_STACK_SIZE: int

class CommandProcessor:
    def __init__(self, application) -> None: ...
    def execute(self, command) -> None: ...
    def undo(self, count: int = 1) -> None: ...
    def redo(self, count: int = 1) -> None: ...
    def clear_buffers(self) -> None: ...
    @property
    def undo_stack_size(self): ...
    def get_undo_stack(self, count=None) -> Generator[Incomplete, Incomplete]: ...
    @property
    def redo_stack_size(self): ...
    def get_redo_stack(self, count=None) -> Generator[Incomplete, Incomplete]: ...
    @property
    def can_undo(self): ...
    @property
    def can_redo(self): ...
    @property
    def changed(self): ...
    def mark_unchanged(self) -> None: ...
