from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.constants.paths import CONFIG as CONFIG
from umlfri2.types.version import Version as Version

class ApplicationConfig:
    CONFIG_FILE: Incomplete
    def __init__(self) -> None: ...
    @property
    def language(self): ...
    @language.setter
    def language(self, value) -> None: ...
    @property
    def ignored_versions(self) -> Generator[Incomplete, Incomplete]: ...
    def ignore_version(self, version) -> None: ...
    def unignore_versions(self, *versions) -> None: ...
    @property
    def auto_check_updates(self): ...
    @auto_check_updates.setter
    def auto_check_updates(self, value) -> None: ...
    @property
    def export_zoom(self): ...
    @property
    def export_padding(self): ...
    def set_export_options(self, zoom, padding) -> None: ...
