from .events.application import LanguageChangedEvent as LanguageChangedEvent
from umlfri2.constants.paths import LOCALE_DIR as LOCALE_DIR

class LanguageManager:
    def __init__(self, application) -> None: ...
    def change_language(self, language) -> None: ...
    @property
    def current_language(self): ...
