from .events.application import RecentFilesChangedEvent as RecentFilesChangedEvent

class RecentFile:
    def __init__(self, application, recent_files, file_path, pinned: bool = False) -> None: ...
    @property
    def exists(self): ...
    @property
    def file_name(self): ...
    @property
    def path(self): ...
    @property
    def pinned(self): ...
    def pin(self) -> None: ...
    def unpin(self) -> None: ...
    def remove(self) -> None: ...
    def open(self) -> None: ...
