from .drawingarea import DrawingArea as DrawingArea
from umlfri2.application.events.tabs import TabLockStatusChangedEvent as TabLockStatusChangedEvent

class Tab:
    def __init__(self, application, tabs, diagram, locked: bool = False) -> None: ...
    @property
    def locked(self): ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def close(self) -> None: ...
    @property
    def drawing_area(self): ...
    @property
    def name(self): ...
    @property
    def icon(self): ...
