from .events.model import DiagramDeletedEvent as DiagramDeletedEvent
from .events.tabs import ChangedCurrentTabEvent as ChangedCurrentTabEvent, ClosedTabEvent as ClosedTabEvent, OpenTabEvent as OpenTabEvent
from .tab import Tab as Tab
from umlfri2.application.events.solution import CloseSolutionEvent as CloseSolutionEvent

class TabList:
    def __init__(self, application) -> None: ...
    def reset_lock_status(self) -> None: ...
    @property
    def lock_status_changed(self): ...
    def get_tab_for(self, diagram): ...
    def open_new_project_tabs(self, tabs) -> None: ...
    def select_tab(self, diagram): ...
    def close_all(self) -> None: ...
    @property
    def current_tab(self): ...
    def __iter__(self): ...
