from .events.application import UpdateCheckFinishedEvent as UpdateCheckFinishedEvent, UpdateCheckStartedEvent as UpdateCheckStartedEvent
from umlfri2.types.exceptioninfo import ExceptionInfo as ExceptionInfo
from umlfri2.types.version import Version as Version

class UmlFriUpdate:
    def __init__(self, application, version, url) -> None: ...
    @property
    def url(self): ...
    @property
    def version(self): ...
    @property
    def is_newer(self): ...
    @property
    def is_ignored(self): ...
    def ignore_update(self) -> None: ...

class UmlFriUpdates:
    def __init__(self, about, application) -> None: ...
    @property
    def checking_update(self): ...
    @property
    def latest_version(self): ...
    @property
    def latest_prerelease(self): ...
    @property
    def has_error(self): ...
    @property
    def error(self): ...
    def recheck_update(self) -> None: ...
