from .about import AboutUmlFri as AboutUmlFri
from .addon import AddOnList as AddOnList
from .commandprocessor import CommandProcessor as CommandProcessor
from .commands.solution import NewProjectCommand as NewProjectCommand
from .dispatcher import EventDispatcher as EventDispatcher
from .events.application import ClipboardSnippetChangedEvent as ClipboardSnippetChangedEvent, ItemSelectedEvent as ItemSelectedEvent
from .events.solution import CloseSolutionEvent as CloseSolutionEvent, OpenSolutionEvent as OpenSolutionEvent, SaveSolutionEvent as SaveSolutionEvent
from .language import LanguageManager as LanguageManager
from .recentfiles import RecentFiles as RecentFiles
from .startupoptions import StartupOptions as StartupOptions
from .tablist import TabList as TabList
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.config import ApplicationConfig as ApplicationConfig
from umlfri2.datalayer.loaders import WholeSolutionLoader as WholeSolutionLoader
from umlfri2.datalayer.savers import WholeSolutionSaver as WholeSolutionSaver
from umlfri2.datalayer.storages import Storage as Storage, UnknownStorageException as UnknownStorageException, ZipStorage as ZipStorage
from umlfri2.model import ProjectBuilder as ProjectBuilder, Solution as Solution
from typing import (
    Any,
    Iterator,
    List,
    Optional,
    Union,
)
from umlfri2.application.about import AboutUmlFri
from umlfri2.application.addon.list import AddOnList
from umlfri2.application.commandprocessor import CommandProcessor
from umlfri2.application.config import ApplicationConfig
from umlfri2.application.dispatcher import EventDispatcher
from umlfri2.application.language import LanguageManager
from umlfri2.application.recentfile import RecentFile
from umlfri2.application.tablist import TabList
from umlfri2.metamodel.projecttemplate.project import ProjectTemplate
from umlfri2.model.diagram import Diagram
from umlfri2.model.element.elementobject import ElementObject
from umlfri2.model.project import Project
from umlfri2.model.solution import Solution
from umlfri2.qtgui.base.qtthreadmanager import QTThreadManager
from umlfri2.qtgui.rendering.qtruler import QTRuler


class MetaApplication(type):
    def __call__(cls) -> Application: ...

class Application(metaclass=MetaApplication):
    def __init__(self) -> None: ...
    @property
    def about(self) -> AboutUmlFri: ...
    def start(self) -> None: ...
    def init_after_main_window_shown(self) -> None: ...
    def stop(self) -> None: ...
    def use_args(self, args: List[Any]) -> None: ...
    def use_ruler(self, ruler: QTRuler) -> None: ...
    def use_thread_manager(self, thread_manager: QTThreadManager) -> None: ...
    @property
    def ruler(self) -> QTRuler: ...
    @property
    def thread_manager(self) -> Optional[QTThreadManager]: ...
    @property
    def event_dispatcher(self) -> EventDispatcher: ...
    @property
    def commands(self) -> CommandProcessor: ...
    @property
    def solution(self) -> Optional[Solution]: ...
    @property
    def addons(self) -> AddOnList: ...
    @property
    def tabs(self) -> TabList: ...
    @property
    def unsaved(self) -> bool: ...
    @property
    def change_status(self) -> bool: ...
    @property
    def templates(self) -> Iterator[ProjectTemplate]: ...
    @property
    def recent_files(self) -> Iterator[RecentFile]: ...
    @property
    def solution_name(self) -> Optional[str]: ...
    def new_project(
        self,
        template: ProjectTemplate,
        new_solution: bool = True,
        project_name: str = 'Project'
    ) -> None: ...
    def is_valid_save_file(self, filename): ...
    @property
    def should_save_as(self) -> bool: ...
    @property
    def can_save_solution(self) -> bool: ...
    def save_solution(self) -> None: ...
    @property
    def can_save_solution_as(self) -> bool: ...
    def save_solution_as(self, filename: str) -> None: ...
    def open_solution_in_steps(self, filename: str) -> Iterator[str]: ...
    def open_solution(self, filename: str) -> None: ...
    def close_solution(self) -> None: ...
    @property
    def language(self) -> LanguageManager: ...
    @property
    def config(self) -> ApplicationConfig: ...
    @property
    def selected_item(self): ...
    def select_item(
        self,
        element: Optional[Union[Project, Diagram, ElementObject]]
    ) -> None: ...
    @property
    def clipboard_empty(self) -> bool: ...
    @property
    def clipboard(self): ...
    @clipboard.setter
    def clipboard(self, value) -> None: ...
