from .events.application import ChangeStatusChangedEvent as ChangeStatusChangedEvent
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.application import Application
from umlfri2.application.commands.base.command import Command


MAX_STACK_SIZE: int

class CommandProcessor:
    def __init__(self, application: Application) -> None: ...
    def execute(self, command: Command) -> None: ...
    def undo(self, count: int = 1) -> None: ...
    def redo(self, count: int = 1) -> None: ...
    def clear_buffers(self) -> None: ...
    @property
    def undo_stack_size(self): ...
    def get_undo_stack(self, count=None) -> Generator[Incomplete, Incomplete]: ...
    @property
    def redo_stack_size(self): ...
    def get_redo_stack(self, count=None) -> Generator[Incomplete, Incomplete]: ...
    @property
    def can_undo(self) -> bool: ...
    @property
    def can_redo(self) -> bool: ...
    @property
    def changed(self) -> bool: ...
    def mark_unchanged(self) -> None: ...
