from _weakref import ref

class methodref(ref):
    def __new__(cls, method, callback=None): ...
    def __call__(self): ...

class EventDispatcher:
    def __init__(self, application) -> None: ...
    def subscribe(self, event_type, function, auto_unsubscribe: bool = True) -> None: ...
    def unsubscribe(self, event_type, function) -> None: ...
    def dispatch(self, event) -> None: ...
    def dispatch_all(self, events) -> None: ...
    def clear(self) -> None: ...
