from .events.application import UpdateCheckFinishedEvent as UpdateCheckFinishedEvent, UpdateCheckStartedEvent as UpdateCheckStartedEvent
from umlfri2.types.exceptioninfo import ExceptionInfo as ExceptionInfo
from umlfri2.types.version import Version as Version
from typing import Optional
from umlfri2.application.about import AboutUmlFri
from umlfri2.application.application import Application
from umlfri2.types.version import Version


class UmlFriUpdate:
    def __init__(self, application, version, url) -> None: ...
    @property
    def url(self): ...
    @property
    def version(self) -> Version: ...
    @property
    def is_newer(self) -> bool: ...
    @property
    def is_ignored(self): ...
    def ignore_update(self) -> None: ...

class UmlFriUpdates:
    def __init__(
        self,
        about: AboutUmlFri,
        application: Application
    ) -> None: ...
    @property
    def checking_update(self) -> bool: ...
    @property
    def latest_version(self) -> Optional[UmlFriUpdate]: ...
    @property
    def latest_prerelease(self) -> None: ...
    @property
    def has_error(self) -> bool: ...
    @property
    def error(self): ...
    def recheck_update(self) -> None: ...
