from PyQt5.QtGui import QFocusEvent


class AddOnListWidget:
    def __init__(self, check_boxes: bool = ..., show_prev_version: bool = ...) -> None: ...
    def focusInEvent(self, event: QFocusEvent) -> None: ...
    def focusOutEvent(self, event: QFocusEvent) -> None: ...
    def refresh(self) -> None: ...
