from typing import Optional


class AddOnDependency:
    def __eq__(self, other: AddOnDependency) -> bool: ...
    def __hash__(self) -> int: ...
    def __init__(
        self,
        type: AddOnDependencyType,
        id: str,
        version: None = ...
    ) -> None: ...
