from io import BufferedReader
from typing import (
    Iterator,
    List,
    Optional,
)
from umlfri2.datalayer.storages.zip import ZipStorage


class DirectoryStorage:
    def __init__(self, path: str, mode: str) -> None: ...
    def close(self) -> None: ...
    def copy_from(self, storage: ZipStorage) -> None: ...
    def create_substorage(self, path: str) -> DirectoryStorage: ...
    def exists(self, path: str) -> bool: ...
    def get_all_files(self) -> Iterator[str]: ...
    def list(self, path: None = ...) -> List[str]: ...
    def make_dir(self, path: str) -> DirectoryStorage: ...
    @staticmethod
    def new_storage(path: str) -> DirectoryStorage: ...
    def open(self, path: str, mode: str = ...) -> BufferedReader: ...
    @property
    def path(self) -> str: ...
    @staticmethod
    def read_storage(path: str) -> Optional[DirectoryStorage]: ...
    def read_string(self, path: str) -> str: ...
    def remember_reference(self) -> DirectoryStorageReference: ...
    def remove_storage(self) -> None: ...
    def store_string(self, path: str, data: str) -> None: ...


class DirectoryStorageReference:
    def __init__(self, path: str, mode: str) -> None: ...
    def open(self, mode: Optional[str] = ...) -> DirectoryStorage: ...
