from typing import (
    Any,
    Iterator,
    List,
    Optional,
    Union,
)
from zipfile import (
    ZipExtFile,
    ZipFile,
)


class ZipFileWriter:
    def __enter__(self) -> ZipFileWriter: ...
    def __exit__(self, exc_type: None, exc_val: None, exc_tb: None) -> None: ...
    def __init__(self, zip_file: ZipFile, file_path: str) -> None: ...
    def close(self) -> None: ...


class ZipStorage:
    def __init__(
        self,
        zip_path: Optional[str],
        zip_file: ZipFile,
        path: List[Union[str, Any]],
        mode: str
    ) -> None: ...
    def close(self) -> None: ...
    def create_substorage(self, path: str) -> ZipStorage: ...
    def exists(self, path: str) -> bool: ...
    def get_all_files(self) -> Iterator[str]: ...
    @staticmethod
    def new_storage(path: str) -> ZipStorage: ...
    def open(
        self,
        path: str,
        mode: str = ...
    ) -> Union[ZipExtFile, ZipFileWriter]: ...
    @staticmethod
    def read_from_memory(bytes: bytes) -> ZipStorage: ...
    @staticmethod
    def read_storage(path: str) -> ZipStorage: ...
    def read_string(self, path: str) -> str: ...
    def remember_reference(self) -> ZipStorageReference: ...
    def store_string(self, path: str, data: str) -> None: ...


class ZipStorageReference:
    def __init__(self, zip_path: str, path: List[Any], mode: str) -> None: ...
    @property
    def name(self) -> str: ...
    def open(self, mode: Optional[str] = ...) -> ZipStorage: ...
    @property
    def still_valid(self) -> bool: ...
