from .node import UflNode as UflNode

class UflAttributeAccessNode(UflNode):
    def __init__(self, obj, attribute, type=None) -> None: ...
    @property
    def object(self): ...
    @property
    def attribute(self): ...
    def accept(self, visitor): ...
