from .node import UflNode as UflNode

class UflEnumNode(UflNode):
    def __init__(self, enum, item, type=None) -> None: ...
    @property
    def enum(self): ...
    @property
    def item(self): ...
    def accept(self, visitor): ...
