from .node import UflNode as UflNode
from _typeshed import Incomplete
from collections.abc import Generator

class UflExpressionNode(UflNode):
    def __init__(self, result, variables, type=None) -> None: ...
    @property
    def result(self): ...
    @property
    def variables(self) -> Generator[Incomplete, Incomplete]: ...
    def accept(self, visitor): ...
