from .node import UflNode as UflNode
from _typeshed import Incomplete
from collections.abc import Generator

class UflLambdaExpressionNode(UflNode):
    def __init__(self, body, parameters, type=None) -> None: ...
    @property
    def body(self): ...
    @property
    def parameter_count(self): ...
    @property
    def parameters(self) -> Generator[Incomplete, Incomplete]: ...
    def accept(self, visitor): ...
