from .node import UflNode as UflNode

class UflMacroInvokeNode(UflNode):
    def __init__(self, target, selector, arguments, inner_type_invoke, macro=None, type=None) -> None: ...
    @property
    def target(self): ...
    @property
    def selector(self): ...
    @property
    def arguments(self): ...
    @property
    def macro(self): ...
    @property
    def inner_type_invoke(self): ...
    def accept(self, visitor): ...
