from _typeshed import Incomplete
from collections.abc import Generator

class UflNode:
    def __init__(self, type) -> None: ...
    @property
    def type(self): ...
    def find(self, condition, cut_branch=...) -> Generator[Incomplete, Incomplete, Incomplete]: ...
    def to_string(self): ...
    def to_string_indented(self, indent: int = 0): ...
    def accept(self, visitor) -> None: ...
