from .node import UflNode as UflNode

class UflObjectMetadataAccessNode(UflNode):
    def __init__(self, obj, metadata_name, type=None) -> None: ...
    @property
    def object(self): ...
    @property
    def metadata_name(self): ...
    def accept(self, visitor): ...
