from .node import UflNode as UflNode

class UflVariableMetadataAccessNode(UflNode):
    def __init__(self, obj, type=None) -> None: ...
    @property
    def object(self): ...
    def accept(self, visitor): ...
