class UflVisitor:
    def visit_attribute_access(self, node) -> None: ...
    def visit_enum(self, node) -> None: ...
    def visit_macro_invoke(self, node) -> None: ...
    def visit_technical_variable(self, node) -> None: ...
    def visit_variable(self, node) -> None: ...
    def visit_variable_definition(self, node) -> None: ...
    def visit_literal(self, node) -> None: ...
    def visit_binary(self, node) -> None: ...
    def visit_unary(self, node) -> None: ...
    def visit_variable_metadata_access(self, node) -> None: ...
    def visit_object_metadata_access(self, node) -> None: ...
    def visit_unpack(self, node) -> None: ...
    def visit_expression(self, node) -> None: ...
    def visit_lambda_expression(self, node) -> None: ...
    def visit_cast(self, node) -> None: ...
