from .tabs import *
from .columns import *
from .widgets import *
from ..objects.mutable import UflMutable as UflMutable
from ..types.basic import UflBoolType as UflBoolType, UflDecimalType as UflDecimalType, UflIntegerType as UflIntegerType, UflStringType as UflStringType
from ..types.complex import UflColorType as UflColorType, UflFontType as UflFontType
from ..types.enum import UflEnumType as UflEnumType, UflFlagsType as UflFlagsType
from ..types.structured import UflListType as UflListType, UflNullableType as UflNullableType, UflObjectType as UflObjectType
from .options import UflDialogOptions as UflDialogOptions
from _typeshed import Incomplete
from collections.abc import Generator

class UflDialog:
    def __init__(self, type, options=...) -> None: ...
    @property
    def should_save_tab(self): ...
    @property
    def has_changes(self): ...
    def switch_tab(self, index) -> None: ...
    @property
    def current_tab(self): ...
    @property
    def original_object(self): ...
    def finish(self) -> None: ...
    def make_patch(self): ...
    @property
    def tabs(self) -> Generator[Incomplete, Incomplete]: ...
    def get_lonely_tab(self): ...
    def associate(self, ufl_object) -> None: ...
    def refresh(self) -> None: ...
    def translate(self, translation) -> None: ...
    def reset(self) -> None: ...
