from enum import Enum

class UflDialogOptions(Enum):
    standard = (True, True, False)
    list = (False, False, True)
    def __init__(self, list_as_tab, object_as_tab, multiline_as_tab) -> None: ...
    @property
    def list_as_tab(self): ...
    @property
    def object_as_tab(self): ...
    @property
    def multiline_as_tab(self): ...
