from .tab import PropertyTab as PropertyTab
from umlfri2.constants.keys import MOVE_DOWN as MOVE_DOWN, MOVE_UP as MOVE_UP
from umlfri2.qtgui.base.hlinewidget import HLineWidget as HLineWidget

class ListPropertyTab(PropertyTab):
    def __init__(self, window, tab, lonely: bool = False) -> None: ...
    def handle_needed_save(self): ...
    def refresh(self) -> None: ...
