from .enum import UflEnumType as UflEnumType
from .enumpossibility import UflEnumPossibility as UflEnumPossibility

class UflDefinedEnumType(UflEnumType):
    def __init__(self, type, possibilities={}, default=None) -> None: ...
    @property
    def name(self): ...
    @property
    def type(self): ...
    def is_assignable_from(self, other): ...
    def is_equatable_to(self, other): ...
