from ..base.type import UflType as UflType

class UflEnumType(UflType):
    def __init__(self, possibilities, default=None) -> None: ...
    @property
    def default_possibility(self): ...
    @property
    def default(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator): ...
    @property
    def possibilities(self): ...
    @property
    def is_immutable(self): ...
    def parse(self, value): ...
    def is_valid_value(self, value): ...
    def is_valid_item(self, item): ...
    def is_default_value(self, value): ...
