from ..basic.string import UflStringType as UflStringType
from .enum import UflEnumType as UflEnumType
from .enumpossibility import UflEnumPossibility as UflEnumPossibility

class UflStringEnumType(UflEnumType):
    def __init__(self, possibilities, default=None) -> None: ...
    def is_assignable_from(self, other): ...
    def is_convertible_to(self, other): ...
    def is_equatable_to(self, other): ...
