from .enum import UflEnumType as UflEnumType
from .enumpossibility import UflEnumPossibility as UflEnumPossibility

from typing import (
    Any,
    Optional,
)

class UflTypedEnumType(UflEnumType):
    def __init__(self, type: Any, default: None = ...) -> None: ...
    @property
    def name(self): ...
    @property
    def type(self): ...
    def is_assignable_from(self, other: UflTypedEnumType) -> bool: ...
    def is_equatable_to(self, other): ...
