from PyQt5.QtCore import QSize
from umlfri2.metamodel.projecttemplate.project import ProjectTemplate
from umlfri2.qtgui.mainwindow.mainwindow import UmlFriMainWindow


class NewProjectDialog:
    def __init__(self, main_window: UmlFriMainWindow) -> None: ...
    @property
    def new_solution(self) -> bool: ...
    @staticmethod
    def open_dialog(
        main_window: UmlFriMainWindow
    ) -> NewProjectDialog: ...
    @property
    def project_name(self) -> str: ...
    @property
    def selected_template(self) -> ProjectTemplate: ...
    def sizeHint(self) -> QSize: ...


class TemplateItem:
    def __init__(self, template: ProjectTemplate) -> None: ...
    @property
    def template(self) -> ProjectTemplate: ...
