from _typeshed import Incomplete
from collections.abc import Generator

class OnlineAddOn:
    def __init__(self, application, identifier, versions) -> None: ...
    @property
    def identifier(self): ...
    @property
    def name(self): ...
    @property
    def author(self): ...
    @property
    def homepage(self): ...
    @property
    def license(self): ...
    @property
    def icon(self): ...
    @property
    def description(self): ...
    @property
    def requirements(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def provisions(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def versions(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def latest_version(self): ...
    @property
    def local_addon(self): ...
