from .actions import OnlineAddOnInstaller as OnlineAddOnInstaller, OnlineAddOnUpdater as OnlineAddOnUpdater
from _typeshed import Incomplete
from collections.abc import Generator

class OnlineAddOnVersion:
    def __init__(self, application, name, version, author, homepage, license, icon, description, requirements, provisions, changelog, locations) -> None: ...
    @property
    def addon(self): ...
    @property
    def name(self): ...
    @property
    def version(self): ...
    @property
    def author(self): ...
    @property
    def homepage(self): ...
    @property
    def license(self): ...
    @property
    def icon(self): ...
    @property
    def description(self): ...
    @property
    def requirements(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def provisions(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def changelog(self): ...
    @property
    def valid_location(self): ...
    def install(self): ...
    def update(self): ...
