class ModelTemporaryDataCache:
    def __init__(self, callback) -> None: ...
    def depend_on(self, cache) -> None: ...
    def invalidate(self) -> None: ...
    def refresh(self, **kwargs) -> None: ...
    def ensure_valid(self, **kwargs) -> None: ...
