from PyQt5.QtWidgets import QLabel
from umlfri2.application import Application as Application
from umlfri2.constants.paths import GRAPHICS as GRAPHICS

class ExitScreen(QLabel):
    def __init__(self) -> None: ...
    def start(self) -> None: ...
    def closeEvent(self, event) -> None: ...
