from ..base.type import UflType as UflType
from ..enum.flags import UflFlagsType as UflFlagsType
from .list import UflListType as UflListType

class UflIterableType(UflType):
    def __init__(self, item_type) -> None: ...
    @property
    def item_type(self): ...
    def is_assignable_from(self, other): ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
