from .tab import UflDialogTab as UflDialogTab
from _typeshed import Incomplete
from collections.abc import Generator

class UflDialogListTab(UflDialogTab):
    def __init__(self, attr, list_type) -> None: ...
    def add_column(self, column) -> None: ...
    @property
    def columns(self) -> Generator[Incomplete]: ...
    @property
    def rows(self) -> Generator[Incomplete]: ...
    @property
    def can_new(self): ...
    def new(self) -> None: ...
    def save(self) -> None: ...
    def discard(self) -> None: ...
    @property
    def should_save(self): ...
    @property
    def can_save(self): ...
    @property
    def can_delete(self): ...
    def delete(self) -> None: ...
    @property
    def can_move_up(self): ...
    def move_up(self) -> None: ...
    @property
    def can_move_down(self): ...
    def move_down(self) -> None: ...
    @property
    def current_index(self): ...
    def change_current_index(self, value) -> None: ...
    def associate(self, ufl_object) -> None: ...
    def finish(self) -> None: ...
    def translate(self, translation) -> None: ...
    def tab_deselected(self) -> None: ...
