from ..widgets import UflDialogChildWidget as UflDialogChildWidget, UflDialogValuedWidget as UflDialogValuedWidget
from .tab import UflDialogTab as UflDialogTab

class UflDialogNullableValueTab(UflDialogTab):
    def __init__(self, attr, value_type) -> None: ...
    @property
    def is_null(self): ...
    @is_null.setter
    def is_null(self, value) -> None: ...
    def associate(self, ufl_object) -> None: ...
    def add_widget(self, widget) -> None: ...
    @property
    def widget(self): ...
    def finish(self) -> None: ...
