from _typeshed import Incomplete
from collections.abc import Generator

class UflDialogTab:
    def __init__(self, attr) -> None: ...
    @property
    def id(self): ...
    @property
    def tab_index(self): ...
    @property
    def name(self): ...
    @property
    def current_object(self): ...
    @property
    def widget_count(self): ...
    @property
    def first_widget(self): ...
    @property
    def widgets(self) -> Generator[Incomplete, Incomplete]: ...
    def add_widget(self, widget) -> None: ...
    def associate(self, ufl_object) -> None: ...
    def finish(self) -> None: ...
    @property
    def has_changes(self): ...
    def translate(self, translation) -> None: ...
