from ..widgets import UflDialogChildWidget as UflDialogChildWidget, UflDialogValuedWidget as UflDialogValuedWidget
from .tab import UflDialogTab as UflDialogTab

class UflDialogValueTab(UflDialogTab):
    def associate(self, ufl_object) -> None: ...
    def add_widget(self, widget) -> None: ...
    @property
    def widget(self): ...
    def finish(self) -> None: ...
