from ..cache import ModelTemporaryDataCache as ModelTemporaryDataCache
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.types.geometry import Point as Point, Rectangle as Rectangle, Size as Size

class ElementVisual:
    def __init__(self, diagram, object) -> None: ...
    def add_connection(self, connection) -> None: ...
    def remove_connection(self, connection) -> None: ...
    @property
    def cache(self): ...
    @property
    def object(self): ...
    @property
    def diagram(self): ...
    @property
    def connections(self) -> Generator[Incomplete, Incomplete]: ...
    def get_position(self, ruler): ...
    def get_size(self, ruler): ...
    def get_minimal_size(self, ruler): ...
    def get_bounds(self, ruler): ...
    def draw(self, canvas) -> None: ...
    def resize(self, ruler, new_size) -> None: ...
    def move(self, ruler, new_position) -> None: ...
    def is_at_position(self, ruler, position): ...
    def is_resizable(self, ruler): ...
