from ..cache import ModelTemporaryDataCache as ModelTemporaryDataCache
from ..connection.connectionobject import ConnectionObject as ConnectionObject
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.ufl.dialog import UflDialog as UflDialog, UflDialogOptions as UflDialogOptions
from umlfri2.ufl.uniquevaluegenerator import UniqueValueGenerator as UniqueValueGenerator

class ElementValueGenerator(UniqueValueGenerator):
    def __init__(self, parent, type) -> None: ...
    def get_parent_name(self): ...
    def for_name(self, name): ...
    def has_value(self, value): ...

class ElementObject:
    def __init__(self, parent, type, save_id=None) -> None: ...
    def add_visual(self, visual) -> None: ...
    def remove_visual(self, visual) -> None: ...
    @property
    def visuals(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def cache(self): ...
    @property
    def parent(self): ...
    def change_parent(self, new_parent, new_index) -> None: ...
    @property
    def type(self): ...
    @property
    def data(self): ...
    @property
    def connections(self) -> Generator[Incomplete, Incomplete]: ...
    def get_display_name(self): ...
    def create_appearance_object(self, ruler): ...
    def connect_with(self, connection_type, second_element, save_id=None): ...
    def get_connections_to(self, element) -> Generator[Incomplete]: ...
    def add_connection(self, connection) -> None: ...
    def remove_connection(self, connection) -> None: ...
    def reconnect(self, connection) -> None: ...
    def disconnect(self, connection) -> None: ...
    @property
    def project(self): ...
    @property
    def children_count(self): ...
    @property
    def children(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def diagram_count(self): ...
    @property
    def diagrams(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def save_id(self): ...
    def create_child_element(self, type, save_id=None): ...
    def create_child_diagram(self, type, save_id=None): ...
    def get_child_index(self, obj): ...
    def add_child(self, obj, index=None) -> None: ...
    def remove_child(self, obj) -> None: ...
    def apply_ufl_patch(self, patch) -> None: ...
    @property
    def has_ufl_dialog(self): ...
    def create_ufl_dialog(self, options=...): ...
    def invalidate_all_caches(self) -> None: ...
