from typing import Optional
from umlfri2.types.color import Color


class UflColorType:
    def __init__(self, default: Optional[Color] = ...) -> None: ...
    def build_default(self, generator: None) -> Color: ...
    def is_default_value(self, value: Color) -> bool: ...
    @property
    def is_immutable(self) -> bool: ...
    def is_valid_value(self, value: Color) -> bool: ...
    def parse(self, value: str) -> Color: ...
