from typing import Optional
from umlfri2.types.font import Font


class UflFontType:
    def __init__(self, default: Optional[Font] = ...) -> None: ...
    def build_default(self, generator: None) -> Font: ...
    def is_default_value(self, value: Font) -> bool: ...
    @property
    def is_immutable(self) -> bool: ...
    def is_valid_value(self, value: Font) -> bool: ...
    def parse(self, value: str) -> Font: ...
