from ..base.type import UflType as UflType

class UflAnyWithDefault(UflType):
    def is_assignable_from(self, other): ...
    def resolve_unknown_generic(self, generics_cache) -> None: ...
    def resolve_generic(self, actual_type, generics_cache): ...
