from ..base.type import UflType as UflType

class UflGenericType(UflType):
    def __init__(self, base_type) -> None: ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
