from PyQt5.QtWidgets import QTreeWidgetItem
from umlfri2.model import Project as Project
from umlfri2.qtgui.base import image_loader as image_loader

class ProjectTreeItem(QTreeWidgetItem):
    def __init__(self, model_object) -> None: ...
    @property
    def model_object(self): ...
    def refresh(self) -> None: ...
    def set_drop_enabled(self, enabled) -> None: ...
