from typing import (
    Any,
    Iterator,
    List,
    Optional,
    Union,
)
from umlfri2.ufl.objects.immutable.list import UflList
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.mutable.object import UflMutableObject
from umlfri2.ufl.objects.patch.list import UflListPatch
from umlfri2.ufl.types.structured.list import UflListType


class ListItemValueGenerator:
    def __init__(self, list: UflMutableList) -> None: ...
    def for_name(self, name: str) -> ListItemValueGenerator: ...
    def get_parent_name(self) -> None: ...
    def has_value(self, value: str) -> bool: ...


class UflMutableList:
    def __init__(
        self,
        type: UflListType,
        values: List[Union[UflObject, Any]]
    ) -> None: ...
    def __iter__(self) -> Iterator[UflMutableObject]: ...
    def append(
        self,
        value: Optional[UflMutableObject] = ...
    ) -> UflMutableObject: ...
    def copy(self) -> UflMutableList: ...
    def create_default(self) -> UflMutableObject: ...
    def make_immutable(self) -> UflList: ...
    def make_patch(self) -> UflListPatch: ...
    @property
    def type(self) -> UflListType: ...
