from typing import (
    Any,
    Dict,
    Union,
)
from umlfri2.types.color import Color
from umlfri2.types.font import Font
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.patch.object import UflObjectPatch
from umlfri2.ufl.types.structured.object import UflObjectType


class UflMutableObject:
    def __init__(self, type: UflObjectType, attributes: Dict[str, Any]) -> None: ...
    def copy(self) -> UflMutableObject: ...
    def get_value(self, name: str) -> Any: ...
    def make_immutable(self) -> UflObject: ...
    def make_patch(self) -> UflObjectPatch: ...
    def set_value(self, name: str, value: Union[Color, Font, str, bool]) -> None: ...
    @property
    def type(self) -> UflObjectType: ...
