from _typeshed import Incomplete

class Color:
    def __init__(self, argb) -> None: ...
    @property
    def alpha(self): ...
    @property
    def r(self): ...
    @property
    def g(self): ...
    @property
    def b(self): ...
    @property
    def rgb(self): ...
    @property
    def argb(self): ...
    @property
    def rgba(self): ...
    def invert(self): ...
    def add_alpha(self, alpha): ...
    def to_gray(self): ...
    def __eq__(self, other): ...
    def to_rgb_str(self): ...
    @staticmethod
    def from_string(color): ...
    @staticmethod
    def from_rgb_values(r, g, b, a: int = 255): ...
    @staticmethod
    def from_argb(argb): ...
    @staticmethod
    def from_rgba(rgba): ...

class Colors:
    aliceblue: Incomplete
    antiquewhite: Incomplete
    antiquewhite1: Incomplete
    antiquewhite2: Incomplete
    antiquewhite3: Incomplete
    antiquewhite4: Incomplete
    aquamarine: Incomplete
    aquamarine1: Incomplete
    aquamarine2: Incomplete
    aquamarine3: Incomplete
    aquamarine4: Incomplete
    azure: Incomplete
    azure1: Incomplete
    azure2: Incomplete
    azure3: Incomplete
    azure4: Incomplete
    beige: Incomplete
    bisque: Incomplete
    bisque1: Incomplete
    bisque2: Incomplete
    bisque3: Incomplete
    bisque4: Incomplete
    black: Incomplete
    blanchedalmond: Incomplete
    blue: Incomplete
    blue1: Incomplete
    blue2: Incomplete
    blue3: Incomplete
    blue4: Incomplete
    blueviolet: Incomplete
    brown: Incomplete
    brown1: Incomplete
    brown2: Incomplete
    brown3: Incomplete
    brown4: Incomplete
    burlywood: Incomplete
    burlywood1: Incomplete
    burlywood2: Incomplete
    burlywood3: Incomplete
    burlywood4: Incomplete
    cadetblue: Incomplete
    cadetblue1: Incomplete
    cadetblue2: Incomplete
    cadetblue3: Incomplete
    cadetblue4: Incomplete
    chartreuse: Incomplete
    chartreuse1: Incomplete
    chartreuse2: Incomplete
    chartreuse3: Incomplete
    chartreuse4: Incomplete
    chocolate: Incomplete
    chocolate1: Incomplete
    chocolate2: Incomplete
    chocolate3: Incomplete
    chocolate4: Incomplete
    coral: Incomplete
    coral1: Incomplete
    coral2: Incomplete
    coral3: Incomplete
    coral4: Incomplete
    cornflowerblue: Incomplete
    cornsilk: Incomplete
    cornsilk1: Incomplete
    cornsilk2: Incomplete
    cornsilk3: Incomplete
    cornsilk4: Incomplete
    cyan: Incomplete
    cyan1: Incomplete
    cyan2: Incomplete
    cyan3: Incomplete
    cyan4: Incomplete
    darkblue: Incomplete
    darkcyan: Incomplete
    darkgoldenrod: Incomplete
    darkgoldenrod1: Incomplete
    darkgoldenrod2: Incomplete
    darkgoldenrod3: Incomplete
    darkgoldenrod4: Incomplete
    darkgray: Incomplete
    darkgreen: Incomplete
    darkkhaki: Incomplete
    darkmagenta: Incomplete
    darkolivegreen: Incomplete
    darkolivegreen1: Incomplete
    darkolivegreen2: Incomplete
    darkolivegreen3: Incomplete
    darkolivegreen4: Incomplete
    darkorange: Incomplete
    darkorange1: Incomplete
    darkorange2: Incomplete
    darkorange3: Incomplete
    darkorange4: Incomplete
    darkorchid: Incomplete
    darkorchid1: Incomplete
    darkorchid2: Incomplete
    darkorchid3: Incomplete
    darkorchid4: Incomplete
    darkred: Incomplete
    darksalmon: Incomplete
    darkseagreen: Incomplete
    darkseagreen1: Incomplete
    darkseagreen2: Incomplete
    darkseagreen3: Incomplete
    darkseagreen4: Incomplete
    darkslateblue: Incomplete
    darkslategray: Incomplete
    darkslategray1: Incomplete
    darkslategray2: Incomplete
    darkslategray3: Incomplete
    darkslategray4: Incomplete
    darkturquoise: Incomplete
    darkviolet: Incomplete
    deeppink: Incomplete
    deeppink1: Incomplete
    deeppink2: Incomplete
    deeppink3: Incomplete
    deeppink4: Incomplete
    deepskyblue: Incomplete
    deepskyblue1: Incomplete
    deepskyblue2: Incomplete
    deepskyblue3: Incomplete
    deepskyblue4: Incomplete
    dimgray: Incomplete
    dodgerblue: Incomplete
    dodgerblue1: Incomplete
    dodgerblue2: Incomplete
    dodgerblue3: Incomplete
    dodgerblue4: Incomplete
    firebrick: Incomplete
    firebrick1: Incomplete
    firebrick2: Incomplete
    firebrick3: Incomplete
    firebrick4: Incomplete
    floralwhite: Incomplete
    forestgreen: Incomplete
    gainsboro: Incomplete
    ghostwhite: Incomplete
    gold: Incomplete
    gold1: Incomplete
    gold2: Incomplete
    gold3: Incomplete
    gold4: Incomplete
    goldenrod: Incomplete
    goldenrod1: Incomplete
    goldenrod2: Incomplete
    goldenrod3: Incomplete
    goldenrod4: Incomplete
    gray: Incomplete
    gray0: Incomplete
    gray1: Incomplete
    gray2: Incomplete
    gray3: Incomplete
    gray4: Incomplete
    gray5: Incomplete
    gray6: Incomplete
    gray7: Incomplete
    gray8: Incomplete
    gray9: Incomplete
    gray10: Incomplete
    gray11: Incomplete
    gray12: Incomplete
    gray13: Incomplete
    gray14: Incomplete
    gray15: Incomplete
    gray16: Incomplete
    gray17: Incomplete
    gray18: Incomplete
    gray19: Incomplete
    gray20: Incomplete
    gray21: Incomplete
    gray22: Incomplete
    gray23: Incomplete
    gray24: Incomplete
    gray25: Incomplete
    gray26: Incomplete
    gray27: Incomplete
    gray28: Incomplete
    gray29: Incomplete
    gray30: Incomplete
    gray31: Incomplete
    gray32: Incomplete
    gray33: Incomplete
    gray34: Incomplete
    gray35: Incomplete
    gray36: Incomplete
    gray37: Incomplete
    gray38: Incomplete
    gray39: Incomplete
    gray40: Incomplete
    gray41: Incomplete
    gray42: Incomplete
    gray43: Incomplete
    gray44: Incomplete
    gray45: Incomplete
    gray46: Incomplete
    gray47: Incomplete
    gray48: Incomplete
    gray49: Incomplete
    gray50: Incomplete
    gray51: Incomplete
    gray52: Incomplete
    gray53: Incomplete
    gray54: Incomplete
    gray55: Incomplete
    gray56: Incomplete
    gray57: Incomplete
    gray58: Incomplete
    gray59: Incomplete
    gray60: Incomplete
    gray61: Incomplete
    gray62: Incomplete
    gray63: Incomplete
    gray64: Incomplete
    gray65: Incomplete
    gray66: Incomplete
    gray67: Incomplete
    gray68: Incomplete
    gray69: Incomplete
    gray70: Incomplete
    gray71: Incomplete
    gray72: Incomplete
    gray73: Incomplete
    gray74: Incomplete
    gray75: Incomplete
    gray76: Incomplete
    gray77: Incomplete
    gray78: Incomplete
    gray79: Incomplete
    gray80: Incomplete
    gray81: Incomplete
    gray82: Incomplete
    gray83: Incomplete
    gray84: Incomplete
    gray85: Incomplete
    gray86: Incomplete
    gray87: Incomplete
    gray88: Incomplete
    gray89: Incomplete
    gray90: Incomplete
    gray91: Incomplete
    gray92: Incomplete
    gray93: Incomplete
    gray94: Incomplete
    gray95: Incomplete
    gray96: Incomplete
    gray97: Incomplete
    gray98: Incomplete
    gray99: Incomplete
    gray100: Incomplete
    green: Incomplete
    green1: Incomplete
    green2: Incomplete
    green3: Incomplete
    green4: Incomplete
    greenyellow: Incomplete
    honeydew: Incomplete
    honeydew1: Incomplete
    honeydew2: Incomplete
    honeydew3: Incomplete
    honeydew4: Incomplete
    hotpink: Incomplete
    hotpink1: Incomplete
    hotpink2: Incomplete
    hotpink3: Incomplete
    hotpink4: Incomplete
    indianred: Incomplete
    indianred1: Incomplete
    indianred2: Incomplete
    indianred3: Incomplete
    indianred4: Incomplete
    ivory: Incomplete
    ivory1: Incomplete
    ivory2: Incomplete
    ivory3: Incomplete
    ivory4: Incomplete
    khaki: Incomplete
    khaki1: Incomplete
    khaki2: Incomplete
    khaki3: Incomplete
    khaki4: Incomplete
    lavender: Incomplete
    lavenderblush: Incomplete
    lavenderblush1: Incomplete
    lavenderblush2: Incomplete
    lavenderblush3: Incomplete
    lavenderblush4: Incomplete
    lawngreen: Incomplete
    lemonchiffon: Incomplete
    lemonchiffon1: Incomplete
    lemonchiffon2: Incomplete
    lemonchiffon3: Incomplete
    lemonchiffon4: Incomplete
    lightblue: Incomplete
    lightblue1: Incomplete
    lightblue2: Incomplete
    lightblue3: Incomplete
    lightblue4: Incomplete
    lightcoral: Incomplete
    lightcyan: Incomplete
    lightcyan1: Incomplete
    lightcyan2: Incomplete
    lightcyan3: Incomplete
    lightcyan4: Incomplete
    lightgoldenrod: Incomplete
    lightgoldenrod1: Incomplete
    lightgoldenrod2: Incomplete
    lightgoldenrod3: Incomplete
    lightgoldenrod4: Incomplete
    lightgoldenrodyellow: Incomplete
    lightgray: Incomplete
    lightgreen: Incomplete
    lightpink: Incomplete
    lightpink1: Incomplete
    lightpink2: Incomplete
    lightpink3: Incomplete
    lightpink4: Incomplete
    lightsalmon: Incomplete
    lightsalmon1: Incomplete
    lightsalmon2: Incomplete
    lightsalmon3: Incomplete
    lightsalmon4: Incomplete
    lightseagreen: Incomplete
    lightskyblue: Incomplete
    lightskyblue1: Incomplete
    lightskyblue2: Incomplete
    lightskyblue3: Incomplete
    lightskyblue4: Incomplete
    lightslateblue: Incomplete
    lightslategray: Incomplete
    lightsteelblue: Incomplete
    lightsteelblue1: Incomplete
    lightsteelblue2: Incomplete
    lightsteelblue3: Incomplete
    lightsteelblue4: Incomplete
    lightyellow: Incomplete
    lightyellow1: Incomplete
    lightyellow2: Incomplete
    lightyellow3: Incomplete
    lightyellow4: Incomplete
    limegreen: Incomplete
    linen: Incomplete
    magenta: Incomplete
    magenta1: Incomplete
    magenta2: Incomplete
    magenta3: Incomplete
    magenta4: Incomplete
    maroon: Incomplete
    maroon1: Incomplete
    maroon2: Incomplete
    maroon3: Incomplete
    maroon4: Incomplete
    mediumaquamarine: Incomplete
    mediumblue: Incomplete
    mediumorchid: Incomplete
    mediumorchid1: Incomplete
    mediumorchid2: Incomplete
    mediumorchid3: Incomplete
    mediumorchid4: Incomplete
    mediumpurple: Incomplete
    mediumpurple1: Incomplete
    mediumpurple2: Incomplete
    mediumpurple3: Incomplete
    mediumpurple4: Incomplete
    mediumseagreen: Incomplete
    mediumslateblue: Incomplete
    mediumspringgreen: Incomplete
    mediumturquoise: Incomplete
    mediumvioletred: Incomplete
    midnightblue: Incomplete
    mintcream: Incomplete
    mistyrose: Incomplete
    mistyrose1: Incomplete
    mistyrose2: Incomplete
    mistyrose3: Incomplete
    mistyrose4: Incomplete
    moccasin: Incomplete
    navahowhite: Incomplete
    navahowhite1: Incomplete
    navahowhite2: Incomplete
    navahowhite3: Incomplete
    navahowhite4: Incomplete
    navajowhite: Incomplete
    navajowhite1: Incomplete
    navajowhite2: Incomplete
    navajowhite3: Incomplete
    navajowhite4: Incomplete
    navy: Incomplete
    navyblue: Incomplete
    oldlace: Incomplete
    olivedrab: Incomplete
    olivedrab1: Incomplete
    olivedrab2: Incomplete
    olivedrab3: Incomplete
    olivedrab4: Incomplete
    orange: Incomplete
    orange1: Incomplete
    orange2: Incomplete
    orange3: Incomplete
    orange4: Incomplete
    orangered: Incomplete
    orangered1: Incomplete
    orangered2: Incomplete
    orangered3: Incomplete
    orangered4: Incomplete
    orchid: Incomplete
    orchid1: Incomplete
    orchid2: Incomplete
    orchid3: Incomplete
    orchid4: Incomplete
    palegoldenrod: Incomplete
    palegreen: Incomplete
    palegreen1: Incomplete
    palegreen2: Incomplete
    palegreen3: Incomplete
    palegreen4: Incomplete
    paleturquoise: Incomplete
    paleturquoise1: Incomplete
    paleturquoise2: Incomplete
    paleturquoise3: Incomplete
    paleturquoise4: Incomplete
    palevioletred: Incomplete
    palevioletred1: Incomplete
    palevioletred2: Incomplete
    palevioletred3: Incomplete
    palevioletred4: Incomplete
    papayawhip: Incomplete
    peachpuff: Incomplete
    peachpuff1: Incomplete
    peachpuff2: Incomplete
    peachpuff3: Incomplete
    peachpuff4: Incomplete
    peru: Incomplete
    pink: Incomplete
    pink1: Incomplete
    pink2: Incomplete
    pink3: Incomplete
    pink4: Incomplete
    plum: Incomplete
    plum1: Incomplete
    plum2: Incomplete
    plum3: Incomplete
    plum4: Incomplete
    powderblue: Incomplete
    purple: Incomplete
    purple1: Incomplete
    purple2: Incomplete
    purple3: Incomplete
    purple4: Incomplete
    red: Incomplete
    red1: Incomplete
    red2: Incomplete
    red3: Incomplete
    red4: Incomplete
    rosybrown: Incomplete
    rosybrown1: Incomplete
    rosybrown2: Incomplete
    rosybrown3: Incomplete
    rosybrown4: Incomplete
    royalblue: Incomplete
    royalblue1: Incomplete
    royalblue2: Incomplete
    royalblue3: Incomplete
    royalblue4: Incomplete
    saddlebrown: Incomplete
    salmon: Incomplete
    salmon1: Incomplete
    salmon2: Incomplete
    salmon3: Incomplete
    salmon4: Incomplete
    sandybrown: Incomplete
    seagreen: Incomplete
    seagreen1: Incomplete
    seagreen2: Incomplete
    seagreen3: Incomplete
    seagreen4: Incomplete
    seashell: Incomplete
    seashell1: Incomplete
    seashell2: Incomplete
    seashell3: Incomplete
    seashell4: Incomplete
    sienna: Incomplete
    sienna1: Incomplete
    sienna2: Incomplete
    sienna3: Incomplete
    sienna4: Incomplete
    skyblue: Incomplete
    skyblue1: Incomplete
    skyblue2: Incomplete
    skyblue3: Incomplete
    skyblue4: Incomplete
    slateblue: Incomplete
    slateblue1: Incomplete
    slateblue2: Incomplete
    slateblue3: Incomplete
    slateblue4: Incomplete
    slategray: Incomplete
    slategray1: Incomplete
    slategray2: Incomplete
    slategray3: Incomplete
    slategray4: Incomplete
    snow: Incomplete
    snow1: Incomplete
    snow2: Incomplete
    snow3: Incomplete
    snow4: Incomplete
    springgreen: Incomplete
    springgreen1: Incomplete
    springgreen2: Incomplete
    springgreen3: Incomplete
    springgreen4: Incomplete
    steelblue: Incomplete
    steelblue1: Incomplete
    steelblue2: Incomplete
    steelblue3: Incomplete
    steelblue4: Incomplete
    tan: Incomplete
    tan1: Incomplete
    tan2: Incomplete
    tan3: Incomplete
    tan4: Incomplete
    thistle: Incomplete
    thistle1: Incomplete
    thistle2: Incomplete
    thistle3: Incomplete
    thistle4: Incomplete
    tomato: Incomplete
    tomato1: Incomplete
    tomato2: Incomplete
    tomato3: Incomplete
    tomato4: Incomplete
    turquoise: Incomplete
    turquoise1: Incomplete
    turquoise2: Incomplete
    turquoise3: Incomplete
    turquoise4: Incomplete
    violet: Incomplete
    violetred: Incomplete
    violetred1: Incomplete
    violetred2: Incomplete
    violetred3: Incomplete
    violetred4: Incomplete
    wheat: Incomplete
    wheat1: Incomplete
    wheat2: Incomplete
    wheat3: Incomplete
    wheat4: Incomplete
    white: Incomplete
    whitesmoke: Incomplete
    yellow: Incomplete
    yellow1: Incomplete
    yellow2: Incomplete
    yellow3: Incomplete
    yellow4: Incomplete
    yellowgreen: Incomplete
    @staticmethod
    def exists(name): ...
    @staticmethod
    def get(name): ...
