class Version:
    def __init__(self, value) -> None: ...
    @property
    def major(self): ...
    @property
    def minor(self): ...
    @property
    def build(self): ...
    @property
    def version(self): ...
    @property
    def suffix(self): ...
    @property
    def major_minor_string(self): ...
    def is_compatible_with(self, current): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
    def __hash__(self): ...
