from _typeshed import Incomplete
from typing import NamedTuple

class UflAttributeDescription(NamedTuple):
    accessor: Incomplete
    type: Incomplete

class UflType:
    ALLOWED_DIRECT_ATTRIBUTES: Incomplete
    @property
    def parent(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator) -> None: ...
    def is_assignable_from(self, other): ...
    def set_parent(self, parent) -> None: ...
    @property
    def is_immutable(self) -> None: ...
    def is_convertible_to(self, other): ...
    def is_equatable_to(self, other): ...
    def is_comparable_with(self, other): ...
    def is_valid_value(self, value) -> None: ...
    def is_default_value(self, value) -> None: ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
