from ..tree import *
from . import definition as d
from .operators import make_binary_operator_tree as make_binary_operator_tree, make_unary_operator_tree as make_unary_operator_tree

@d.VARIABLE_METADATA_ACCESS.setParseAction
def variable_metadata_access(data): ...
@d.TARGET.setParseAction
def target(data): ...
@d.VARIABLE.setParseAction
def variable(data): ...
@d.NUMBER.setParseAction
def number(data): ...
@d.STRING.setParseAction
def string(data): ...
@d.UNARY.setParseAction
def unary(data): ...
@d.BINARY.setParseAction
def binary(data): ...
@d.ARGUMENTS.setParseAction
def arguments(data): ...
@d.METHOD_ATTRIBUTE_OR_ENUM.setParseAction
def method_attribute_or_enum(data): ...
@d.LAMBDA_EXPRESSION.setParseAction
def lambda_expression(data): ...
