from ..constants import MODEL_NAMESPACE as MODEL_NAMESPACE, MODEL_SCHEMA as MODEL_SCHEMA

class LockedTabsSaver:
    def __init__(self, storage, path) -> None: ...
    def save(self, locked_tabs) -> None: ...
