from ..constants import FRIP2_LOCKED_TABS_FILE as FRIP2_LOCKED_TABS_FILE, FRIP2_MIMETYPE_FILE as FRIP2_MIMETYPE_FILE, FRIP2_PROJECT_FILE as FRIP2_PROJECT_FILE, FRIP2_SOLUTION_FILE as FRIP2_SOLUTION_FILE, FRIP2_VERSION_FILE as FRIP2_VERSION_FILE, MODEL_SAVE_VERSION as MODEL_SAVE_VERSION, SOLUTION_MIME_TYPE as SOLUTION_MIME_TYPE
from .lockedtabssaver import LockedTabsSaver as LockedTabsSaver
from .projectsaver import ProjectSaver as ProjectSaver
from .solutionsaver import SolutionSaver as SolutionSaver

class WholeSolutionSaver:
    def __init__(self, storage, ruler) -> None: ...
    @property
    def solution(self): ...
    @solution.setter
    def solution(self, value) -> None: ...
    @property
    def locked_tabs(self): ...
    def add_locked_tab(self, tab) -> None: ...
    def save(self) -> None: ...
