from typing import (
    Any,
    Iterator,
    Optional,
    Tuple,
    Union,
)
from umlfri2.model.diagram import DiagramValueGenerator
from umlfri2.model.element.elementobject import ElementValueGenerator
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.mutable.list import ListItemValueGenerator
from umlfri2.ufl.objects.mutable.object import UflMutableObject
from umlfri2.ufl.types.base.type import UflType


class UflObjectAttribute:
    def __init__(self, name: str, type: UflType) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def parent(self) -> UflObjectType: ...
    def set_parent(self, parent: UflObjectType) -> None: ...
    @property
    def type(self) -> UflType: ...


class UflObjectType:
    def __init__(self, attributes: Tuple[UflObjectAttribute, Ellipsis]) -> None: ...
    @property
    def attributes(self) -> Iterator[UflObjectAttribute]: ...
    def build_default(
        self,
        generator: Optional[Union[ListItemValueGenerator, ElementValueGenerator, DiagramValueGenerator]]
    ) -> UflObject: ...
    def contains_attribute(self, name: str) -> bool: ...
    def get_attribute(self, name: str) -> UflObjectAttribute: ...
    @property
    def has_attributes(self) -> bool: ...
    def is_default_value(self, value: UflObject) -> bool: ...
    @property
    def is_immutable(self) -> bool: ...
    def is_valid_value(self, value: UflMutableObject) -> bool: ...
    def set_parent(self, parent: Any) -> None: ...
