from .tab import UflDialogTab as UflDialogTab
from _typeshed import Incomplete
from collections.abc import Generator

from typing import (
    Iterator,
    List,
    Optional,
    Union,
)
from umlfri2.metamodel.translation.translation import Translation
from umlfri2.ufl.dialog.columns.check import UflDialogCheckColumn
from umlfri2.ufl.dialog.columns.complex import UflDialogComplexColumn
from umlfri2.ufl.dialog.columns.enum import UflDialogEnumColumn
from umlfri2.ufl.dialog.columns.valued import UflDialogValuedColumn
from umlfri2.ufl.objects.mutable.list import UflMutableList
from umlfri2.ufl.types.structured.list import UflListType
from umlfri2.ufl.types.structured.object import UflObjectAttribute

class UflDialogListTab(UflDialogTab):
    def __init__(
        self,
        attr: Optional[UflObjectAttribute],
        list_type: UflListType
    ) -> None: ...
    def add_column(
        self,
        column: Union[UflDialogEnumColumn, UflDialogComplexColumn, UflDialogValuedColumn, UflDialogCheckColumn]
    ) -> None: ...
    @property
    def columns(self) -> Iterator[str]: ...
    @property
    def rows(self) -> Iterator[List[str]]: ...
    @property
    def can_new(self) -> bool: ...
    def new(self) -> None: ...
    def save(self) -> None: ...
    def discard(self) -> None: ...
    @property
    def should_save(self) -> bool: ...
    @property
    def can_save(self) -> bool: ...
    @property
    def can_delete(self) -> bool: ...
    def delete(self) -> None: ...
    @property
    def can_move_up(self) -> bool: ...
    def move_up(self) -> None: ...
    @property
    def can_move_down(self) -> bool: ...
    def move_down(self) -> None: ...
    @property
    def current_index(self) -> None: ...
    def change_current_index(self, value: None) -> None: ...
    def associate(self, ufl_object: Optional[UflMutableList]) -> None: ...
    def finish(self) -> None: ...
    def translate(self, translation: Translation) -> None: ...
    def tab_deselected(self) -> None: ...
