from _typeshed import Incomplete
from collections.abc import Generator

from typing import (
    Iterator,
    Optional,
    Union,
)
from umlfri2.metamodel.translation.translation import Translation
from umlfri2.ufl.dialog.widgets.text import UflDialogTextWidget
from umlfri2.ufl.dialog.widgets.widget import UflDialogWidget
from umlfri2.ufl.objects.mutable.object import UflMutableObject
from umlfri2.ufl.types.structured.object import UflObjectAttribute

class UflDialogTab:
    def __init__(self, attr: Optional[UflObjectAttribute]) -> None: ...
    @property
    def id(self) -> Optional[str]: ...
    @property
    def tab_index(self) -> int: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def current_object(self) -> Optional[Union[UflMutableObject, str]]: ...
    @property
    def widget_count(self) -> int: ...
    @property
    def first_widget(self) -> UflDialogTextWidget: ...
    @property
    def widgets(self) -> Iterator[UflDialogWidget]: ...
    def add_widget(self, widget: UflDialogWidget) -> None: ...
    def associate(self, ufl_object) -> None: ...
    def finish(self) -> None: ...
    @property
    def has_changes(self) -> bool: ...
    def translate(self, translation: Translation) -> None: ...
