from ..widgets import UflDialogChildWidget as UflDialogChildWidget, UflDialogValuedWidget as UflDialogValuedWidget
from .tab import UflDialogTab as UflDialogTab

from umlfri2.ufl.dialog.widgets.textarea import UflDialogTextAreaWidget

class UflDialogValueTab(UflDialogTab):
    def associate(self, ufl_object) -> None: ...
    def add_widget(self, widget: UflDialogTextAreaWidget) -> None: ...
    @property
    def widget(self) -> UflDialogTextAreaWidget: ...
    def finish(self) -> None: ...
