from .interface import Interface as Interface
from umlfri2.application.events.addon import ActionTriggeredEvent as ActionTriggeredEvent

class IAction(Interface):
    def __init__(self, executor, action) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_enabled(self): ...
    def set_enabled(self, value: bool): ...
    def get_id(self): ...
    def register_triggered(self) -> None: ...
    def deregister_triggered(self) -> None: ...
