from .interface import Interface as Interface

class IConnectionType(Interface):
    def __init__(self, executor, connection) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_name(self): ...
