from .helpers.uflobject import UflObjectApiHelper as UflObjectApiHelper
from .interface import Interface as Interface
from _typeshed import Incomplete
from collections.abc import Generator

class IConnectionObject(Interface):
    def __init__(self, executor, connection) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    @property
    def connection_object(self): ...
    def get_destination(self): ...
    def get_connected_object(self, obj: object): ...
    def get_source(self): ...
    def get_type(self): ...
    def get_value(self, path: str): ...
    def get_values(self) -> Generator[Incomplete, Incomplete]: ...
    def get_visuals(self) -> Generator[Incomplete]: ...
