from .interface import Interface as Interface

class IConnectionLabel(Interface):
    def __init__(self, executor, label) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_center(self): ...
    def get_connection(self): ...
    def get_diagram(self): ...
    def get_position(self): ...
    def get_size(self): ...
