from .interface import Interface as Interface
from _typeshed import Incomplete
from collections.abc import Generator

class IDiagramType(Interface):
    def __init__(self, executor, diagram) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_connections(self) -> Generator[Incomplete]: ...
    def get_elements(self) -> Generator[Incomplete]: ...
    def get_name(self): ...
