from .helpers.uflobject import UflObjectApiHelper as UflObjectApiHelper
from .interface import Interface as Interface
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.model.element import ElementVisual as ElementVisual

class IDiagram(Interface):
    def __init__(self, executor, diagram) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    @property
    def diagram(self): ...
    def get_connections(self) -> Generator[Incomplete]: ...
    def get_elements(self) -> Generator[Incomplete]: ...
    def get_connection(self, obj: object): ...
    def get_element(self, obj: object): ...
    def get_name(self): ...
    def get_parent(self): ...
    def get_project(self): ...
    def get_selection(self) -> object: ...
    def get_type(self): ...
    def get_value(self, path: str): ...
    def get_values(self) -> Generator[Incomplete, Incomplete]: ...
