from .interface import Interface as Interface
from _typeshed import Incomplete
from collections.abc import Generator

class IElementVisual(Interface):
    def __init__(self, executor, element) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_center(self): ...
    def get_connections(self) -> Generator[Incomplete]: ...
    def get_diagram(self): ...
    def get_minimal_size(self): ...
    def get_object(self): ...
    def get_position(self): ...
    def get_size(self): ...
