from .interface import Interface as Interface
from .partnotfound import PartNotFound as PartNotFound
from _typeshed import Incomplete
from collections.abc import Generator

class IMetamodel(Interface):
    def __init__(self, executor, metamodel) -> None: ...
    @property
    def id(self): ...
    @property
    def api_name(self): ...
    def get_connection(self, name: str): ...
    def get_connections(self) -> Generator[Incomplete]: ...
    def get_diagram(self, name: str): ...
    def get_diagrams(self) -> Generator[Incomplete]: ...
    def get_element(self, name: str): ...
    def get_elements(self) -> Generator[Incomplete]: ...
    def get_identifier(self): ...
    def get_version(self): ...
