from .actions import AddOnStarter as AddOnStarter, AddOnStopper as AddOnStopper, AddOnUninstaller as AddOnUninstaller
from .state import AddOnState as AddOnState
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.events.addon import AddOnStateChangedEvent as AddOnStateChangedEvent

class AddOn:
    def __init__(self, application, storage_reference, identifier, name, version, author, homepage, license, icon, description, requirements, provisions, metamodel, gui_injection, patch_plugin, plugin, system_addon) -> None: ...
    @property
    def identifier(self): ...
    @property
    def name(self): ...
    @property
    def version(self): ...
    @property
    def author(self): ...
    @property
    def homepage(self): ...
    @property
    def license(self): ...
    @property
    def icon(self): ...
    @property
    def description(self): ...
    @property
    def requirements(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def provisions(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def metamodel(self): ...
    @property
    def is_system_addon(self): ...
    @property
    def application(self): ...
    def compile(self) -> None: ...
    @property
    def state(self): ...
    @property
    def gui_injection(self): ...
    @property
    def storage_reference(self): ...
    def start(self): ...
    def stop(self): ...
    def uninstall(self): ...
