from .actions import AddOnStarter as AddOnStarter, AddOnStopper as AddOnStopper
from .state import AddOnState as AddOnState
from umlfri2.application.events.addon import AddOnInstalledEvent as AddOnInstalledEvent, AddOnUninstalledEvent as AddOnUninstalledEvent, AddOnUpdatedEvent as AddOnUpdatedEvent
from umlfri2.constants.paths import ADDONS as ADDONS, LOCAL_ADDONS as LOCAL_ADDONS
from umlfri2.datalayer.loaders import AddOnListLoader as AddOnListLoader
from umlfri2.datalayer.storages import DirectoryStorage as DirectoryStorage

class AddOnManager:
    def __init__(self, application) -> None: ...
    def load_addons(self) -> None: ...
    def install_addon(self, storage, online_addon_version): ...
    def install_addon_update(self, storage, online_addon_version): ...
    def uninstall_addon(self, addon) -> None: ...
    def get_addon(self, identifier): ...
    def start_all(self): ...
    def stop_all(self): ...
    def __iter__(self): ...
