from ..base import Command as Command, CommandNotDone as CommandNotDone
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.events.diagram import ConnectionShownEvent as ConnectionShownEvent
from umlfri2.types.geometry import Vector as Vector

class ShowConnectionCommand(Command):
    def __init__(self, diagram, connection_object) -> None: ...
    @property
    def description(self): ...
    @property
    def connection_visual(self): ...
    @property
    def connection_object(self): ...
    def get_updates(self) -> Generator[Incomplete]: ...
