from .communication import PluginExecutor as PluginExecutor
from .starters import STARTER_LIST as STARTER_LIST

class Plugin:
    def __init__(self, addon_path, starter, path) -> None: ...
    @property
    def is_running(self): ...
    def start(self) -> None: ...
    @property
    def running(self): ...
    def stop(self) -> None: ...
    def terminate(self) -> None: ...
    def kill(self) -> None: ...
