from .patch import UflPatch as UflPatch
from umlfri2.ufl.objects.immutable.object import UflObject

class UflListPatch(UflPatch):
    class ItemAdded:
        def __init__(self, index: int, new_value: UflObject) -> None: ...
        @property
        def index(self) -> int: ...
        @property
        def new_value(self) -> UflObject: ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
    class ItemRemoved:
        def __init__(self, index, old_value) -> None: ...
        @property
        def index(self): ...
        @property
        def old_value(self): ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
    class ItemMoved:
        def __init__(self, old_index, new_index, value) -> None: ...
        @property
        def old_index(self): ...
        @property
        def new_index(self): ...
        @property
        def value(self): ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
    class ItemPatch:
        def __init__(self, index, patch) -> None: ...
        @property
        def index(self): ...
        @property
        def patch(self): ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
