from .patch import UflPatch as UflPatch
from typing import Union
from umlfri2.types.color import Color
from umlfri2.types.font import Font
from umlfri2.ufl.objects.patch.list import UflListPatch

class UflObjectPatch(UflPatch):
    class AttributeChanged:
        def __init__(self, name: str, old_value: Union[str, Font, Color, bool], new_value: Union[str, Font, Color, bool]) -> None: ...
        @property
        def name(self) -> str: ...
        @property
        def old_value(self): ...
        @property
        def new_value(self) -> Union[bool, Font, Color, str]: ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
    class AttributePatch:
        def __init__(self, name: str, patch: Union[UflListPatch, UflObjectPatch]) -> None: ...
        @property
        def name(self) -> str: ...
        @property
        def patch(self) -> Union[UflListPatch, UflObjectPatch]: ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
