from ..base import Event as Event
from umlfri2.model.connection.connectionobject import ConnectionObject


class ConnectionChangedEvent(Event):
    def __init__(self, connection: ConnectionObject) -> None: ...
    @property
    def connection(self): ...
    def get_opposite(self): ...
