from ..base import Event as Event
from typing import Optional
from umlfri2.model.diagram import Diagram


class DiagramCreatedEvent(Event):
    def __init__(self, diagram: Diagram, index: None = None, indirect: bool = False) -> None: ...
    @property
    def diagram(self) -> Diagram: ...
    @property
    def index(self) -> None: ...
    @property
    def indirect(self) -> bool: ...
    def get_opposite(self): ...
