from ..base import Event as Event
from umlfri2.model.project import Project


class ProjectChangedEvent(Event):
    def __init__(self, project: Project) -> None: ...
    @property
    def project(self) -> Project: ...
    def get_opposite(self): ...
