from .snippet import Snippet as Snippet
from umlfri2.ufl.types.complex import UflColorType as UflColorType, UflFontType as UflFontType, UflImageType as UflImageType, UflProportionType as UflProportionType
from umlfri2.ufl.types.enum import UflFlagsType as UflFlagsType
from umlfri2.ufl.types.structured import UflListType as UflListType, UflNullableType as UflNullableType, UflObjectType as UflObjectType

class SnippetBuilder:
    def __init__(self, project) -> None: ...
    def add_element(self, ruler, visual): ...
    def add_connection(self, ruler, visual): ...
    def build(self): ...
