from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.types.geometry import Point as Point, Size as Size
from umlfri2.ufl.types.complex import UflColorType as UflColorType, UflFontType as UflFontType, UflImageType as UflImageType, UflProportionType as UflProportionType
from umlfri2.ufl.types.structured import UflListType as UflListType, UflObjectType as UflObjectType

class Snippet:
    def __init__(self, data) -> None: ...
    def serialize(self): ...
    @staticmethod
    def deserialize(data): ...
    @property
    def empty(self): ...
    def can_be_pasted_to(self, diagram): ...
    def paste_to(self, ruler, diagram) -> Generator[Incomplete]: ...
    def can_be_duplicated_to(self, diagram): ...
    def duplicate_to(self, ruler, diagram) -> Generator[Incomplete]: ...
