from typing import Union
from umlfri2.metamodel.translation.translation import Translation
from umlfri2.ufl.objects.mutable.object import UflMutableObject
from umlfri2.ufl.types.structured.object import UflObjectAttribute


class UflDialogColumn:
    def __init__(self, attr: UflObjectAttribute) -> None: ...
    def _get_real_value(self, object: UflMutableObject) -> Union[str, bool]: ...
    @property
    def title(self) -> str: ...
    def translate(self, translation: Translation) -> None: ...
