from umlfri2.application.addon.local.addon import AddOn


class Plugin:
    def __init__(self, addon_path: str, starter: str, path: str) -> None: ...
    def _set_addon(self, addon: AddOn) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
