from typing import Iterator
from umlfri2.application.addon.online.addon import OnlineAddOn
from umlfri2.application.application import Application


class OnlineAddOnManager:
    def __init__(self, application: Application) -> None: ...
    def __iter__(self) -> Iterator[OnlineAddOn]: ...
    def update(self) -> None: ...
    @property
    def updated_addons(self) -> None: ...
