from PyQt5.QtWidgets import QDialog
from umlfri2.application import Application as Application
from umlfri2.application.commands.model import ChangeProjectNameCommand as ChangeProjectNameCommand

class ProjectPropertiesDialog(QDialog):
    def __init__(self, main_window, project) -> None: ...
    def sizeHint(self): ...
    @property
    def project_name(self): ...
    @staticmethod
    def open_for(main_window, project) -> None: ...
