from PyQt5.QtWidgets import QTextEdit
from _typeshed import Incomplete

class EditorWidget(QTextEdit):
    text_update: Incomplete
    def __init__(self) -> None: ...
    def setPlainText(self, text) -> None: ...
    def focusOutEvent(self, event) -> None: ...
