from .tabletab import TableTab as TableTab
from umlfri2.application import Application as Application
from umlfri2.application.commands.model import ChangeProjectNameCommand as ChangeProjectNameCommand
from umlfri2.qtgui.properties.widget.selectionchangingwidgets import QSelectionChangingLineEdit as QSelectionChangingLineEdit

class ProjectTab(TableTab):
    def __init__(self, project) -> None: ...
    def reload_texts(self) -> None: ...
    def reload_data(self) -> None: ...
    @property
    def label(self): ...
