from PyQt5.QtWidgets import QCheckBox, QComboBox, QDoubleSpinBox, QLineEdit, QPushButton, QSpinBox
from _typeshed import Incomplete

class QSelectionChangingCheckBox(QCheckBox):
    def __init__(self, table, row) -> None: ...
    def focusInEvent(self, event) -> None: ...

class QSelectionChangingPushButton(QPushButton):
    def __init__(self, table, row) -> None: ...
    def focusInEvent(self, event) -> None: ...

class QSelectionChangingComboBox(QComboBox):
    lostFocus: Incomplete
    def __init__(self, table, row) -> None: ...
    def focusInEvent(self, event) -> None: ...
    def focusOutEvent(self, event) -> None: ...

class QSelectionChangingSpinBox(QSpinBox):
    def __init__(self, table, row) -> None: ...
    def focusInEvent(self, event) -> None: ...

class QSelectionChangingDoubleSpinBox(QDoubleSpinBox):
    def __init__(self, table, row) -> None: ...
    def focusInEvent(self, event) -> None: ...

class QSelectionChangingLineEdit(QLineEdit):
    lostFocus: Incomplete
    def __init__(self, table, row) -> None: ...
    def focusInEvent(self, event) -> None: ...
    def focusOutEvent(self, event) -> None: ...
