from PyQt5.QtWidgets import QTableWidget

class TableTab(QTableWidget):
    def __init__(self) -> None: ...
    def reload_texts(self) -> None: ...
    def reload_data(self) -> None: ...
    def content_updated(self) -> None: ...
    @property
    def label(self) -> None: ...
