from .editorwidget import EditorWidget as EditorWidget

class TextTab(EditorWidget):
    def __init__(self, widget, tab) -> None: ...
    @property
    def label(self): ...
    def reload_data(self) -> None: ...
    def reload_texts(self) -> None: ...
