from .nullable import STANDARD_NULLABLE_MACROS
from .iterator import STANDARD_ITERATOR_MACROS
from .other import STANDARD_OTHER_MACROS

STANDARD_MACROS = STANDARD_NULLABLE_MACROS + STANDARD_ITERATOR_MACROS + STANDARD_OTHER_MACROS
