from umlfri2.ufl.types.enum import UflDefinedEnumType as UflDefinedEnumType
from umlfri2.ufl.types.structured import UflNullableType as UflNullableType

class TypeContext:
    def __init__(self, definitions) -> None: ...
    def get_variable_type(self, name): ...
    def as_dict(self, prefix=None): ...
    def resolve_defined_enum(self, type): ...
    def set_variable_type(self, name, type): ...
