from ..parser import parse_ufl as parse_ufl
from .compilingvisitor import UflCompilingVisitor as UflCompilingVisitor
from .typingvisitor import UflTypingVisitor as UflTypingVisitor
from _typeshed import Incomplete
from collections.abc import Generator

class CompiledUflExpression:
    def __init__(self, expression, expected_type, variables) -> None: ...
    @property
    def source(self): ...
    @property
    def parameters(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def compiled_source(self): ...
    @property
    def compiled_function(self): ...
    @property
    def type(self): ...
