from ..tree import *
from ...compilerhelpers.automultiresolver import resolve_multi_type as resolve_multi_type
from ...macro.standard import STANDARD_MACROS as STANDARD_MACROS
from ...types.basic import UflBoolType as UflBoolType, UflDecimalType as UflDecimalType, UflIntegerType as UflIntegerType, UflNumberType as UflNumberType, UflStringType as UflStringType
from ...types.complex import UflColorType as UflColorType, UflFontType as UflFontType
from ...types.enum import UflTypedEnumType as UflTypedEnumType
from ...types.structured import UflIterableType as UflIterableType, UflNullableType as UflNullableType, UflObjectType as UflObjectType, UflVariableWithMetadataType as UflVariableWithMetadataType
from ..tree.visitor import UflVisitor as UflVisitor
from .macroargumenttypeprovider import MacroArgumentTypeProvider as MacroArgumentTypeProvider
from umlfri2.types.color import Colors as Colors
from umlfri2.types.enums import ALL_ENUMS as ALL_ENUMS
from umlfri2.types.font import Fonts as Fonts

class UflTypingVisitor(UflVisitor):
    def __init__(self, params, expected_type) -> None: ...
    def visit_attribute_access(self, node): ...
    def visit_enum(self, node): ...
    def visit_macro_invoke(self, node): ...
    def visit_technical_variable(self, node) -> None: ...
    def visit_variable(self, node): ...
    def visit_variable_definition(self, node): ...
    def visit_binary(self, node): ...
    def visit_unary(self, node): ...
    def visit_literal(self, node): ...
    def visit_variable_metadata_access(self, node): ...
    def visit_object_metadata_access(self, node): ...
    def visit_unpack(self, node) -> None: ...
    def visit_expression(self, node): ...
    def visit_lambda_expression(self, node) -> None: ...
    def visit_cast(self, node) -> None: ...
    def create_for_lambda(self, lambda_args): ...
