class VariableNameRegister:
    def __init__(self, user_variable_prefix) -> None: ...
    def register_temp_variable(self): ...
    def register_function(self, function): ...
    def register_class(self, class_): ...
    def build_globals(self): ...
