from enum import Enum

class OnlineAddOnArch(Enum):
    processor_32 = 1
    processor_64 = 2

class OnlineAddOnHash(Enum):
    sha256 = ...
    def __init__(self, fnc) -> None: ...
    def compute(self, bytes): ...

class OnlineAddOnLocation:
    def __init__(self, url, hash, hash_type, arch=None, os=None) -> None: ...
    @property
    def url(self): ...
    @property
    def is_valid(self): ...
    def download(self): ...
