from PyQt5.QtWidgets import QWidget
from umlfri2.application import Application as Application
from umlfri2.types.version import Version as Version

class SettingsDialogUpdates(QWidget):
    def __init__(self, dialog) -> None: ...
    @staticmethod
    def get_name(): ...
    def apply_settings(self) -> None: ...
    def reload_texts(self) -> None: ...
