from typing import (
    Iterator,
    Tuple,
    Union,
)
from umlfri2.types.geometry.point import Point


class Line:
    def __init__(self, x1: Union[float, int], y1: Union[float, int], x2: int, y2: int) -> None: ...
    @property
    def first(self) -> Point: ...
    @staticmethod
    def from_point_point(
        p1: Point,
        p2: Point
    ) -> Line: ...
    def get_abc(self) -> Union[Tuple[int, int, int], Tuple[int, float, float], Tuple[int, int, float]]: ...
    def get_distance_to(self, other: Point) -> float: ...
    def get_nearest_point_to(self, other: Point) -> Point: ...
    def intersect(self, other: Line) -> Iterator[Point]: ...
    @property
    def second(self) -> Point: ...
