from typing import Union
from umlfri2.types.geometry.size import Size
from umlfri2.types.geometry.transformation import Transformation
from umlfri2.types.geometry.vector import Vector


class Point:
    def __add__(self, other: Vector) -> Point: ...
    def __eq__(self, other: Point) -> bool: ...
    def __hash__(self) -> int: ...
    def __init__(self, x: Union[float, int], y: Union[float, int]) -> None: ...
    def __sub__(
        self,
        other: Union[Point, Vector]
    ) -> Union[Point, Vector]: ...
    def as_size(self) -> Size: ...
    def as_vector(self) -> Vector: ...
    @staticmethod
    def parse(param: str) -> Point: ...
    def transform(
        self,
        matrix: Transformation
    ) -> Point: ...
    @property
    def x(self) -> Union[float, int]: ...
    @property
    def y(self) -> Union[float, int]: ...
