from typing import (
    Iterator,
    List,
)
from umlfri2.types.geometry.line import Line
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.size import Size
from umlfri2.types.geometry.vector import Vector


class Rectangle:
    def __add__(self, other: Vector) -> Rectangle: ...
    def __eq__(self, other: Rectangle) -> bool: ...
    def __init__(self, x: int, y: int, width: int, height: int) -> None: ...
    @property
    def all_lines(self) -> Iterator[Line]: ...
    @property
    def bottom_center(self) -> Point: ...
    @property
    def bottom_left(self) -> Point: ...
    @property
    def bottom_right(self) -> Point: ...
    @property
    def center(self) -> Point: ...
    @staticmethod
    def combine_bounds(
        rectangles: List[Rectangle]
    ) -> Rectangle: ...
    def contains(self, point: Point) -> bool: ...
    @staticmethod
    def from_point_point(
        p1: Point,
        p2: Point
    ) -> Rectangle: ...
    @staticmethod
    def from_point_size(
        point: Point,
        size: Size
    ) -> Rectangle: ...
    @property
    def height(self) -> int: ...
    def intersect(self, other: Line) -> Iterator[Point]: ...
    def is_overlapping(self, other: Rectangle) -> bool: ...
    @property
    def left_center(self) -> Point: ...
    def normalize(self) -> Rectangle: ...
    @property
    def right_center(self) -> Point: ...
    @property
    def size(self) -> Size: ...
    @property
    def top_center(self) -> Point: ...
    @property
    def top_left(self) -> Point: ...
    @property
    def top_right(self) -> Point: ...
    @property
    def width(self) -> int: ...
    @property
    def x1(self) -> int: ...
    @property
    def x2(self) -> int: ...
    @property
    def y1(self) -> int: ...
    @property
    def y2(self) -> int: ...
