from typing import Union
from umlfri2.types.geometry.vector import Vector


class Size:
    def __init__(self, width: Union[float, int], height: Union[float, int]) -> None: ...
    def __mul__(self, other: float) -> Size: ...
    def as_vector(self) -> Vector: ...
    @property
    def height(self) -> Union[float, int]: ...
    @property
    def width(self) -> Union[float, int]: ...
