from typing import Union


class Vector:
    def __bool__(self) -> bool: ...
    def __init__(self, x: Union[float, int], y: Union[float, int]) -> None: ...
    def __mul__(self, other: float) -> Vector: ...
    def __neg__(self) -> Vector: ...
    def __truediv__(self, other: int) -> Vector: ...
    @property
    def angle(self) -> float: ...
    @staticmethod
    def from_angle_length(angle: float, length: Union[float, int]) -> Vector: ...
    @property
    def length(self) -> float: ...
    @property
    def x(self) -> Union[float, int]: ...
    @property
    def y(self) -> Union[float, int]: ...
