from _typeshed import Incomplete
from collections.abc import Generator

class SnappedRectangle:
    def __init__(self, rectangle, horizontal_indicators=(), vertical_indicators=()) -> None: ...
    @property
    def rectangle(self): ...
    @property
    def snapped_horizontally(self): ...
    @property
    def snapped_vertically(self): ...
    @property
    def horizontal_indicators(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def vertical_indicators(self) -> Generator[Incomplete, Incomplete]: ...
