from .initialized import InitializedSnapping as InitializedSnapping

class Snapping:
    MAXIMAL_DISTANCE: int
    def __init__(self, application, elements, connections, selected_elements) -> None: ...
    def ignore_point(self, connection, index): ...
    def ignore_selection(self): ...
    def build(self): ...
