from ..interfaces import IApplication as IApplication, Interface as Interface, InterfaceException as InterfaceException

class PluginExecutor:
    def __init__(self, addon, channel, thread_manager) -> None: ...
    @property
    def addon(self): ...
    def fire_event(self, target, selector, **arguments) -> None: ...
    @property
    def running(self): ...
    def start(self) -> None: ...
    def send_stop(self) -> None: ...
    def object_removed(self, object) -> None: ...
