from .filechannel import FileChannel as FileChannel

class PipeChannel(FileChannel):
    def __init__(self) -> None: ...
    @property
    def child_reader_handle(self): ...
    @property
    def child_writer_handle(self): ...
    def close_child_descriptors(self) -> None: ...
