from ..base import Event as Event

class MetamodelConfigChangedEvent(Event):
    def __init__(self, metamodel, patch) -> None: ...
    @property
    def metamodel(self): ...
    @property
    def patch(self): ...
    def get_opposite(self): ...
