from typing import (
    Callable,
    Tuple,
    Union,
)
from umlfri2.application.application import Application
from umlfri2.application.drawingarea.actions.addelement import AddElementAction
from umlfri2.application.drawingarea.actions.addtypedconnection import AddTypedConnectionAction
from umlfri2.application.drawingarea.drawingarea import DrawingArea
from umlfri2.application.drawingarea.drawingareacursor import DrawingAreaCursor
from umlfri2.application.drawingarea.snapping.snapping import Snapping
from umlfri2.types.geometry.point import Point


class Action:
    def __init__(self) -> None: ...
    def _finish(self) -> None: ...
    def after_finish(
        self,
        callback: Callable
    ) -> Union[AddTypedConnectionAction, AddElementAction]: ...
    @property
    def application(self) -> Application: ...
    def associate(
        self,
        application: Application,
        drawing_area: DrawingArea
    ) -> None: ...
    @property
    def box(self) -> None: ...
    @property
    def cursor(self) -> DrawingAreaCursor: ...
    @property
    def drawing_area(self) -> DrawingArea: ...
    @property
    def finished(self) -> bool: ...
    @property
    def horizontal_snapping_indicators(self) -> Tuple[()]: ...
    @property
    def menu_to_show(self) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    @property
    def path(self) -> None: ...
    def snap_to(self, snapping: Snapping) -> None: ...
    @property
    def vertical_snapping_indicators(self) -> Tuple[()]: ...
