from typing import (
    Iterator,
    Optional,
)
from umlfri2.application.drawingarea.snapping.snapping import Snapping
from umlfri2.types.geometry.path import Path
from umlfri2.types.geometry.point import Point


class AddConnectionAction:
    def __init__(self) -> None: ...
    @property
    def horizontal_snapping_indicators(self) -> Iterator[Point]: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
    @property
    def path(self) -> Optional[Path]: ...
    def snap_to(self, snapping: Snapping) -> None: ...
    @property
    def vertical_snapping_indicators(self) -> Iterator[Point]: ...
