from umlfri2.types.geometry.point import Point


class AddElementAction:
    def __init__(self, type: str) -> None: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
