from typing import Iterator
from umlfri2.application.drawingarea.drawingareacursor import DrawingAreaCursor
from umlfri2.application.drawingarea.snapping.snapping import Snapping
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.rectangle import Rectangle


class MoveSelectionAction:
    def __init__(self) -> None: ...
    @property
    def box(self) -> Rectangle: ...
    @property
    def cursor(self) -> DrawingAreaCursor: ...
    @property
    def horizontal_snapping_indicators(self) -> Iterator[Point]: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
    def snap_to(self, snapping: Snapping) -> None: ...
    @property
    def vertical_snapping_indicators(self) -> Iterator[Point]: ...
