from umlfri2.application.drawingarea.drawingareacursor import DrawingAreaCursor
from umlfri2.model.connection.connectionvisual import ConnectionVisual
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.rectangle import Rectangle


class MoveConnectionLabelAction:
    def __init__(self, connection: ConnectionVisual, id: str) -> None: ...
    @property
    def box(self) -> Rectangle: ...
    @property
    def cursor(self) -> DrawingAreaCursor: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
