from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.rectangle import Rectangle


class SelectManyAction:
    @property
    def box(self) -> Rectangle: ...
    def mouse_down(self, point: Point) -> None: ...
    def mouse_move(self, point: Point) -> None: ...
    def mouse_up(self) -> None: ...
