from PyQt5.QtGui import (
    QCloseEvent,
    QDragEnterEvent,
)
from PyQt5.QtWidgets import QAction
from typing import Iterator
from umlfri2.application.recentfile import RecentFile


class UmlFriMainWindow:
    def __init__(self) -> None: ...
    def closeEvent(self, event: QCloseEvent) -> None: ...
    def dragEnterEvent(self, event: QDragEnterEvent) -> None: ...
    def get_dock_actions(self) -> Iterator[QAction]: ...
    def get_toolbar_actions(self) -> Iterator[QAction]: ...
    def new_project(self) -> None: ...
    def open_recent_file(self, recent_file: RecentFile) -> None: ...
    def save_solution(self) -> bool: ...
    def save_solution_as(self) -> bool: ...
