from .mutable import UflMutable as UflMutable
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.ufl.objects.patch import UflObjectPatch as UflObjectPatch

class UflMutableObject(UflMutable):
    def __init__(self, type, attributes) -> None: ...
    @property
    def type(self): ...
    def __eq__(self, other): ...
    def get_values(self) -> Generator[Incomplete]: ...
    def get_value(self, name): ...
    def set_value(self, name, value) -> None: ...
    def make_immutable(self): ...
    def make_patch(self): ...
    def copy(self): ...
