from ..cache import ModelTemporaryDataCache as ModelTemporaryDataCache
from .connectionlabel import ConnectionLabel as ConnectionLabel
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.types.geometry import Line as Line, Point as Point, Rectangle as Rectangle

class ConnectionVisual:
    MAXIMAL_CLICKABLE_DISTANCE: int
    def __init__(self, diagram, object, source, destination) -> None: ...
    @property
    def cache(self): ...
    @property
    def object(self): ...
    @property
    def source(self): ...
    @property
    def destination(self): ...
    def get_other_end(self, one_end): ...
    @property
    def diagram(self): ...
    def get_points(self, ruler, source_and_end: bool = True, element_centers: bool = False) -> Generator[Incomplete, Incomplete]: ...
    @property
    def number_of_points_on_line(self): ...
    @property
    def is_identity(self): ...
    def get_labels(self) -> Generator[Incomplete, Incomplete]: ...
    def get_label(self, id): ...
    def add_point(self, ruler, index, point) -> None: ...
    def move_point(self, ruler, index, point) -> None: ...
    def remove_point(self, ruler, index) -> None: ...
    def draw(self, canvas) -> None: ...
    def is_at_position(self, ruler, position): ...
    def get_point(self, ruler, id): ...
    def get_bounds(self, ruler): ...
