class Canvas:
    def translate(self, delta) -> None: ...
    def zoom(self, zoom) -> None: ...
    def draw_ellipse(self, rectangle, fg=None, bg=None, line_width=None, line_style=None) -> None: ...
    def draw_line(self, start, end, fg, line_width=None, line_style=None) -> None: ...
    def draw_path(self, path, fg=None, bg=None, line_width=None, line_style=None) -> None: ...
    def draw_rectangle(self, rectangle, fg=None, bg=None, line_width=None, line_style=None) -> None: ...
    def draw_text(self, pos, text, font, fg) -> None: ...
    def draw_image(self, pos, image) -> None: ...
    def clear(self, color=None) -> None: ...
    def get_ruler(self) -> None: ...
