from .basic import UflBoolType as UflBoolType, UflDecimalType as UflDecimalType, UflIntegerType as UflIntegerType, UflNumberType as UflNumberType, UflStringType as UflStringType
from .complex import UflColorType as UflColorType, UflFontType as UflFontType, UflImageType as UflImageType, UflProportionType as UflProportionType
from .enum import UflStringEnumType as UflStringEnumType, UflStringFlagsType as UflStringFlagsType, UflTypedEnumType as UflTypedEnumType
from .generic import UflAnyType as UflAnyType
from .structured import UflIterableType as UflIterableType, UflListType as UflListType, UflNullableType as UflNullableType, UflObjectType as UflObjectType
from umlfri2.types.enums import ALL_ENUMS as ALL_ENUMS

class UflTypeParserForName:
    def __init__(self, abstract, inner_type, outer_type) -> None: ...
    @property
    def can_have_possibilities(self): ...
    @property
    def can_have_template(self): ...
    @property
    def can_have_attributes(self): ...
    def set_default_value(self, value) -> None: ...
    def set_default_value_as_string(self, value) -> None: ...
    def set_possibilities(self, possibilities) -> None: ...
    def set_attributes(self, attributes) -> None: ...
    def set_template(self, template) -> None: ...
    def finish(self): ...

class UflTypeParser:
    def __init__(self, abstract: bool = False) -> None: ...
    def parse(self, type_name): ...
