from PyQt5.QtCore import QSize
from PyQt5.QtGui import QPaintEvent
from umlfri2.qtgui.mainwindow.tabs.startpageframeaction import StartPageFrameAction


class StartPageFrame:
    def __init__(self) -> None: ...
    def add_frame_action(self) -> StartPageFrameAction: ...
    def clear(self) -> None: ...
    def paintEvent(self, event: QPaintEvent) -> None: ...
    def sizeHint(self) -> QSize: ...
