from PyQt5.QtGui import QMouseEvent


class MiddleClosableTabBar:
    def __init__(self) -> None: ...
    def mousePressEvent(self, event: QMouseEvent) -> None: ...
    def mouseReleaseEvent(self, event: QMouseEvent) -> None: ...
