from enum import Enum

class AddOnDependencyType(Enum):
    starter = 1
    interface = 2

class AddOnDependency:
    def __init__(self, type, id, version=None) -> None: ...
    @property
    def type(self): ...
    @property
    def id(self): ...
    @property
    def version(self): ...
    def __hash__(self): ...
    def __eq__(self, other): ...
