from .local import AddOnManager as AddOnManager
from .online import OnlineAddOnManager as OnlineAddOnManager

class AddOnList:
    def __init__(self, application) -> None: ...
    def init(self) -> None: ...
    @property
    def local(self): ...
    @property
    def online(self): ...
