from .commandnotdone import CommandNotDone as CommandNotDone

class Command:
    @property
    def has_error(self): ...
    @property
    def description(self) -> None: ...
    def do(self, ruler) -> None: ...
    def undo(self, ruler) -> None: ...
    def redo(self, ruler) -> None: ...
    def get_updates(self): ...
