from .commandnotdone import CommandNotDone as CommandNotDone
from typing import Optional
from umlfri2.qtgui.rendering.qtruler import QTRuler


class Command:
    @property
    def has_error(self) -> Optional[bool]: ...
    @property
    def description(self) -> None: ...
    def do(self, ruler: QTRuler) -> None: ...
    def undo(self, ruler: QTRuler) -> None: ...
    def redo(self, ruler: QTRuler) -> None: ...
    def get_updates(self): ...
