from umlfri2.ufl.types.enum import UflFlagsType as UflFlagsType
from umlfri2.ufl.types.structured import UflListType as UflListType, UflObjectType as UflObjectType

def check_any(type, data): ...
def check_object(type, data): ...
def check_list(type, data): ...
def check_flags(type, data): ...
