from .checkdata import check_any as check_any
from _typeshed import Incomplete
from collections.abc import Generator

class ElementTemplate:
    def __init__(self, type, data, children, id=None) -> None: ...
    @property
    def id(self): ...
    @property
    def type(self): ...
    @property
    def data(self): ...
    @property
    def children(self) -> Generator[Incomplete, Incomplete]: ...
