from ..base.type import UflType as UflType
from _typeshed import Incomplete
from collections.abc import Generator

class UflLambdaType(UflType):
    def __init__(self, parameter_types, return_type) -> None: ...
    @property
    def parameter_count(self): ...
    @property
    def parameter_types(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def return_type(self): ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
