from umlfri2.ufl.context import Context as Context

class ConnectionType:
    def __init__(self, id, icon, ufl_type, appearance, labels) -> None: ...
    @property
    def metamodel(self): ...
    @property
    def id(self): ...
    @property
    def icon(self): ...
    @property
    def ufl_type(self): ...
    @property
    def labels(self): ...
    def get_label(self, id): ...
    def compile(self, type_context) -> None: ...
    def create_appearance_object(self, connection, ruler): ...
