from _typeshed import Incomplete
from collections.abc import Generator
from typing import NamedTuple
from umlfri2.ufl.context import Context as Context
from umlfri2.ufl.types.basic import UflStringType as UflStringType
from umlfri2.ufl.types.complex import UflImageType as UflImageType
from umlfri2.ufl.types.generic import UflAnyType as UflAnyType
from umlfri2.ufl.types.structured import UflIterableType as UflIterableType, UflVariableWithMetadataType as UflVariableWithMetadataType

class ElementAccessDepth(NamedTuple):
    parent: Incomplete
    child: Incomplete

class NodeMetadata:
    def __init__(self, element, node_access_depth) -> None: ...
    @property
    def children(self) -> Generator[Incomplete]: ...
    @property
    def icon(self): ...
    @property
    def label(self): ...
    @property
    def value(self): ...
    @staticmethod
    def build_node_metadata_types(element_type=None): ...

class ElementType:
    def __init__(self, id, icon, ufl_type, display_name, appearance, default_action, node_access_depth, allow_direct_add) -> None: ...
    @property
    def metamodel(self): ...
    @property
    def id(self): ...
    @property
    def icon(self): ...
    @property
    def ufl_type(self): ...
    @property
    def default_action(self): ...
    @property
    def node_access_depth(self): ...
    @property
    def allow_direct_add(self): ...
    def compile(self, type_context) -> None: ...
    def create_appearance_object(self, element, ruler): ...
    def get_display_name(self, element): ...
