from .translation import TranslationList as TranslationList
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.ufl.context import TypeContext as TypeContext
from umlfri2.ufl.types.structured import UflObjectType as UflObjectType

class Metamodel:
    def __init__(self, diagrams, elements, connections, templates, definitions, translations, config) -> None: ...
    @property
    def addon(self): ...
    @property
    def diagram_types(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def element_types(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def connection_types(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def templates(self) -> Generator[Incomplete, Incomplete]: ...
    def get_element_type(self, name): ...
    def get_diagram_type(self, name): ...
    def get_connection_type(self, name): ...
    def get_translation(self, language): ...
    @property
    def config_structure(self): ...
    @property
    def has_config(self): ...
    def compile(self) -> None: ...
