from PyQt5.QtWidgets import QComboBox, QStyledItemDelegate
from _typeshed import Incomplete

class MultiSelectComboBox(QComboBox):
    check_changed: Incomplete
    class __CheckingStyledItemDelegate(QStyledItemDelegate):
        def paint(self, painter, option, index) -> None: ...
    def __init__(self) -> None: ...
    def paintEvent(self, event) -> None: ...
    def add_check_item(self, checked, text) -> None: ...
    def set_item_text(self, index, text) -> None: ...
    def set_item_checked(self, index, checked) -> None: ...
