from PyQt5.QtCore import QObject, QThread
from umlfri2.application.threadmanager import ThreadManager as ThreadManager

class QTThreadManager(QObject, ThreadManager):
    class __Thread(QThread):
        def __init__(self, callback) -> None: ...
        def run(self) -> None: ...
    def __init__(self) -> None: ...
    def execute_in_main_thread(self, function, *args) -> None: ...
    def start_thread(self, function): ...
