def osi_license_url(abbreviation: str) -> str: ...


class CommonLicense:
    def __init__(self, abbreviation: str) -> None: ...
    @property
    def abbreviation(self) -> str: ...
    @property
    def title(self) -> str: ...
    @property
    def url(self) -> str: ...
