from typing import (
    Iterator,
    List,
    Optional,
    Union,
)
from umlfri2.metamodel.translation.translation import Translation
from umlfri2.ufl.dialog.columns.check import UflDialogCheckColumn
from umlfri2.ufl.dialog.columns.complex import UflDialogComplexColumn
from umlfri2.ufl.dialog.columns.enum import UflDialogEnumColumn
from umlfri2.ufl.dialog.columns.valued import UflDialogValuedColumn
from umlfri2.ufl.objects.mutable.list import UflMutableList
from umlfri2.ufl.types.structured.list import UflListType
from umlfri2.ufl.types.structured.object import UflObjectAttribute


class UflDialogListTab:
    def __init__(
        self,
        attr: Optional[UflObjectAttribute],
        list_type: UflListType
    ) -> None: ...
    def add_column(
        self,
        column: Union[UflDialogEnumColumn, UflDialogComplexColumn, UflDialogValuedColumn, UflDialogCheckColumn]
    ) -> None: ...
    def associate(self, ufl_object: Optional[UflMutableList]) -> None: ...
    @property
    def can_delete(self) -> bool: ...
    @property
    def can_move_down(self) -> bool: ...
    @property
    def can_move_up(self) -> bool: ...
    @property
    def can_new(self) -> bool: ...
    @property
    def can_save(self) -> bool: ...
    def change_current_index(self, value: None) -> None: ...
    @property
    def columns(self) -> Iterator[str]: ...
    @property
    def current_index(self) -> None: ...
    def finish(self) -> None: ...
    def new(self) -> None: ...
    @property
    def rows(self) -> Iterator[List[str]]: ...
    def save(self) -> None: ...
    @property
    def should_save(self) -> bool: ...
    def translate(self, translation: Translation) -> None: ...
