from typing import (
    Iterator,
    Optional,
    Union,
)
from umlfri2.metamodel.translation.translation import Translation
from umlfri2.ufl.dialog.widgets.text import UflDialogTextWidget
from umlfri2.ufl.dialog.widgets.widget import UflDialogWidget
from umlfri2.ufl.objects.mutable.object import UflMutableObject
from umlfri2.ufl.types.structured.object import UflObjectAttribute


class UflDialogTab:
    def __init__(self, attr: Optional[UflObjectAttribute]) -> None: ...
    def _associate_tab_index(self, tab_index: int) -> None: ...
    def _set_current_object(
        self,
        ufl_object: Optional[Union[UflMutableObject, str]]
    ) -> None: ...
    def add_widget(self, widget: UflDialogWidget) -> None: ...
    @property
    def current_object(self) -> Optional[Union[UflMutableObject, str]]: ...
    @property
    def first_widget(self) -> UflDialogTextWidget: ...
    @property
    def has_changes(self) -> bool: ...
    @property
    def id(self) -> Optional[str]: ...
    @property
    def name(self) -> Optional[str]: ...
    @property
    def tab_index(self) -> int: ...
    def translate(self, translation: Translation) -> None: ...
    @property
    def widget_count(self) -> int: ...
    @property
    def widgets(self) -> Iterator[UflDialogWidget]: ...
