from umlfri2.ufl.dialog.widgets.textarea import UflDialogTextAreaWidget


class UflDialogValueTab:
    def add_widget(self, widget: UflDialogTextAreaWidget) -> None: ...
    def finish(self) -> None: ...
    @property
    def widget(self) -> UflDialogTextAreaWidget: ...
