from PyQt5.QtWidgets import QDialog, QListWidgetItem
from umlfri2.application import Application as Application
from umlfri2.qtgui.base import image_loader as image_loader

class TemplateItem(QListWidgetItem):
    def __init__(self, template) -> None: ...
    @property
    def template(self): ...

class NewProjectDialog(QDialog):
    def __init__(self, main_window) -> None: ...
    def sizeHint(self): ...
    @property
    def selected_template(self): ...
    @property
    def new_solution(self): ...
    @property
    def project_name(self): ...
    @staticmethod
    def open_dialog(main_window): ...
