from ..state import AddOnState as AddOnState

class AddOnStarter:
    class __StartErrorException(Exception): ...
    def __init__(self, manager, *addons) -> None: ...
    @property
    def finished(self): ...
    @property
    def has_error(self): ...
    def do(self) -> None: ...
