from .action import Action as Action
from umlfri2.application.commands.diagram import AddDiagramElementCommand as AddDiagramElementCommand

class AddElementAction(Action):
    def __init__(self, type) -> None: ...
    @property
    def element_type(self): ...
    def mouse_down(self, point) -> None: ...
    def mouse_up(self) -> None: ...
