from ..drawingareacursor import DrawingAreaCursor as DrawingAreaCursor
from .action import Action as Action
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.commands.diagram import MoveConnectionPointCommand as MoveConnectionPointCommand
from umlfri2.types.geometry import PathBuilder as PathBuilder, Point as Point

class MoveConnectionPointAction(Action):
    def __init__(self, connection, index) -> None: ...
    @property
    def path(self): ...
    @property
    def cursor(self): ...
    @property
    def horizontal_snapping_indicators(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def vertical_snapping_indicators(self) -> Generator[Incomplete, Incomplete]: ...
    def snap_to(self, snapping) -> None: ...
    def mouse_down(self, point) -> None: ...
    def mouse_move(self, point) -> None: ...
    def mouse_up(self) -> None: ...
