from ..drawingareacursor import DrawingAreaCursor as DrawingAreaCursor
from .action import Action as Action
from umlfri2.application.commands.diagram import MoveConnectionLabelCommand as MoveConnectionLabelCommand
from umlfri2.types.geometry import Vector as Vector

class MoveConnectionLabelAction(Action):
    def __init__(self, connection, id) -> None: ...
    @property
    def cursor(self): ...
    @property
    def box(self): ...
    def mouse_down(self, point) -> None: ...
    def mouse_move(self, point) -> None: ...
    def mouse_up(self) -> None: ...
