from ..drawingareacursor import DrawingAreaCursor as DrawingAreaCursor
from ..selectionpointposition import SelectionPointPosition as SelectionPointPosition
from .action import Action as Action
from umlfri2.application.commands.diagram import ResizeMoveElementCommand as ResizeMoveElementCommand
from umlfri2.types.geometry import Rectangle as Rectangle

class ResizeElementAction(Action):
    def __init__(self, element, horizontal, vertical) -> None: ...
    @property
    def box(self): ...
    @property
    def cursor(self): ...
    def mouse_down(self, point) -> None: ...
    def mouse_move(self, point) -> None: ...
    def mouse_up(self) -> None: ...
