from .patch import UflPatch as UflPatch

class UflFlagsPatch(UflPatch):
    class ItemAdded:
        def __init__(self, new_value) -> None: ...
        @property
        def new_value(self): ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
    class ItemRemoved:
        def __init__(self, old_value) -> None: ...
        @property
        def old_value(self): ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
