from .patch import UflPatch as UflPatch

class UflObjectPatch(UflPatch):
    class AttributeChanged:
        def __init__(self, name, old_value, new_value) -> None: ...
        @property
        def name(self): ...
        @property
        def old_value(self): ...
        @property
        def new_value(self): ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
    class AttributePatch:
        def __init__(self, name, patch) -> None: ...
        @property
        def name(self): ...
        @property
        def patch(self): ...
        def make_reverse(self): ...
        def debug_print(self, file, level) -> None: ...
