class UflPatch:
    def __init__(self, type, changes) -> None: ...
    def __iter__(self): ...
    @property
    def type(self): ...
    @property
    def has_changes(self): ...
    def make_reverse(self): ...
    def get_lonely_change(self): ...
    def debug_print(self, file, indent: int = 0) -> None: ...
