from typing import (
    Iterator,
    Optional,
    Union,
)
from umlfri2.metamodel.connectiontype import ConnectionType
from umlfri2.metamodel.diagramtype import DiagramType
from umlfri2.metamodel.elementtype import ElementType
from umlfri2.model.cache import ModelTemporaryDataCache
from umlfri2.model.connection.connectionobject import ConnectionObject
from umlfri2.model.diagram import Diagram
from umlfri2.model.element.elementvisual import ElementVisual
from umlfri2.model.project import Project
from umlfri2.qtgui.rendering.qtruler import QTRuler
from umlfri2.ufl.components.visual.visualcontainer import VisualObjectContainer
from umlfri2.ufl.dialog.dialog import UflDialog
from umlfri2.ufl.dialog.options import UflDialogOptions
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.patch.object import UflObjectPatch
from uuid import UUID


class ElementObject:
    def __init__(
        self,
        parent: Union[Project, ElementObject],
        type: ElementType,
        save_id: Optional[UUID] = ...
    ) -> None: ...
    def add_child(
        self,
        obj: Union[Diagram, ElementObject],
        index: Optional[int] = ...
    ) -> None: ...
    def add_visual(self, visual: ElementVisual) -> None: ...
    def apply_ufl_patch(self, patch: UflObjectPatch) -> None: ...
    @property
    def cache(self) -> ModelTemporaryDataCache: ...
    def change_parent(self, new_parent: ElementObject, new_index: int) -> None: ...
    @property
    def children(self) -> Iterator[ElementObject]: ...
    @property
    def children_count(self) -> int: ...
    def connect_with(
        self,
        connection_type: ConnectionType,
        second_element: ElementObject,
        save_id: Optional[UUID] = ...
    ) -> ConnectionObject: ...
    @property
    def connections(self) -> Iterator[ConnectionObject]: ...
    def create_appearance_object(
        self,
        ruler: QTRuler
    ) -> VisualObjectContainer: ...
    def create_child_diagram(
        self,
        type: DiagramType,
        save_id: Optional[UUID] = ...
    ) -> Diagram: ...
    def create_child_element(
        self,
        type: ElementType,
        save_id: Optional[UUID] = ...
    ) -> ElementObject: ...
    def create_ufl_dialog(
        self,
        options: UflDialogOptions = ...
    ) -> UflDialog: ...
    @property
    def data(self) -> UflObject: ...
    @property
    def diagram_count(self) -> int: ...
    @property
    def diagrams(self) -> Iterator[Diagram]: ...
    def get_child_index(self, obj: ElementObject) -> int: ...
    def get_connections_to(self, element: ElementObject) -> None: ...
    def get_display_name(self) -> Optional[str]: ...
    @property
    def has_ufl_dialog(self) -> bool: ...
    def invalidate_all_caches(self) -> None: ...
    @property
    def parent(self) -> Union[Project, ElementObject]: ...
    @property
    def project(self) -> Project: ...
    def remove_child(
        self,
        obj: Union[Diagram, ElementObject]
    ) -> None: ...
    def remove_connection(self, connection: ConnectionObject) -> None: ...
    def remove_visual(self, visual: ElementVisual) -> None: ...
    @property
    def save_id(self) -> UUID: ...
    @property
    def type(self) -> ElementType: ...
    @property
    def visuals(self) -> Iterator[ElementVisual]: ...


class ElementValueGenerator:
    def __init__(
        self,
        parent: Union[Project, ElementObject],
        type: ElementType
    ) -> None: ...
    def for_name(self, name: str) -> ElementValueGenerator: ...
    def get_parent_name(self) -> str: ...
    def has_value(self, value: str) -> bool: ...
