from typing import (
    Iterator,
    Tuple,
)
from umlfri2.model.cache import ModelTemporaryDataCache
from umlfri2.model.connection.connectionvisual import ConnectionVisual
from umlfri2.model.diagram import Diagram
from umlfri2.model.element.elementobject import ElementObject
from umlfri2.qtgui.rendering.qtpaintercanvas import QTPainterCanvas
from umlfri2.qtgui.rendering.qtruler import QTRuler
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.rectangle import Rectangle
from umlfri2.types.geometry.size import Size


class ElementVisual:
    def __init__(
        self,
        diagram: Diagram,
        object: ElementObject
    ) -> None: ...
    def add_connection(self, connection: ConnectionVisual) -> None: ...
    @property
    def cache(self) -> ModelTemporaryDataCache: ...
    @property
    def connections(self) -> Iterator[ConnectionVisual]: ...
    @property
    def diagram(self) -> Diagram: ...
    def draw(self, canvas: QTPainterCanvas) -> None: ...
    def get_bounds(self, ruler: QTRuler) -> Rectangle: ...
    def get_minimal_size(self, ruler: QTRuler) -> Size: ...
    def get_position(self, ruler: QTRuler) -> Point: ...
    def get_size(self, ruler: QTRuler) -> Size: ...
    def is_at_position(
        self,
        ruler: QTRuler,
        position: Point
    ) -> bool: ...
    def is_resizable(self, ruler: QTRuler) -> Tuple[bool, bool]: ...
    def move(
        self,
        ruler: QTRuler,
        new_position: Point
    ) -> None: ...
    @property
    def object(self) -> ElementObject: ...
    def remove_connection(self, connection: ConnectionVisual) -> None: ...
    def resize(self, ruler: QTRuler, new_size: Size) -> None: ...
