from typing import Optional
from umlfri2.qtgui.rendering.qtruler import QTRuler


class Command:
    def do(self, ruler: QTRuler) -> None: ...
    @property
    def has_error(self) -> Optional[bool]: ...
    def redo(self, ruler: QTRuler) -> None: ...
    def undo(self, ruler: QTRuler) -> None: ...
