from ..base import Command as Command
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.events.diagram import ConnectionShownEvent as ConnectionShownEvent
from umlfri2.application.events.model import ConnectionCreatedEvent as ConnectionCreatedEvent

class AddDiagramConnectionCommand(Command):
    def __init__(self, diagram, connection_type, source_element, destination_element, points) -> None: ...
    @property
    def description(self): ...
    @property
    def connection_visual(self): ...
    @property
    def connection_object(self): ...
    def get_updates(self) -> Generator[Incomplete]: ...
