from ..base import Command as Command
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.events.diagram import ElementShownEvent as ElementShownEvent
from umlfri2.application.events.model import ElementCreatedEvent as ElementCreatedEvent

class AddDiagramElementCommand(Command):
    def __init__(self, diagram, element_type, point) -> None: ...
    @property
    def description(self): ...
    @property
    def element_visual(self): ...
    @property
    def element_object(self): ...
    def get_updates(self) -> Generator[Incomplete]: ...
