from ..base import Command as Command, CommandNotDone as CommandNotDone
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.application.events.diagram import ConnectionShownEvent as ConnectionShownEvent, ElementShownEvent as ElementShownEvent

class ShowElementCommand(Command):
    def __init__(self, diagram, element_object, point) -> None: ...
    @property
    def description(self): ...
    @property
    def element_visual(self): ...
    @property
    def element_object(self): ...
    def get_updates(self) -> Generator[Incomplete]: ...
