from ...compilerhelpers.automultiresolver import resolve_multi_source as resolve_multi_source, resolve_multi_type as resolve_multi_type
from ...macro.inlined import InlinedMacro as InlinedMacro
from ...types.basic import UflStringType as UflStringType
from ...types.complex import UflColorType as UflColorType, UflFontType as UflFontType
from ...types.enum import UflTypedEnumType as UflTypedEnumType
from ...types.structured import UflVariableWithMetadataType as UflVariableWithMetadataType
from ..tree.visitor import UflVisitor as UflVisitor
from .varnameregister import VariableNameRegister as VariableNameRegister
from umlfri2.types.color import Colors as Colors
from umlfri2.types.enums import ALL_ENUMS as ALL_ENUMS
from umlfri2.types.font import Fonts as Fonts

class UflCompilingVisitor(UflVisitor):
    def __init__(self, variable_prefix) -> None: ...
    def visit_attribute_access(self, node): ...
    def visit_enum(self, node): ...
    def visit_macro_invoke(self, node): ...
    def visit_technical_variable(self, node): ...
    def visit_variable(self, node): ...
    def visit_variable_definition(self, node): ...
    def visit_binary(self, node): ...
    def visit_unary(self, node): ...
    def visit_literal(self, node): ...
    def visit_variable_metadata_access(self, node): ...
    def visit_object_metadata_access(self, node): ...
    def visit_unpack(self, node): ...
    def visit_expression(self, node): ...
    def visit_lambda_expression(self, node): ...
    def visit_cast(self, node): ...
    @property
    def all_globals(self): ...
