from ...objects import UflList as UflList
from ..base.type import UflType as UflType

class UflListType(UflType):
    def __init__(self, item_type) -> None: ...
    @property
    def item_type(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator): ...
    def is_assignable_from(self, other): ...
    def is_default_value(self, value): ...
    @property
    def is_immutable(self): ...
    def set_parent(self, parent) -> None: ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
