from ...objects import UflList as UflList
from ..base.type import UflType as UflType

from typing import Union
from umlfri2.model.element.elementobject import ElementValueGenerator
from umlfri2.ufl.objects.immutable.list import UflList
from umlfri2.ufl.objects.mutable.list import ListItemValueGenerator
from umlfri2.ufl.types.structured.object import (
    UflObjectAttribute,
    UflObjectType,
)

class UflListType(UflType):
    def __init__(self, item_type: UflObjectType) -> None: ...
    @property
    def item_type(self) -> UflObjectType: ...
    @property
    def has_default(self): ...
    def build_default(
        self,
        generator: Union[ListItemValueGenerator, ElementValueGenerator]
    ) -> UflList: ...
    def is_assignable_from(self, other): ...
    def is_default_value(self, value: UflList) -> bool: ...
    @property
    def is_immutable(self) -> bool: ...
    def set_parent(self, parent: UflObjectAttribute) -> None: ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
