from ..base.type import UflType as UflType
from ..basic.string import UflStringType as UflStringType

from typing import (
    Any,
    Union,
)
from umlfri2.ufl.types.basic.integer import UflIntegerType
from umlfri2.ufl.types.complex.color import UflColorType
from umlfri2.ufl.types.enum.definedenum import UflDefinedEnumType
from umlfri2.ufl.types.enum.typedenum import UflTypedEnumType

class UflNullableType(UflType):
    def __init__(self, inner_type: Any) -> None: ...
    @property
    def inner_type(
        self
    ) -> Union[UflTypedEnumType, UflColorType, UflIntegerType, UflDefinedEnumType]: ...
    @property
    def has_default(self): ...
    def build_default(self, generator) -> None: ...
    def parse(self, value: str) -> Any: ...
    def is_assignable_from(
        self,
        other: Union[UflColorType, UflNullableType]
    ) -> bool: ...
    def is_equatable_to(self, other): ...
    def is_convertible_to(self, other): ...
    @property
    def is_immutable(self): ...
    def is_default_value(self, value): ...
    def is_valid_value(self, value): ...
    def set_parent(self, parent) -> None: ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
