from ..base.type import UflType as UflType
from ..basic.string import UflStringType as UflStringType

class UflNullableType(UflType):
    def __init__(self, inner_type) -> None: ...
    @property
    def inner_type(self): ...
    @property
    def has_default(self): ...
    def build_default(self, generator) -> None: ...
    def parse(self, value): ...
    def is_assignable_from(self, other): ...
    def is_equatable_to(self, other): ...
    def is_convertible_to(self, other): ...
    @property
    def is_immutable(self): ...
    def is_default_value(self, value): ...
    def is_valid_value(self, value): ...
    def set_parent(self, parent) -> None: ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
