from ...objects import UflObject as UflObject
from ..base.type import UflType as UflType
from ..structured import UflNullableType as UflNullableType
from _typeshed import Incomplete
from collections.abc import Generator

from typing import (
    Any,
    Iterator,
    Optional,
    Tuple,
    Union,
)
from umlfri2.model.diagram import DiagramValueGenerator
from umlfri2.model.element.elementobject import ElementValueGenerator
from umlfri2.ufl.objects.immutable.object import UflObject
from umlfri2.ufl.objects.mutable.list import ListItemValueGenerator
from umlfri2.ufl.objects.mutable.object import UflMutableObject
from umlfri2.ufl.types.base.type import UflType

class UflObjectAttribute:
    def __init__(self, name: str, type: UflType) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def type(self) -> UflType: ...
    @property
    def parent(self) -> UflObjectType: ...
    def set_parent(self, parent: UflObjectType) -> None: ...
    def create_as_non_nullable(self): ...

class UflObjectType(UflType):
    def __init__(self, attributes: Tuple[UflObjectAttribute, Ellipsis]) -> None: ...
    @property
    def attributes(self) -> Iterator[UflObjectAttribute]: ...
    @property
    def has_attributes(self) -> bool: ...
    def get_attribute(self, name: str) -> UflObjectAttribute: ...
    def contains_attribute(self, name: str) -> bool: ...
    @property
    def has_default(self): ...
    def build_default(
        self,
        generator: Optional[Union[ListItemValueGenerator, ElementValueGenerator, DiagramValueGenerator]]
    ) -> UflObject: ...
    def is_assignable_from(self, other): ...
    @property
    def is_immutable(self) -> bool: ...
    def is_default_value(self, value: UflObject) -> bool: ...
    def is_valid_value(self, value: UflMutableObject) -> bool: ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
    def set_parent(self, parent: Any) -> None: ...
