from ...objects import UflObject as UflObject
from ..base.type import UflType as UflType
from ..structured import UflNullableType as UflNullableType
from _typeshed import Incomplete
from collections.abc import Generator

class UflObjectAttribute:
    def __init__(self, name, type) -> None: ...
    @property
    def name(self): ...
    @property
    def type(self): ...
    @property
    def parent(self): ...
    def set_parent(self, parent) -> None: ...
    def create_as_non_nullable(self): ...

class UflObjectType(UflType):
    def __init__(self, attributes) -> None: ...
    @property
    def attributes(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def has_attributes(self): ...
    def get_attribute(self, name): ...
    def contains_attribute(self, name): ...
    @property
    def has_default(self): ...
    def build_default(self, generator): ...
    def is_assignable_from(self, other): ...
    @property
    def is_immutable(self): ...
    def is_default_value(self, value): ...
    def is_valid_value(self, value): ...
    def resolve_unknown_generic(self, generics_cache): ...
    def resolve_generic(self, actual_type, generics_cache): ...
    def set_parent(self, parent) -> None: ...
