from ..base.type import UflAttributeDescription as UflAttributeDescription, UflType as UflType
from _typeshed import Incomplete
from collections.abc import Generator

class UflVariableMetadataType(UflType):
    ALLOWED_DIRECT_ATTRIBUTES: Incomplete
    def __init__(self, metadata_type, underlying_type) -> None: ...
    @property
    def is_immutable(self): ...

class UflVariableWithMetadataType(UflType):
    VALUE_ATTRIBUTE: str
    def __init__(self, underlying_type, **metadata_types) -> None: ...
    @property
    def metadata_types(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def underlying_type(self): ...
    @property
    def metadata_type(self): ...
    def is_equatable_to(self, other): ...
    def is_comparable_with(self, other): ...
    def is_convertible_to(self, other): ...
    def resolve_unknown_generic(self, generics_cache) -> None: ...
    def resolve_generic(self, actual_type, generics_cache) -> None: ...
