from typing import (
    Any,
    List,
    Optional,
)
from umlfri2.application.application import Application
from umlfri2.application.drawingarea.actions.action import ActionMenuItem
from umlfri2.application.drawingarea.drawingareacursor import DrawingAreaCursor
from umlfri2.application.drawingarea.selection import Selection
from umlfri2.model.diagram import Diagram
from umlfri2.qtgui.rendering.qtpaintercanvas import QTPainterCanvas
from umlfri2.qtgui.rendering.qtruler import QTRuler
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.size import Size


class DrawingArea:
    def __init__(
        self,
        application: Application,
        diagram: Diagram
    ) -> None: ...
    @property
    def action_active(self) -> bool: ...
    @property
    def can_copy_snippet(self) -> bool: ...
    @property
    def can_paste_snippet(self) -> bool: ...
    @property
    def can_paste_snippet_duplicate(self) -> bool: ...
    @property
    def can_zoom_in(self) -> bool: ...
    @property
    def can_zoom_original(self) -> bool: ...
    @property
    def can_zoom_out(self) -> bool: ...
    def copy_snippet(self) -> None: ...
    @property
    def current_action(self) -> None: ...
    @property
    def cursor(self) -> DrawingAreaCursor: ...
    @property
    def diagram(self) -> Diagram: ...
    def draw(self, canvas: QTPainterCanvas) -> None: ...
    def ensure_selection_at(self, point: Point) -> None: ...
    def execute_menu_action(
        self,
        menu_item: ActionMenuItem,
        point: Point,
        control_pressed: bool,
        shift_pressed: bool
    ) -> None: ...
    def get_size(self, ruler: QTRuler) -> Size: ...
    @property
    def menu_to_show(self) -> Optional[List[ActionMenuItem]]: ...
    def mouse_down(self, point: Point, control_pressed: bool, shift_pressed: bool) -> None: ...
    def mouse_move(self, point: Point, control_pressed: bool, shift_pressed: bool) -> None: ...
    def mouse_up(self, point: Point, control_pressed: bool, shift_pressed: bool) -> None: ...
    def reset_action(self) -> None: ...
    @property
    def selection(self) -> Selection: ...
    def set_action(self, action: Any) -> None: ...
    def zoom_in(self) -> None: ...
    def zoom_out(self) -> None: ...
