from typing import (
    Any,
    Iterator,
    Optional,
    Union,
)
from umlfri2.application.application import Application
from umlfri2.model.connection.connectionvisual import ConnectionVisual
from umlfri2.model.diagram import Diagram
from umlfri2.model.element.elementvisual import ElementVisual
from umlfri2.qtgui.rendering.qtpaintercanvas import QTPainterCanvas
from umlfri2.types.geometry.point import Point
from umlfri2.types.geometry.rectangle import Rectangle


class Selection:
    def __init__(
        self,
        application: Application,
        diagram: Diagram
    ) -> None: ...
    def add_to_selection(
        self,
        visual: Union[ElementVisual, ConnectionVisual]
    ) -> None: ...
    def deselect_all(self) -> None: ...
    @property
    def diagram(self) -> Diagram: ...
    def draw_for(
        self,
        canvas: QTPainterCanvas,
        visual: Union[ElementVisual, ConnectionVisual]
    ) -> None: ...
    def get_action_at(self, position: Point, shift_pressed: bool) -> Any: ...
    def get_bounds(self, include_connections: bool = ...) -> Rectangle: ...
    def get_lonely_selected_visual(
        self
    ) -> Union[ElementVisual, ConnectionVisual]: ...
    @property
    def is_connection_selected(self) -> bool: ...
    @property
    def is_diagram_selected(self) -> bool: ...
    @property
    def is_element_selected(self) -> bool: ...
    def is_selection_at(self, position: Point) -> bool: ...
    def select(
        self,
        visual: Optional[Union[ElementVisual, ConnectionVisual]]
    ) -> None: ...
    def select_at(self, point: Point) -> None: ...
    def select_in_area(self, area: Rectangle) -> None: ...
    @property
    def selected_connection(self) -> ConnectionVisual: ...
    @property
    def selected_diagram(self) -> Diagram: ...
    @property
    def selected_elements(self) -> Iterator[ElementVisual]: ...
    def toggle_select(self, visual: ElementVisual) -> None: ...
