from .startpageframeaction import StartPageFrameAction as StartPageFrameAction
from PyQt5.QtWidgets import QWidget

class StartPageFrame(QWidget):
    WIDTH: int
    HEIGHT: int
    THICKNESS: int
    def __init__(self) -> None: ...
    def paintEvent(self, event) -> None: ...
    def sizeHint(self): ...
    def add_frame_action(self): ...
    def clear(self) -> None: ...
