from PyQt5.QtWidgets import QWidget

class StartPageFrameAction(QWidget):
    def __init__(self) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, value) -> None: ...
    @property
    def pixmap(self): ...
    @pixmap.setter
    def pixmap(self, value) -> None: ...
    @property
    def tooltip(self): ...
    @tooltip.setter
    def tooltip(self, value) -> None: ...
    def set_action_callback(self, callback): ...
    def set_context_menu_builder(self, menu_builder) -> None: ...
