from PyQt5.QtWidgets import QTabBar

class MiddleClosableTabBar(QTabBar):
    def __init__(self) -> None: ...
    def mousePressEvent(self, event) -> None: ...
    def mouseReleaseEvent(self, event) -> None: ...
