from umlfri2.model.project import Project


class ProjectTab:
    def __init__(self, project: Project) -> None: ...
    @property
    def label(self) -> str: ...
    def reload_data(self) -> None: ...
    def reload_texts(self) -> None: ...
