from .connection import ConnectionObject as ConnectionObject, ConnectionVisual as ConnectionVisual
from .element import ElementObject as ElementObject, ElementVisual as ElementVisual
from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.types.geometry import Rectangle as Rectangle
from umlfri2.ufl.dialog import UflDialog as UflDialog, UflDialogOptions as UflDialogOptions
from umlfri2.ufl.uniquevaluegenerator import UniqueValueGenerator as UniqueValueGenerator

class DiagramValueGenerator(UniqueValueGenerator):
    def __init__(self, parent, type) -> None: ...
    def get_parent_name(self): ...
    def for_name(self, name): ...
    def has_value(self, value): ...

class Diagram:
    def __init__(self, parent, type, save_id=None) -> None: ...
    @property
    def parent(self): ...
    def change_parent(self, new_parent, new_index) -> None: ...
    @property
    def project(self): ...
    @property
    def type(self): ...
    @property
    def data(self): ...
    @property
    def elements(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def element_count(self): ...
    @property
    def connections(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def save_id(self): ...
    def get_display_name(self): ...
    def show(self, object): ...
    def add(self, visual, z_order=None) -> None: ...
    def remove(self, visual) -> None: ...
    def get_z_order(self, visual): ...
    def change_z_order(self, visual, z_order) -> None: ...
    def change_z_order_many(self, z_order_visuals) -> None: ...
    def draw_background(self, canvas) -> None: ...
    def draw(self, canvas, selection=None, transparent: bool = False) -> None: ...
    def get_visual_for(self, object): ...
    def get_visual_at(self, ruler, position): ...
    def get_visual_above(self, ruler, visual, skip=...): ...
    def get_visual_below(self, ruler, visual, skip=...): ...
    def get_size(self, ruler): ...
    def get_bounds(self, ruler): ...
    def contains(self, object): ...
    def apply_ufl_patch(self, patch) -> None: ...
    @property
    def has_ufl_dialog(self): ...
    def create_ufl_dialog(self, options=...): ...
