from _typeshed import Incomplete
from collections.abc import Generator
from umlfri2.model import ElementObject as ElementObject
from umlfri2.ufl.dialog import UflDialog as UflDialog

class Project:
    def __init__(self, metamodel, name=None, save_id=None) -> None: ...
    @property
    def parent(self) -> None: ...
    def get_display_name(self): ...
    @property
    def name(self): ...
    @name.setter
    def name(self, new_name) -> None: ...
    @property
    def metamodel(self): ...
    @property
    def children_count(self): ...
    @property
    def children(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def save_id(self): ...
    def create_child_element(self, type, save_id=None): ...
    def get_child_index(self, obj): ...
    def add_child(self, obj, index=None) -> None: ...
    def remove_child(self, obj) -> None: ...
    def get_all_elements(self): ...
    def invalidate_all_caches(self) -> None: ...
    @property
    def config(self): ...
    def apply_config_patch(self, patch) -> None: ...
    def create_config_dialog(self): ...
