from _typeshed import Incomplete
from collections.abc import Generator

class Solution:
    def __init__(self, project=None, save_id=None) -> None: ...
    def add_project(self, project) -> None: ...
    def remove_project(self, project) -> None: ...
    @property
    def children(self) -> Generator[Incomplete, Incomplete]: ...
    @property
    def save_id(self): ...
    def get_all_diagrams(self) -> Generator[Incomplete, Incomplete]: ...
    def get_all_elements(self) -> Generator[Incomplete, Incomplete]: ...
    def invalidate_all_caches(self) -> None: ...
