from umlfri2.qtgui.rendering import PagedRenderer as PagedRenderer

class DiagramPrinting:
    def __init__(self, printing, diagram) -> None: ...
    def show_preview(self) -> None: ...
    def print(self) -> None: ...
