from .diagramprinting import DiagramPrinting as DiagramPrinting

has_printing_support: bool

class MetaPrinting(type):
    def __call__(cls): ...

class Printing(metaclass=MetaPrinting):
    def __init__(self) -> None: ...
    @property
    def printer(self): ...
    def for_diagram(self, diagram): ...
    def show_page_setup(self) -> None: ...
    @property
    def has_printing_support(self): ...
    @property
    def can_print(self): ...
